//1_1_1024_7_1_16
//128_2048_7_7_512_1_1_SAME
//dim3 grid(1, 1, 1024);
//dim3 block(7, 1, 16);

#ifdef _WIN32
  using uint = unsigned int;
  using uchar = unsigned char;
  using ushort = unsigned short;
  using int64_t = long long;
  using uint64_t = unsigned long long;
#else
  #define uint unsigned int
  #define uchar unsigned char
  #define ushort unsigned short
  #define int64_t long long
  #define uint64_t unsigned long long
#endif
extern "C" __global__ void __launch_bounds__(112) conv_kernel0(float* __restrict__ placeholder, float* __restrict__ placeholder1, float* __restrict__ compute, float* __restrict__ input2) {
  float compute1[28];
  __shared__ float pad_temp_shared[784];
  __shared__ float placeholder_shared[1024];
  compute1[(0)] = 0.000000e+00f;
  compute1[(7)] = 0.000000e+00f;
  compute1[(14)] = 0.000000e+00f;
  compute1[(21)] = 0.000000e+00f;
  compute1[(1)] = 0.000000e+00f;
  compute1[(8)] = 0.000000e+00f;
  compute1[(15)] = 0.000000e+00f;
  compute1[(22)] = 0.000000e+00f;
  compute1[(2)] = 0.000000e+00f;
  compute1[(9)] = 0.000000e+00f;
  compute1[(16)] = 0.000000e+00f;
  compute1[(23)] = 0.000000e+00f;
  compute1[(3)] = 0.000000e+00f;
  compute1[(10)] = 0.000000e+00f;
  compute1[(17)] = 0.000000e+00f;
  compute1[(24)] = 0.000000e+00f;
  compute1[(4)] = 0.000000e+00f;
  compute1[(11)] = 0.000000e+00f;
  compute1[(18)] = 0.000000e+00f;
  compute1[(25)] = 0.000000e+00f;
  compute1[(5)] = 0.000000e+00f;
  compute1[(12)] = 0.000000e+00f;
  compute1[(19)] = 0.000000e+00f;
  compute1[(26)] = 0.000000e+00f;
  compute1[(6)] = 0.000000e+00f;
  compute1[(13)] = 0.000000e+00f;
  compute1[(20)] = 0.000000e+00f;
  compute1[(27)] = 0.000000e+00f;
  for (int rc_outer = 0; rc_outer < 128; ++rc_outer) {
    __syncthreads();
    pad_temp_shared[(((((int)threadIdx.z) * 49) + (((int)threadIdx.x) * 7)))] = placeholder[((((((((int)blockIdx.z) >> 3) * 100352) + (rc_outer * 784)) + (((int)threadIdx.z) * 49)) + (((int)threadIdx.x) * 7)))];
    pad_temp_shared[((((((int)threadIdx.z) * 49) + (((int)threadIdx.x) * 7)) + 1))] = placeholder[(((((((((int)blockIdx.z) >> 3) * 100352) + (rc_outer * 784)) + (((int)threadIdx.z) * 49)) + (((int)threadIdx.x) * 7)) + 1))];
    pad_temp_shared[((((((int)threadIdx.z) * 49) + (((int)threadIdx.x) * 7)) + 2))] = placeholder[(((((((((int)blockIdx.z) >> 3) * 100352) + (rc_outer * 784)) + (((int)threadIdx.z) * 49)) + (((int)threadIdx.x) * 7)) + 2))];
    pad_temp_shared[((((((int)threadIdx.z) * 49) + (((int)threadIdx.x) * 7)) + 3))] = placeholder[(((((((((int)blockIdx.z) >> 3) * 100352) + (rc_outer * 784)) + (((int)threadIdx.z) * 49)) + (((int)threadIdx.x) * 7)) + 3))];
    pad_temp_shared[((((((int)threadIdx.z) * 49) + (((int)threadIdx.x) * 7)) + 4))] = placeholder[(((((((((int)blockIdx.z) >> 3) * 100352) + (rc_outer * 784)) + (((int)threadIdx.z) * 49)) + (((int)threadIdx.x) * 7)) + 4))];
    pad_temp_shared[((((((int)threadIdx.z) * 49) + (((int)threadIdx.x) * 7)) + 5))] = placeholder[(((((((((int)blockIdx.z) >> 3) * 100352) + (rc_outer * 784)) + (((int)threadIdx.z) * 49)) + (((int)threadIdx.x) * 7)) + 5))];
    pad_temp_shared[((((((int)threadIdx.z) * 49) + (((int)threadIdx.x) * 7)) + 6))] = placeholder[(((((((((int)blockIdx.z) >> 3) * 100352) + (rc_outer * 784)) + (((int)threadIdx.z) * 49)) + (((int)threadIdx.x) * 7)) + 6))];
    placeholder_shared[(((((int)threadIdx.z) * 64) + (((int)threadIdx.x) * 10)))] = placeholder1[(((((((((int)blockIdx.z) & 7) * 131072) + (((int)threadIdx.z) * 8192)) + (((((int)threadIdx.x) * 10) >> 4) * 2048)) + (rc_outer * 16)) + ((((int)threadIdx.x) * 10) & 15)))];
    placeholder_shared[((((((int)threadIdx.z) * 64) + (((int)threadIdx.x) * 10)) + 1))] = placeholder1[(((((((((int)blockIdx.z) & 7) * 131072) + (((int)threadIdx.z) * 8192)) + ((((((int)threadIdx.x) * 10) + 1) >> 4) * 2048)) + (rc_outer * 16)) + (((((int)threadIdx.x) * 10) + 1) & 15)))];
    placeholder_shared[((((((int)threadIdx.z) * 64) + (((int)threadIdx.x) * 10)) + 2))] = placeholder1[(((((((((int)blockIdx.z) & 7) * 131072) + (((int)threadIdx.z) * 8192)) + ((((((int)threadIdx.x) * 10) + 2) >> 4) * 2048)) + (rc_outer * 16)) + (((((int)threadIdx.x) * 10) + 2) & 15)))];
    placeholder_shared[((((((int)threadIdx.z) * 64) + (((int)threadIdx.x) * 10)) + 3))] = placeholder1[(((((((((int)blockIdx.z) & 7) * 131072) + (((int)threadIdx.z) * 8192)) + ((((((int)threadIdx.x) * 10) + 3) >> 4) * 2048)) + (rc_outer * 16)) + (((((int)threadIdx.x) * 10) + 3) & 15)))];
    if (((((int)threadIdx.z) * 4) + (((((int)threadIdx.x) * 10) + 4) >> 4)) < 64) {
      if (((((int)threadIdx.z) * 64) + (((int)threadIdx.x) * 10)) < 1020) {
        if (((int)threadIdx.x) < 6) {
          placeholder_shared[((((((int)threadIdx.z) * 64) + (((int)threadIdx.x) * 10)) + 4))] = placeholder1[(((((((((int)blockIdx.z) & 7) * 131072) + (((int)threadIdx.z) * 8192)) + ((((((int)threadIdx.x) * 10) + 4) >> 4) * 2048)) + (rc_outer * 16)) + (((((int)threadIdx.x) * 10) + 4) & 15)))];
        }
      }
    }
    if (((((int)threadIdx.z) * 4) + (((((int)threadIdx.x) * 10) + 5) >> 4)) < 64) {
      if (((((int)threadIdx.z) * 64) + (((int)threadIdx.x) * 10)) < 1019) {
        if (((int)threadIdx.x) < 6) {
          placeholder_shared[((((((int)threadIdx.z) * 64) + (((int)threadIdx.x) * 10)) + 5))] = placeholder1[(((((((((int)blockIdx.z) & 7) * 131072) + (((int)threadIdx.z) * 8192)) + ((((((int)threadIdx.x) * 10) + 5) >> 4) * 2048)) + (rc_outer * 16)) + (((((int)threadIdx.x) * 10) + 5) & 15)))];
        }
      }
    }
    if (((((int)threadIdx.z) * 4) + (((((int)threadIdx.x) * 10) + 6) >> 4)) < 64) {
      if (((((int)threadIdx.z) * 64) + (((int)threadIdx.x) * 10)) < 1018) {
        if (((int)threadIdx.x) < 6) {
          placeholder_shared[((((((int)threadIdx.z) * 64) + (((int)threadIdx.x) * 10)) + 6))] = placeholder1[(((((((((int)blockIdx.z) & 7) * 131072) + (((int)threadIdx.z) * 8192)) + ((((((int)threadIdx.x) * 10) + 6) >> 4) * 2048)) + (rc_outer * 16)) + (((((int)threadIdx.x) * 10) + 6) & 15)))];
        }
      }
    }
    if (((((int)threadIdx.z) * 4) + (((((int)threadIdx.x) * 10) + 7) >> 4)) < 64) {
      if (((((int)threadIdx.z) * 64) + (((int)threadIdx.x) * 10)) < 1017) {
        if (((int)threadIdx.x) < 6) {
          placeholder_shared[((((((int)threadIdx.z) * 64) + (((int)threadIdx.x) * 10)) + 7))] = placeholder1[(((((((((int)blockIdx.z) & 7) * 131072) + (((int)threadIdx.z) * 8192)) + ((((((int)threadIdx.x) * 10) + 7) >> 4) * 2048)) + (rc_outer * 16)) + (((((int)threadIdx.x) * 10) + 7) & 15)))];
        }
      }
    }
    if (((((int)threadIdx.z) * 4) + (((((int)threadIdx.x) * 10) + 8) >> 4)) < 64) {
      if (((((int)threadIdx.z) * 64) + (((int)threadIdx.x) * 10)) < 1016) {
        if (((int)threadIdx.x) < 6) {
          placeholder_shared[((((((int)threadIdx.z) * 64) + (((int)threadIdx.x) * 10)) + 8))] = placeholder1[(((((((((int)blockIdx.z) & 7) * 131072) + (((int)threadIdx.z) * 8192)) + ((((((int)threadIdx.x) * 10) + 8) >> 4) * 2048)) + (rc_outer * 16)) + (((((int)threadIdx.x) * 10) + 8) & 15)))];
        }
      }
    }
    if (((((int)threadIdx.z) * 4) + (((((int)threadIdx.x) * 10) + 9) >> 4)) < 64) {
      if (((((int)threadIdx.z) * 64) + (((int)threadIdx.x) * 10)) < 1015) {
        if (((int)threadIdx.x) < 6) {
          placeholder_shared[((((((int)threadIdx.z) * 64) + (((int)threadIdx.x) * 10)) + 9))] = placeholder1[(((((((((int)blockIdx.z) & 7) * 131072) + (((int)threadIdx.z) * 8192)) + ((((((int)threadIdx.x) * 10) + 9) >> 4) * 2048)) + (rc_outer * 16)) + (((((int)threadIdx.x) * 10) + 9) & 15)))];
        }
      }
    }
    __syncthreads();
    compute1[(0)] = (compute1[(0)] + (pad_temp_shared[(((int)threadIdx.x))] * placeholder_shared[((((int)threadIdx.z) * 16))]));
    compute1[(7)] = (compute1[(7)] + (pad_temp_shared[(((int)threadIdx.x))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 256))]));
    compute1[(14)] = (compute1[(14)] + (pad_temp_shared[(((int)threadIdx.x))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 512))]));
    compute1[(21)] = (compute1[(21)] + (pad_temp_shared[(((int)threadIdx.x))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 768))]));
    compute1[(1)] = (compute1[(1)] + (pad_temp_shared[((((int)threadIdx.x) + 7))] * placeholder_shared[((((int)threadIdx.z) * 16))]));
    compute1[(8)] = (compute1[(8)] + (pad_temp_shared[((((int)threadIdx.x) + 7))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 256))]));
    compute1[(15)] = (compute1[(15)] + (pad_temp_shared[((((int)threadIdx.x) + 7))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 512))]));
    compute1[(22)] = (compute1[(22)] + (pad_temp_shared[((((int)threadIdx.x) + 7))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 768))]));
    compute1[(2)] = (compute1[(2)] + (pad_temp_shared[((((int)threadIdx.x) + 14))] * placeholder_shared[((((int)threadIdx.z) * 16))]));
    compute1[(9)] = (compute1[(9)] + (pad_temp_shared[((((int)threadIdx.x) + 14))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 256))]));
    compute1[(16)] = (compute1[(16)] + (pad_temp_shared[((((int)threadIdx.x) + 14))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 512))]));
    compute1[(23)] = (compute1[(23)] + (pad_temp_shared[((((int)threadIdx.x) + 14))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 768))]));
    compute1[(3)] = (compute1[(3)] + (pad_temp_shared[((((int)threadIdx.x) + 21))] * placeholder_shared[((((int)threadIdx.z) * 16))]));
    compute1[(10)] = (compute1[(10)] + (pad_temp_shared[((((int)threadIdx.x) + 21))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 256))]));
    compute1[(17)] = (compute1[(17)] + (pad_temp_shared[((((int)threadIdx.x) + 21))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 512))]));
    compute1[(24)] = (compute1[(24)] + (pad_temp_shared[((((int)threadIdx.x) + 21))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 768))]));
    compute1[(4)] = (compute1[(4)] + (pad_temp_shared[((((int)threadIdx.x) + 28))] * placeholder_shared[((((int)threadIdx.z) * 16))]));
    compute1[(11)] = (compute1[(11)] + (pad_temp_shared[((((int)threadIdx.x) + 28))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 256))]));
    compute1[(18)] = (compute1[(18)] + (pad_temp_shared[((((int)threadIdx.x) + 28))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 512))]));
    compute1[(25)] = (compute1[(25)] + (pad_temp_shared[((((int)threadIdx.x) + 28))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 768))]));
    compute1[(5)] = (compute1[(5)] + (pad_temp_shared[((((int)threadIdx.x) + 35))] * placeholder_shared[((((int)threadIdx.z) * 16))]));
    compute1[(12)] = (compute1[(12)] + (pad_temp_shared[((((int)threadIdx.x) + 35))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 256))]));
    compute1[(19)] = (compute1[(19)] + (pad_temp_shared[((((int)threadIdx.x) + 35))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 512))]));
    compute1[(26)] = (compute1[(26)] + (pad_temp_shared[((((int)threadIdx.x) + 35))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 768))]));
    compute1[(6)] = (compute1[(6)] + (pad_temp_shared[((((int)threadIdx.x) + 42))] * placeholder_shared[((((int)threadIdx.z) * 16))]));
    compute1[(13)] = (compute1[(13)] + (pad_temp_shared[((((int)threadIdx.x) + 42))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 256))]));
    compute1[(20)] = (compute1[(20)] + (pad_temp_shared[((((int)threadIdx.x) + 42))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 512))]));
    compute1[(27)] = (compute1[(27)] + (pad_temp_shared[((((int)threadIdx.x) + 42))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 768))]));
    compute1[(0)] = (compute1[(0)] + (pad_temp_shared[((((int)threadIdx.x) + 49))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 1))]));
    compute1[(7)] = (compute1[(7)] + (pad_temp_shared[((((int)threadIdx.x) + 49))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 257))]));
    compute1[(14)] = (compute1[(14)] + (pad_temp_shared[((((int)threadIdx.x) + 49))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 513))]));
    compute1[(21)] = (compute1[(21)] + (pad_temp_shared[((((int)threadIdx.x) + 49))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 769))]));
    compute1[(1)] = (compute1[(1)] + (pad_temp_shared[((((int)threadIdx.x) + 56))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 1))]));
    compute1[(8)] = (compute1[(8)] + (pad_temp_shared[((((int)threadIdx.x) + 56))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 257))]));
    compute1[(15)] = (compute1[(15)] + (pad_temp_shared[((((int)threadIdx.x) + 56))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 513))]));
    compute1[(22)] = (compute1[(22)] + (pad_temp_shared[((((int)threadIdx.x) + 56))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 769))]));
    compute1[(2)] = (compute1[(2)] + (pad_temp_shared[((((int)threadIdx.x) + 63))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 1))]));
    compute1[(9)] = (compute1[(9)] + (pad_temp_shared[((((int)threadIdx.x) + 63))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 257))]));
    compute1[(16)] = (compute1[(16)] + (pad_temp_shared[((((int)threadIdx.x) + 63))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 513))]));
    compute1[(23)] = (compute1[(23)] + (pad_temp_shared[((((int)threadIdx.x) + 63))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 769))]));
    compute1[(3)] = (compute1[(3)] + (pad_temp_shared[((((int)threadIdx.x) + 70))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 1))]));
    compute1[(10)] = (compute1[(10)] + (pad_temp_shared[((((int)threadIdx.x) + 70))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 257))]));
    compute1[(17)] = (compute1[(17)] + (pad_temp_shared[((((int)threadIdx.x) + 70))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 513))]));
    compute1[(24)] = (compute1[(24)] + (pad_temp_shared[((((int)threadIdx.x) + 70))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 769))]));
    compute1[(4)] = (compute1[(4)] + (pad_temp_shared[((((int)threadIdx.x) + 77))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 1))]));
    compute1[(11)] = (compute1[(11)] + (pad_temp_shared[((((int)threadIdx.x) + 77))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 257))]));
    compute1[(18)] = (compute1[(18)] + (pad_temp_shared[((((int)threadIdx.x) + 77))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 513))]));
    compute1[(25)] = (compute1[(25)] + (pad_temp_shared[((((int)threadIdx.x) + 77))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 769))]));
    compute1[(5)] = (compute1[(5)] + (pad_temp_shared[((((int)threadIdx.x) + 84))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 1))]));
    compute1[(12)] = (compute1[(12)] + (pad_temp_shared[((((int)threadIdx.x) + 84))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 257))]));
    compute1[(19)] = (compute1[(19)] + (pad_temp_shared[((((int)threadIdx.x) + 84))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 513))]));
    compute1[(26)] = (compute1[(26)] + (pad_temp_shared[((((int)threadIdx.x) + 84))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 769))]));
    compute1[(6)] = (compute1[(6)] + (pad_temp_shared[((((int)threadIdx.x) + 91))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 1))]));
    compute1[(13)] = (compute1[(13)] + (pad_temp_shared[((((int)threadIdx.x) + 91))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 257))]));
    compute1[(20)] = (compute1[(20)] + (pad_temp_shared[((((int)threadIdx.x) + 91))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 513))]));
    compute1[(27)] = (compute1[(27)] + (pad_temp_shared[((((int)threadIdx.x) + 91))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 769))]));
    compute1[(0)] = (compute1[(0)] + (pad_temp_shared[((((int)threadIdx.x) + 98))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 2))]));
    compute1[(7)] = (compute1[(7)] + (pad_temp_shared[((((int)threadIdx.x) + 98))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 258))]));
    compute1[(14)] = (compute1[(14)] + (pad_temp_shared[((((int)threadIdx.x) + 98))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 514))]));
    compute1[(21)] = (compute1[(21)] + (pad_temp_shared[((((int)threadIdx.x) + 98))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 770))]));
    compute1[(1)] = (compute1[(1)] + (pad_temp_shared[((((int)threadIdx.x) + 105))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 2))]));
    compute1[(8)] = (compute1[(8)] + (pad_temp_shared[((((int)threadIdx.x) + 105))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 258))]));
    compute1[(15)] = (compute1[(15)] + (pad_temp_shared[((((int)threadIdx.x) + 105))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 514))]));
    compute1[(22)] = (compute1[(22)] + (pad_temp_shared[((((int)threadIdx.x) + 105))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 770))]));
    compute1[(2)] = (compute1[(2)] + (pad_temp_shared[((((int)threadIdx.x) + 112))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 2))]));
    compute1[(9)] = (compute1[(9)] + (pad_temp_shared[((((int)threadIdx.x) + 112))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 258))]));
    compute1[(16)] = (compute1[(16)] + (pad_temp_shared[((((int)threadIdx.x) + 112))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 514))]));
    compute1[(23)] = (compute1[(23)] + (pad_temp_shared[((((int)threadIdx.x) + 112))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 770))]));
    compute1[(3)] = (compute1[(3)] + (pad_temp_shared[((((int)threadIdx.x) + 119))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 2))]));
    compute1[(10)] = (compute1[(10)] + (pad_temp_shared[((((int)threadIdx.x) + 119))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 258))]));
    compute1[(17)] = (compute1[(17)] + (pad_temp_shared[((((int)threadIdx.x) + 119))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 514))]));
    compute1[(24)] = (compute1[(24)] + (pad_temp_shared[((((int)threadIdx.x) + 119))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 770))]));
    compute1[(4)] = (compute1[(4)] + (pad_temp_shared[((((int)threadIdx.x) + 126))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 2))]));
    compute1[(11)] = (compute1[(11)] + (pad_temp_shared[((((int)threadIdx.x) + 126))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 258))]));
    compute1[(18)] = (compute1[(18)] + (pad_temp_shared[((((int)threadIdx.x) + 126))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 514))]));
    compute1[(25)] = (compute1[(25)] + (pad_temp_shared[((((int)threadIdx.x) + 126))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 770))]));
    compute1[(5)] = (compute1[(5)] + (pad_temp_shared[((((int)threadIdx.x) + 133))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 2))]));
    compute1[(12)] = (compute1[(12)] + (pad_temp_shared[((((int)threadIdx.x) + 133))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 258))]));
    compute1[(19)] = (compute1[(19)] + (pad_temp_shared[((((int)threadIdx.x) + 133))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 514))]));
    compute1[(26)] = (compute1[(26)] + (pad_temp_shared[((((int)threadIdx.x) + 133))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 770))]));
    compute1[(6)] = (compute1[(6)] + (pad_temp_shared[((((int)threadIdx.x) + 140))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 2))]));
    compute1[(13)] = (compute1[(13)] + (pad_temp_shared[((((int)threadIdx.x) + 140))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 258))]));
    compute1[(20)] = (compute1[(20)] + (pad_temp_shared[((((int)threadIdx.x) + 140))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 514))]));
    compute1[(27)] = (compute1[(27)] + (pad_temp_shared[((((int)threadIdx.x) + 140))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 770))]));
    compute1[(0)] = (compute1[(0)] + (pad_temp_shared[((((int)threadIdx.x) + 147))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 3))]));
    compute1[(7)] = (compute1[(7)] + (pad_temp_shared[((((int)threadIdx.x) + 147))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 259))]));
    compute1[(14)] = (compute1[(14)] + (pad_temp_shared[((((int)threadIdx.x) + 147))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 515))]));
    compute1[(21)] = (compute1[(21)] + (pad_temp_shared[((((int)threadIdx.x) + 147))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 771))]));
    compute1[(1)] = (compute1[(1)] + (pad_temp_shared[((((int)threadIdx.x) + 154))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 3))]));
    compute1[(8)] = (compute1[(8)] + (pad_temp_shared[((((int)threadIdx.x) + 154))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 259))]));
    compute1[(15)] = (compute1[(15)] + (pad_temp_shared[((((int)threadIdx.x) + 154))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 515))]));
    compute1[(22)] = (compute1[(22)] + (pad_temp_shared[((((int)threadIdx.x) + 154))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 771))]));
    compute1[(2)] = (compute1[(2)] + (pad_temp_shared[((((int)threadIdx.x) + 161))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 3))]));
    compute1[(9)] = (compute1[(9)] + (pad_temp_shared[((((int)threadIdx.x) + 161))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 259))]));
    compute1[(16)] = (compute1[(16)] + (pad_temp_shared[((((int)threadIdx.x) + 161))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 515))]));
    compute1[(23)] = (compute1[(23)] + (pad_temp_shared[((((int)threadIdx.x) + 161))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 771))]));
    compute1[(3)] = (compute1[(3)] + (pad_temp_shared[((((int)threadIdx.x) + 168))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 3))]));
    compute1[(10)] = (compute1[(10)] + (pad_temp_shared[((((int)threadIdx.x) + 168))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 259))]));
    compute1[(17)] = (compute1[(17)] + (pad_temp_shared[((((int)threadIdx.x) + 168))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 515))]));
    compute1[(24)] = (compute1[(24)] + (pad_temp_shared[((((int)threadIdx.x) + 168))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 771))]));
    compute1[(4)] = (compute1[(4)] + (pad_temp_shared[((((int)threadIdx.x) + 175))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 3))]));
    compute1[(11)] = (compute1[(11)] + (pad_temp_shared[((((int)threadIdx.x) + 175))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 259))]));
    compute1[(18)] = (compute1[(18)] + (pad_temp_shared[((((int)threadIdx.x) + 175))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 515))]));
    compute1[(25)] = (compute1[(25)] + (pad_temp_shared[((((int)threadIdx.x) + 175))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 771))]));
    compute1[(5)] = (compute1[(5)] + (pad_temp_shared[((((int)threadIdx.x) + 182))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 3))]));
    compute1[(12)] = (compute1[(12)] + (pad_temp_shared[((((int)threadIdx.x) + 182))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 259))]));
    compute1[(19)] = (compute1[(19)] + (pad_temp_shared[((((int)threadIdx.x) + 182))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 515))]));
    compute1[(26)] = (compute1[(26)] + (pad_temp_shared[((((int)threadIdx.x) + 182))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 771))]));
    compute1[(6)] = (compute1[(6)] + (pad_temp_shared[((((int)threadIdx.x) + 189))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 3))]));
    compute1[(13)] = (compute1[(13)] + (pad_temp_shared[((((int)threadIdx.x) + 189))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 259))]));
    compute1[(20)] = (compute1[(20)] + (pad_temp_shared[((((int)threadIdx.x) + 189))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 515))]));
    compute1[(27)] = (compute1[(27)] + (pad_temp_shared[((((int)threadIdx.x) + 189))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 771))]));
    compute1[(0)] = (compute1[(0)] + (pad_temp_shared[((((int)threadIdx.x) + 196))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 4))]));
    compute1[(7)] = (compute1[(7)] + (pad_temp_shared[((((int)threadIdx.x) + 196))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 260))]));
    compute1[(14)] = (compute1[(14)] + (pad_temp_shared[((((int)threadIdx.x) + 196))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 516))]));
    compute1[(21)] = (compute1[(21)] + (pad_temp_shared[((((int)threadIdx.x) + 196))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 772))]));
    compute1[(1)] = (compute1[(1)] + (pad_temp_shared[((((int)threadIdx.x) + 203))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 4))]));
    compute1[(8)] = (compute1[(8)] + (pad_temp_shared[((((int)threadIdx.x) + 203))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 260))]));
    compute1[(15)] = (compute1[(15)] + (pad_temp_shared[((((int)threadIdx.x) + 203))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 516))]));
    compute1[(22)] = (compute1[(22)] + (pad_temp_shared[((((int)threadIdx.x) + 203))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 772))]));
    compute1[(2)] = (compute1[(2)] + (pad_temp_shared[((((int)threadIdx.x) + 210))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 4))]));
    compute1[(9)] = (compute1[(9)] + (pad_temp_shared[((((int)threadIdx.x) + 210))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 260))]));
    compute1[(16)] = (compute1[(16)] + (pad_temp_shared[((((int)threadIdx.x) + 210))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 516))]));
    compute1[(23)] = (compute1[(23)] + (pad_temp_shared[((((int)threadIdx.x) + 210))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 772))]));
    compute1[(3)] = (compute1[(3)] + (pad_temp_shared[((((int)threadIdx.x) + 217))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 4))]));
    compute1[(10)] = (compute1[(10)] + (pad_temp_shared[((((int)threadIdx.x) + 217))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 260))]));
    compute1[(17)] = (compute1[(17)] + (pad_temp_shared[((((int)threadIdx.x) + 217))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 516))]));
    compute1[(24)] = (compute1[(24)] + (pad_temp_shared[((((int)threadIdx.x) + 217))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 772))]));
    compute1[(4)] = (compute1[(4)] + (pad_temp_shared[((((int)threadIdx.x) + 224))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 4))]));
    compute1[(11)] = (compute1[(11)] + (pad_temp_shared[((((int)threadIdx.x) + 224))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 260))]));
    compute1[(18)] = (compute1[(18)] + (pad_temp_shared[((((int)threadIdx.x) + 224))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 516))]));
    compute1[(25)] = (compute1[(25)] + (pad_temp_shared[((((int)threadIdx.x) + 224))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 772))]));
    compute1[(5)] = (compute1[(5)] + (pad_temp_shared[((((int)threadIdx.x) + 231))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 4))]));
    compute1[(12)] = (compute1[(12)] + (pad_temp_shared[((((int)threadIdx.x) + 231))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 260))]));
    compute1[(19)] = (compute1[(19)] + (pad_temp_shared[((((int)threadIdx.x) + 231))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 516))]));
    compute1[(26)] = (compute1[(26)] + (pad_temp_shared[((((int)threadIdx.x) + 231))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 772))]));
    compute1[(6)] = (compute1[(6)] + (pad_temp_shared[((((int)threadIdx.x) + 238))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 4))]));
    compute1[(13)] = (compute1[(13)] + (pad_temp_shared[((((int)threadIdx.x) + 238))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 260))]));
    compute1[(20)] = (compute1[(20)] + (pad_temp_shared[((((int)threadIdx.x) + 238))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 516))]));
    compute1[(27)] = (compute1[(27)] + (pad_temp_shared[((((int)threadIdx.x) + 238))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 772))]));
    compute1[(0)] = (compute1[(0)] + (pad_temp_shared[((((int)threadIdx.x) + 245))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 5))]));
    compute1[(7)] = (compute1[(7)] + (pad_temp_shared[((((int)threadIdx.x) + 245))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 261))]));
    compute1[(14)] = (compute1[(14)] + (pad_temp_shared[((((int)threadIdx.x) + 245))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 517))]));
    compute1[(21)] = (compute1[(21)] + (pad_temp_shared[((((int)threadIdx.x) + 245))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 773))]));
    compute1[(1)] = (compute1[(1)] + (pad_temp_shared[((((int)threadIdx.x) + 252))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 5))]));
    compute1[(8)] = (compute1[(8)] + (pad_temp_shared[((((int)threadIdx.x) + 252))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 261))]));
    compute1[(15)] = (compute1[(15)] + (pad_temp_shared[((((int)threadIdx.x) + 252))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 517))]));
    compute1[(22)] = (compute1[(22)] + (pad_temp_shared[((((int)threadIdx.x) + 252))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 773))]));
    compute1[(2)] = (compute1[(2)] + (pad_temp_shared[((((int)threadIdx.x) + 259))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 5))]));
    compute1[(9)] = (compute1[(9)] + (pad_temp_shared[((((int)threadIdx.x) + 259))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 261))]));
    compute1[(16)] = (compute1[(16)] + (pad_temp_shared[((((int)threadIdx.x) + 259))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 517))]));
    compute1[(23)] = (compute1[(23)] + (pad_temp_shared[((((int)threadIdx.x) + 259))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 773))]));
    compute1[(3)] = (compute1[(3)] + (pad_temp_shared[((((int)threadIdx.x) + 266))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 5))]));
    compute1[(10)] = (compute1[(10)] + (pad_temp_shared[((((int)threadIdx.x) + 266))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 261))]));
    compute1[(17)] = (compute1[(17)] + (pad_temp_shared[((((int)threadIdx.x) + 266))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 517))]));
    compute1[(24)] = (compute1[(24)] + (pad_temp_shared[((((int)threadIdx.x) + 266))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 773))]));
    compute1[(4)] = (compute1[(4)] + (pad_temp_shared[((((int)threadIdx.x) + 273))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 5))]));
    compute1[(11)] = (compute1[(11)] + (pad_temp_shared[((((int)threadIdx.x) + 273))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 261))]));
    compute1[(18)] = (compute1[(18)] + (pad_temp_shared[((((int)threadIdx.x) + 273))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 517))]));
    compute1[(25)] = (compute1[(25)] + (pad_temp_shared[((((int)threadIdx.x) + 273))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 773))]));
    compute1[(5)] = (compute1[(5)] + (pad_temp_shared[((((int)threadIdx.x) + 280))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 5))]));
    compute1[(12)] = (compute1[(12)] + (pad_temp_shared[((((int)threadIdx.x) + 280))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 261))]));
    compute1[(19)] = (compute1[(19)] + (pad_temp_shared[((((int)threadIdx.x) + 280))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 517))]));
    compute1[(26)] = (compute1[(26)] + (pad_temp_shared[((((int)threadIdx.x) + 280))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 773))]));
    compute1[(6)] = (compute1[(6)] + (pad_temp_shared[((((int)threadIdx.x) + 287))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 5))]));
    compute1[(13)] = (compute1[(13)] + (pad_temp_shared[((((int)threadIdx.x) + 287))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 261))]));
    compute1[(20)] = (compute1[(20)] + (pad_temp_shared[((((int)threadIdx.x) + 287))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 517))]));
    compute1[(27)] = (compute1[(27)] + (pad_temp_shared[((((int)threadIdx.x) + 287))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 773))]));
    compute1[(0)] = (compute1[(0)] + (pad_temp_shared[((((int)threadIdx.x) + 294))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 6))]));
    compute1[(7)] = (compute1[(7)] + (pad_temp_shared[((((int)threadIdx.x) + 294))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 262))]));
    compute1[(14)] = (compute1[(14)] + (pad_temp_shared[((((int)threadIdx.x) + 294))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 518))]));
    compute1[(21)] = (compute1[(21)] + (pad_temp_shared[((((int)threadIdx.x) + 294))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 774))]));
    compute1[(1)] = (compute1[(1)] + (pad_temp_shared[((((int)threadIdx.x) + 301))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 6))]));
    compute1[(8)] = (compute1[(8)] + (pad_temp_shared[((((int)threadIdx.x) + 301))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 262))]));
    compute1[(15)] = (compute1[(15)] + (pad_temp_shared[((((int)threadIdx.x) + 301))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 518))]));
    compute1[(22)] = (compute1[(22)] + (pad_temp_shared[((((int)threadIdx.x) + 301))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 774))]));
    compute1[(2)] = (compute1[(2)] + (pad_temp_shared[((((int)threadIdx.x) + 308))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 6))]));
    compute1[(9)] = (compute1[(9)] + (pad_temp_shared[((((int)threadIdx.x) + 308))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 262))]));
    compute1[(16)] = (compute1[(16)] + (pad_temp_shared[((((int)threadIdx.x) + 308))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 518))]));
    compute1[(23)] = (compute1[(23)] + (pad_temp_shared[((((int)threadIdx.x) + 308))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 774))]));
    compute1[(3)] = (compute1[(3)] + (pad_temp_shared[((((int)threadIdx.x) + 315))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 6))]));
    compute1[(10)] = (compute1[(10)] + (pad_temp_shared[((((int)threadIdx.x) + 315))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 262))]));
    compute1[(17)] = (compute1[(17)] + (pad_temp_shared[((((int)threadIdx.x) + 315))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 518))]));
    compute1[(24)] = (compute1[(24)] + (pad_temp_shared[((((int)threadIdx.x) + 315))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 774))]));
    compute1[(4)] = (compute1[(4)] + (pad_temp_shared[((((int)threadIdx.x) + 322))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 6))]));
    compute1[(11)] = (compute1[(11)] + (pad_temp_shared[((((int)threadIdx.x) + 322))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 262))]));
    compute1[(18)] = (compute1[(18)] + (pad_temp_shared[((((int)threadIdx.x) + 322))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 518))]));
    compute1[(25)] = (compute1[(25)] + (pad_temp_shared[((((int)threadIdx.x) + 322))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 774))]));
    compute1[(5)] = (compute1[(5)] + (pad_temp_shared[((((int)threadIdx.x) + 329))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 6))]));
    compute1[(12)] = (compute1[(12)] + (pad_temp_shared[((((int)threadIdx.x) + 329))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 262))]));
    compute1[(19)] = (compute1[(19)] + (pad_temp_shared[((((int)threadIdx.x) + 329))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 518))]));
    compute1[(26)] = (compute1[(26)] + (pad_temp_shared[((((int)threadIdx.x) + 329))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 774))]));
    compute1[(6)] = (compute1[(6)] + (pad_temp_shared[((((int)threadIdx.x) + 336))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 6))]));
    compute1[(13)] = (compute1[(13)] + (pad_temp_shared[((((int)threadIdx.x) + 336))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 262))]));
    compute1[(20)] = (compute1[(20)] + (pad_temp_shared[((((int)threadIdx.x) + 336))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 518))]));
    compute1[(27)] = (compute1[(27)] + (pad_temp_shared[((((int)threadIdx.x) + 336))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 774))]));
    compute1[(0)] = (compute1[(0)] + (pad_temp_shared[((((int)threadIdx.x) + 343))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 7))]));
    compute1[(7)] = (compute1[(7)] + (pad_temp_shared[((((int)threadIdx.x) + 343))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 263))]));
    compute1[(14)] = (compute1[(14)] + (pad_temp_shared[((((int)threadIdx.x) + 343))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 519))]));
    compute1[(21)] = (compute1[(21)] + (pad_temp_shared[((((int)threadIdx.x) + 343))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 775))]));
    compute1[(1)] = (compute1[(1)] + (pad_temp_shared[((((int)threadIdx.x) + 350))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 7))]));
    compute1[(8)] = (compute1[(8)] + (pad_temp_shared[((((int)threadIdx.x) + 350))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 263))]));
    compute1[(15)] = (compute1[(15)] + (pad_temp_shared[((((int)threadIdx.x) + 350))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 519))]));
    compute1[(22)] = (compute1[(22)] + (pad_temp_shared[((((int)threadIdx.x) + 350))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 775))]));
    compute1[(2)] = (compute1[(2)] + (pad_temp_shared[((((int)threadIdx.x) + 357))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 7))]));
    compute1[(9)] = (compute1[(9)] + (pad_temp_shared[((((int)threadIdx.x) + 357))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 263))]));
    compute1[(16)] = (compute1[(16)] + (pad_temp_shared[((((int)threadIdx.x) + 357))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 519))]));
    compute1[(23)] = (compute1[(23)] + (pad_temp_shared[((((int)threadIdx.x) + 357))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 775))]));
    compute1[(3)] = (compute1[(3)] + (pad_temp_shared[((((int)threadIdx.x) + 364))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 7))]));
    compute1[(10)] = (compute1[(10)] + (pad_temp_shared[((((int)threadIdx.x) + 364))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 263))]));
    compute1[(17)] = (compute1[(17)] + (pad_temp_shared[((((int)threadIdx.x) + 364))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 519))]));
    compute1[(24)] = (compute1[(24)] + (pad_temp_shared[((((int)threadIdx.x) + 364))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 775))]));
    compute1[(4)] = (compute1[(4)] + (pad_temp_shared[((((int)threadIdx.x) + 371))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 7))]));
    compute1[(11)] = (compute1[(11)] + (pad_temp_shared[((((int)threadIdx.x) + 371))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 263))]));
    compute1[(18)] = (compute1[(18)] + (pad_temp_shared[((((int)threadIdx.x) + 371))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 519))]));
    compute1[(25)] = (compute1[(25)] + (pad_temp_shared[((((int)threadIdx.x) + 371))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 775))]));
    compute1[(5)] = (compute1[(5)] + (pad_temp_shared[((((int)threadIdx.x) + 378))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 7))]));
    compute1[(12)] = (compute1[(12)] + (pad_temp_shared[((((int)threadIdx.x) + 378))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 263))]));
    compute1[(19)] = (compute1[(19)] + (pad_temp_shared[((((int)threadIdx.x) + 378))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 519))]));
    compute1[(26)] = (compute1[(26)] + (pad_temp_shared[((((int)threadIdx.x) + 378))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 775))]));
    compute1[(6)] = (compute1[(6)] + (pad_temp_shared[((((int)threadIdx.x) + 385))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 7))]));
    compute1[(13)] = (compute1[(13)] + (pad_temp_shared[((((int)threadIdx.x) + 385))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 263))]));
    compute1[(20)] = (compute1[(20)] + (pad_temp_shared[((((int)threadIdx.x) + 385))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 519))]));
    compute1[(27)] = (compute1[(27)] + (pad_temp_shared[((((int)threadIdx.x) + 385))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 775))]));
    compute1[(0)] = (compute1[(0)] + (pad_temp_shared[((((int)threadIdx.x) + 392))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 8))]));
    compute1[(7)] = (compute1[(7)] + (pad_temp_shared[((((int)threadIdx.x) + 392))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 264))]));
    compute1[(14)] = (compute1[(14)] + (pad_temp_shared[((((int)threadIdx.x) + 392))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 520))]));
    compute1[(21)] = (compute1[(21)] + (pad_temp_shared[((((int)threadIdx.x) + 392))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 776))]));
    compute1[(1)] = (compute1[(1)] + (pad_temp_shared[((((int)threadIdx.x) + 399))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 8))]));
    compute1[(8)] = (compute1[(8)] + (pad_temp_shared[((((int)threadIdx.x) + 399))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 264))]));
    compute1[(15)] = (compute1[(15)] + (pad_temp_shared[((((int)threadIdx.x) + 399))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 520))]));
    compute1[(22)] = (compute1[(22)] + (pad_temp_shared[((((int)threadIdx.x) + 399))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 776))]));
    compute1[(2)] = (compute1[(2)] + (pad_temp_shared[((((int)threadIdx.x) + 406))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 8))]));
    compute1[(9)] = (compute1[(9)] + (pad_temp_shared[((((int)threadIdx.x) + 406))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 264))]));
    compute1[(16)] = (compute1[(16)] + (pad_temp_shared[((((int)threadIdx.x) + 406))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 520))]));
    compute1[(23)] = (compute1[(23)] + (pad_temp_shared[((((int)threadIdx.x) + 406))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 776))]));
    compute1[(3)] = (compute1[(3)] + (pad_temp_shared[((((int)threadIdx.x) + 413))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 8))]));
    compute1[(10)] = (compute1[(10)] + (pad_temp_shared[((((int)threadIdx.x) + 413))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 264))]));
    compute1[(17)] = (compute1[(17)] + (pad_temp_shared[((((int)threadIdx.x) + 413))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 520))]));
    compute1[(24)] = (compute1[(24)] + (pad_temp_shared[((((int)threadIdx.x) + 413))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 776))]));
    compute1[(4)] = (compute1[(4)] + (pad_temp_shared[((((int)threadIdx.x) + 420))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 8))]));
    compute1[(11)] = (compute1[(11)] + (pad_temp_shared[((((int)threadIdx.x) + 420))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 264))]));
    compute1[(18)] = (compute1[(18)] + (pad_temp_shared[((((int)threadIdx.x) + 420))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 520))]));
    compute1[(25)] = (compute1[(25)] + (pad_temp_shared[((((int)threadIdx.x) + 420))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 776))]));
    compute1[(5)] = (compute1[(5)] + (pad_temp_shared[((((int)threadIdx.x) + 427))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 8))]));
    compute1[(12)] = (compute1[(12)] + (pad_temp_shared[((((int)threadIdx.x) + 427))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 264))]));
    compute1[(19)] = (compute1[(19)] + (pad_temp_shared[((((int)threadIdx.x) + 427))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 520))]));
    compute1[(26)] = (compute1[(26)] + (pad_temp_shared[((((int)threadIdx.x) + 427))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 776))]));
    compute1[(6)] = (compute1[(6)] + (pad_temp_shared[((((int)threadIdx.x) + 434))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 8))]));
    compute1[(13)] = (compute1[(13)] + (pad_temp_shared[((((int)threadIdx.x) + 434))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 264))]));
    compute1[(20)] = (compute1[(20)] + (pad_temp_shared[((((int)threadIdx.x) + 434))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 520))]));
    compute1[(27)] = (compute1[(27)] + (pad_temp_shared[((((int)threadIdx.x) + 434))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 776))]));
    compute1[(0)] = (compute1[(0)] + (pad_temp_shared[((((int)threadIdx.x) + 441))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 9))]));
    compute1[(7)] = (compute1[(7)] + (pad_temp_shared[((((int)threadIdx.x) + 441))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 265))]));
    compute1[(14)] = (compute1[(14)] + (pad_temp_shared[((((int)threadIdx.x) + 441))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 521))]));
    compute1[(21)] = (compute1[(21)] + (pad_temp_shared[((((int)threadIdx.x) + 441))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 777))]));
    compute1[(1)] = (compute1[(1)] + (pad_temp_shared[((((int)threadIdx.x) + 448))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 9))]));
    compute1[(8)] = (compute1[(8)] + (pad_temp_shared[((((int)threadIdx.x) + 448))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 265))]));
    compute1[(15)] = (compute1[(15)] + (pad_temp_shared[((((int)threadIdx.x) + 448))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 521))]));
    compute1[(22)] = (compute1[(22)] + (pad_temp_shared[((((int)threadIdx.x) + 448))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 777))]));
    compute1[(2)] = (compute1[(2)] + (pad_temp_shared[((((int)threadIdx.x) + 455))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 9))]));
    compute1[(9)] = (compute1[(9)] + (pad_temp_shared[((((int)threadIdx.x) + 455))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 265))]));
    compute1[(16)] = (compute1[(16)] + (pad_temp_shared[((((int)threadIdx.x) + 455))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 521))]));
    compute1[(23)] = (compute1[(23)] + (pad_temp_shared[((((int)threadIdx.x) + 455))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 777))]));
    compute1[(3)] = (compute1[(3)] + (pad_temp_shared[((((int)threadIdx.x) + 462))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 9))]));
    compute1[(10)] = (compute1[(10)] + (pad_temp_shared[((((int)threadIdx.x) + 462))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 265))]));
    compute1[(17)] = (compute1[(17)] + (pad_temp_shared[((((int)threadIdx.x) + 462))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 521))]));
    compute1[(24)] = (compute1[(24)] + (pad_temp_shared[((((int)threadIdx.x) + 462))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 777))]));
    compute1[(4)] = (compute1[(4)] + (pad_temp_shared[((((int)threadIdx.x) + 469))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 9))]));
    compute1[(11)] = (compute1[(11)] + (pad_temp_shared[((((int)threadIdx.x) + 469))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 265))]));
    compute1[(18)] = (compute1[(18)] + (pad_temp_shared[((((int)threadIdx.x) + 469))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 521))]));
    compute1[(25)] = (compute1[(25)] + (pad_temp_shared[((((int)threadIdx.x) + 469))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 777))]));
    compute1[(5)] = (compute1[(5)] + (pad_temp_shared[((((int)threadIdx.x) + 476))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 9))]));
    compute1[(12)] = (compute1[(12)] + (pad_temp_shared[((((int)threadIdx.x) + 476))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 265))]));
    compute1[(19)] = (compute1[(19)] + (pad_temp_shared[((((int)threadIdx.x) + 476))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 521))]));
    compute1[(26)] = (compute1[(26)] + (pad_temp_shared[((((int)threadIdx.x) + 476))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 777))]));
    compute1[(6)] = (compute1[(6)] + (pad_temp_shared[((((int)threadIdx.x) + 483))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 9))]));
    compute1[(13)] = (compute1[(13)] + (pad_temp_shared[((((int)threadIdx.x) + 483))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 265))]));
    compute1[(20)] = (compute1[(20)] + (pad_temp_shared[((((int)threadIdx.x) + 483))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 521))]));
    compute1[(27)] = (compute1[(27)] + (pad_temp_shared[((((int)threadIdx.x) + 483))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 777))]));
    compute1[(0)] = (compute1[(0)] + (pad_temp_shared[((((int)threadIdx.x) + 490))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 10))]));
    compute1[(7)] = (compute1[(7)] + (pad_temp_shared[((((int)threadIdx.x) + 490))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 266))]));
    compute1[(14)] = (compute1[(14)] + (pad_temp_shared[((((int)threadIdx.x) + 490))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 522))]));
    compute1[(21)] = (compute1[(21)] + (pad_temp_shared[((((int)threadIdx.x) + 490))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 778))]));
    compute1[(1)] = (compute1[(1)] + (pad_temp_shared[((((int)threadIdx.x) + 497))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 10))]));
    compute1[(8)] = (compute1[(8)] + (pad_temp_shared[((((int)threadIdx.x) + 497))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 266))]));
    compute1[(15)] = (compute1[(15)] + (pad_temp_shared[((((int)threadIdx.x) + 497))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 522))]));
    compute1[(22)] = (compute1[(22)] + (pad_temp_shared[((((int)threadIdx.x) + 497))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 778))]));
    compute1[(2)] = (compute1[(2)] + (pad_temp_shared[((((int)threadIdx.x) + 504))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 10))]));
    compute1[(9)] = (compute1[(9)] + (pad_temp_shared[((((int)threadIdx.x) + 504))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 266))]));
    compute1[(16)] = (compute1[(16)] + (pad_temp_shared[((((int)threadIdx.x) + 504))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 522))]));
    compute1[(23)] = (compute1[(23)] + (pad_temp_shared[((((int)threadIdx.x) + 504))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 778))]));
    compute1[(3)] = (compute1[(3)] + (pad_temp_shared[((((int)threadIdx.x) + 511))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 10))]));
    compute1[(10)] = (compute1[(10)] + (pad_temp_shared[((((int)threadIdx.x) + 511))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 266))]));
    compute1[(17)] = (compute1[(17)] + (pad_temp_shared[((((int)threadIdx.x) + 511))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 522))]));
    compute1[(24)] = (compute1[(24)] + (pad_temp_shared[((((int)threadIdx.x) + 511))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 778))]));
    compute1[(4)] = (compute1[(4)] + (pad_temp_shared[((((int)threadIdx.x) + 518))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 10))]));
    compute1[(11)] = (compute1[(11)] + (pad_temp_shared[((((int)threadIdx.x) + 518))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 266))]));
    compute1[(18)] = (compute1[(18)] + (pad_temp_shared[((((int)threadIdx.x) + 518))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 522))]));
    compute1[(25)] = (compute1[(25)] + (pad_temp_shared[((((int)threadIdx.x) + 518))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 778))]));
    compute1[(5)] = (compute1[(5)] + (pad_temp_shared[((((int)threadIdx.x) + 525))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 10))]));
    compute1[(12)] = (compute1[(12)] + (pad_temp_shared[((((int)threadIdx.x) + 525))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 266))]));
    compute1[(19)] = (compute1[(19)] + (pad_temp_shared[((((int)threadIdx.x) + 525))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 522))]));
    compute1[(26)] = (compute1[(26)] + (pad_temp_shared[((((int)threadIdx.x) + 525))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 778))]));
    compute1[(6)] = (compute1[(6)] + (pad_temp_shared[((((int)threadIdx.x) + 532))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 10))]));
    compute1[(13)] = (compute1[(13)] + (pad_temp_shared[((((int)threadIdx.x) + 532))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 266))]));
    compute1[(20)] = (compute1[(20)] + (pad_temp_shared[((((int)threadIdx.x) + 532))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 522))]));
    compute1[(27)] = (compute1[(27)] + (pad_temp_shared[((((int)threadIdx.x) + 532))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 778))]));
    compute1[(0)] = (compute1[(0)] + (pad_temp_shared[((((int)threadIdx.x) + 539))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 11))]));
    compute1[(7)] = (compute1[(7)] + (pad_temp_shared[((((int)threadIdx.x) + 539))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 267))]));
    compute1[(14)] = (compute1[(14)] + (pad_temp_shared[((((int)threadIdx.x) + 539))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 523))]));
    compute1[(21)] = (compute1[(21)] + (pad_temp_shared[((((int)threadIdx.x) + 539))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 779))]));
    compute1[(1)] = (compute1[(1)] + (pad_temp_shared[((((int)threadIdx.x) + 546))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 11))]));
    compute1[(8)] = (compute1[(8)] + (pad_temp_shared[((((int)threadIdx.x) + 546))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 267))]));
    compute1[(15)] = (compute1[(15)] + (pad_temp_shared[((((int)threadIdx.x) + 546))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 523))]));
    compute1[(22)] = (compute1[(22)] + (pad_temp_shared[((((int)threadIdx.x) + 546))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 779))]));
    compute1[(2)] = (compute1[(2)] + (pad_temp_shared[((((int)threadIdx.x) + 553))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 11))]));
    compute1[(9)] = (compute1[(9)] + (pad_temp_shared[((((int)threadIdx.x) + 553))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 267))]));
    compute1[(16)] = (compute1[(16)] + (pad_temp_shared[((((int)threadIdx.x) + 553))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 523))]));
    compute1[(23)] = (compute1[(23)] + (pad_temp_shared[((((int)threadIdx.x) + 553))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 779))]));
    compute1[(3)] = (compute1[(3)] + (pad_temp_shared[((((int)threadIdx.x) + 560))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 11))]));
    compute1[(10)] = (compute1[(10)] + (pad_temp_shared[((((int)threadIdx.x) + 560))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 267))]));
    compute1[(17)] = (compute1[(17)] + (pad_temp_shared[((((int)threadIdx.x) + 560))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 523))]));
    compute1[(24)] = (compute1[(24)] + (pad_temp_shared[((((int)threadIdx.x) + 560))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 779))]));
    compute1[(4)] = (compute1[(4)] + (pad_temp_shared[((((int)threadIdx.x) + 567))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 11))]));
    compute1[(11)] = (compute1[(11)] + (pad_temp_shared[((((int)threadIdx.x) + 567))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 267))]));
    compute1[(18)] = (compute1[(18)] + (pad_temp_shared[((((int)threadIdx.x) + 567))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 523))]));
    compute1[(25)] = (compute1[(25)] + (pad_temp_shared[((((int)threadIdx.x) + 567))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 779))]));
    compute1[(5)] = (compute1[(5)] + (pad_temp_shared[((((int)threadIdx.x) + 574))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 11))]));
    compute1[(12)] = (compute1[(12)] + (pad_temp_shared[((((int)threadIdx.x) + 574))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 267))]));
    compute1[(19)] = (compute1[(19)] + (pad_temp_shared[((((int)threadIdx.x) + 574))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 523))]));
    compute1[(26)] = (compute1[(26)] + (pad_temp_shared[((((int)threadIdx.x) + 574))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 779))]));
    compute1[(6)] = (compute1[(6)] + (pad_temp_shared[((((int)threadIdx.x) + 581))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 11))]));
    compute1[(13)] = (compute1[(13)] + (pad_temp_shared[((((int)threadIdx.x) + 581))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 267))]));
    compute1[(20)] = (compute1[(20)] + (pad_temp_shared[((((int)threadIdx.x) + 581))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 523))]));
    compute1[(27)] = (compute1[(27)] + (pad_temp_shared[((((int)threadIdx.x) + 581))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 779))]));
    compute1[(0)] = (compute1[(0)] + (pad_temp_shared[((((int)threadIdx.x) + 588))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 12))]));
    compute1[(7)] = (compute1[(7)] + (pad_temp_shared[((((int)threadIdx.x) + 588))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 268))]));
    compute1[(14)] = (compute1[(14)] + (pad_temp_shared[((((int)threadIdx.x) + 588))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 524))]));
    compute1[(21)] = (compute1[(21)] + (pad_temp_shared[((((int)threadIdx.x) + 588))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 780))]));
    compute1[(1)] = (compute1[(1)] + (pad_temp_shared[((((int)threadIdx.x) + 595))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 12))]));
    compute1[(8)] = (compute1[(8)] + (pad_temp_shared[((((int)threadIdx.x) + 595))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 268))]));
    compute1[(15)] = (compute1[(15)] + (pad_temp_shared[((((int)threadIdx.x) + 595))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 524))]));
    compute1[(22)] = (compute1[(22)] + (pad_temp_shared[((((int)threadIdx.x) + 595))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 780))]));
    compute1[(2)] = (compute1[(2)] + (pad_temp_shared[((((int)threadIdx.x) + 602))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 12))]));
    compute1[(9)] = (compute1[(9)] + (pad_temp_shared[((((int)threadIdx.x) + 602))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 268))]));
    compute1[(16)] = (compute1[(16)] + (pad_temp_shared[((((int)threadIdx.x) + 602))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 524))]));
    compute1[(23)] = (compute1[(23)] + (pad_temp_shared[((((int)threadIdx.x) + 602))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 780))]));
    compute1[(3)] = (compute1[(3)] + (pad_temp_shared[((((int)threadIdx.x) + 609))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 12))]));
    compute1[(10)] = (compute1[(10)] + (pad_temp_shared[((((int)threadIdx.x) + 609))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 268))]));
    compute1[(17)] = (compute1[(17)] + (pad_temp_shared[((((int)threadIdx.x) + 609))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 524))]));
    compute1[(24)] = (compute1[(24)] + (pad_temp_shared[((((int)threadIdx.x) + 609))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 780))]));
    compute1[(4)] = (compute1[(4)] + (pad_temp_shared[((((int)threadIdx.x) + 616))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 12))]));
    compute1[(11)] = (compute1[(11)] + (pad_temp_shared[((((int)threadIdx.x) + 616))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 268))]));
    compute1[(18)] = (compute1[(18)] + (pad_temp_shared[((((int)threadIdx.x) + 616))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 524))]));
    compute1[(25)] = (compute1[(25)] + (pad_temp_shared[((((int)threadIdx.x) + 616))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 780))]));
    compute1[(5)] = (compute1[(5)] + (pad_temp_shared[((((int)threadIdx.x) + 623))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 12))]));
    compute1[(12)] = (compute1[(12)] + (pad_temp_shared[((((int)threadIdx.x) + 623))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 268))]));
    compute1[(19)] = (compute1[(19)] + (pad_temp_shared[((((int)threadIdx.x) + 623))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 524))]));
    compute1[(26)] = (compute1[(26)] + (pad_temp_shared[((((int)threadIdx.x) + 623))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 780))]));
    compute1[(6)] = (compute1[(6)] + (pad_temp_shared[((((int)threadIdx.x) + 630))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 12))]));
    compute1[(13)] = (compute1[(13)] + (pad_temp_shared[((((int)threadIdx.x) + 630))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 268))]));
    compute1[(20)] = (compute1[(20)] + (pad_temp_shared[((((int)threadIdx.x) + 630))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 524))]));
    compute1[(27)] = (compute1[(27)] + (pad_temp_shared[((((int)threadIdx.x) + 630))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 780))]));
    compute1[(0)] = (compute1[(0)] + (pad_temp_shared[((((int)threadIdx.x) + 637))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 13))]));
    compute1[(7)] = (compute1[(7)] + (pad_temp_shared[((((int)threadIdx.x) + 637))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 269))]));
    compute1[(14)] = (compute1[(14)] + (pad_temp_shared[((((int)threadIdx.x) + 637))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 525))]));
    compute1[(21)] = (compute1[(21)] + (pad_temp_shared[((((int)threadIdx.x) + 637))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 781))]));
    compute1[(1)] = (compute1[(1)] + (pad_temp_shared[((((int)threadIdx.x) + 644))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 13))]));
    compute1[(8)] = (compute1[(8)] + (pad_temp_shared[((((int)threadIdx.x) + 644))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 269))]));
    compute1[(15)] = (compute1[(15)] + (pad_temp_shared[((((int)threadIdx.x) + 644))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 525))]));
    compute1[(22)] = (compute1[(22)] + (pad_temp_shared[((((int)threadIdx.x) + 644))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 781))]));
    compute1[(2)] = (compute1[(2)] + (pad_temp_shared[((((int)threadIdx.x) + 651))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 13))]));
    compute1[(9)] = (compute1[(9)] + (pad_temp_shared[((((int)threadIdx.x) + 651))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 269))]));
    compute1[(16)] = (compute1[(16)] + (pad_temp_shared[((((int)threadIdx.x) + 651))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 525))]));
    compute1[(23)] = (compute1[(23)] + (pad_temp_shared[((((int)threadIdx.x) + 651))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 781))]));
    compute1[(3)] = (compute1[(3)] + (pad_temp_shared[((((int)threadIdx.x) + 658))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 13))]));
    compute1[(10)] = (compute1[(10)] + (pad_temp_shared[((((int)threadIdx.x) + 658))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 269))]));
    compute1[(17)] = (compute1[(17)] + (pad_temp_shared[((((int)threadIdx.x) + 658))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 525))]));
    compute1[(24)] = (compute1[(24)] + (pad_temp_shared[((((int)threadIdx.x) + 658))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 781))]));
    compute1[(4)] = (compute1[(4)] + (pad_temp_shared[((((int)threadIdx.x) + 665))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 13))]));
    compute1[(11)] = (compute1[(11)] + (pad_temp_shared[((((int)threadIdx.x) + 665))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 269))]));
    compute1[(18)] = (compute1[(18)] + (pad_temp_shared[((((int)threadIdx.x) + 665))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 525))]));
    compute1[(25)] = (compute1[(25)] + (pad_temp_shared[((((int)threadIdx.x) + 665))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 781))]));
    compute1[(5)] = (compute1[(5)] + (pad_temp_shared[((((int)threadIdx.x) + 672))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 13))]));
    compute1[(12)] = (compute1[(12)] + (pad_temp_shared[((((int)threadIdx.x) + 672))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 269))]));
    compute1[(19)] = (compute1[(19)] + (pad_temp_shared[((((int)threadIdx.x) + 672))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 525))]));
    compute1[(26)] = (compute1[(26)] + (pad_temp_shared[((((int)threadIdx.x) + 672))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 781))]));
    compute1[(6)] = (compute1[(6)] + (pad_temp_shared[((((int)threadIdx.x) + 679))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 13))]));
    compute1[(13)] = (compute1[(13)] + (pad_temp_shared[((((int)threadIdx.x) + 679))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 269))]));
    compute1[(20)] = (compute1[(20)] + (pad_temp_shared[((((int)threadIdx.x) + 679))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 525))]));
    compute1[(27)] = (compute1[(27)] + (pad_temp_shared[((((int)threadIdx.x) + 679))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 781))]));
    compute1[(0)] = (compute1[(0)] + (pad_temp_shared[((((int)threadIdx.x) + 686))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 14))]));
    compute1[(7)] = (compute1[(7)] + (pad_temp_shared[((((int)threadIdx.x) + 686))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 270))]));
    compute1[(14)] = (compute1[(14)] + (pad_temp_shared[((((int)threadIdx.x) + 686))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 526))]));
    compute1[(21)] = (compute1[(21)] + (pad_temp_shared[((((int)threadIdx.x) + 686))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 782))]));
    compute1[(1)] = (compute1[(1)] + (pad_temp_shared[((((int)threadIdx.x) + 693))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 14))]));
    compute1[(8)] = (compute1[(8)] + (pad_temp_shared[((((int)threadIdx.x) + 693))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 270))]));
    compute1[(15)] = (compute1[(15)] + (pad_temp_shared[((((int)threadIdx.x) + 693))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 526))]));
    compute1[(22)] = (compute1[(22)] + (pad_temp_shared[((((int)threadIdx.x) + 693))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 782))]));
    compute1[(2)] = (compute1[(2)] + (pad_temp_shared[((((int)threadIdx.x) + 700))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 14))]));
    compute1[(9)] = (compute1[(9)] + (pad_temp_shared[((((int)threadIdx.x) + 700))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 270))]));
    compute1[(16)] = (compute1[(16)] + (pad_temp_shared[((((int)threadIdx.x) + 700))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 526))]));
    compute1[(23)] = (compute1[(23)] + (pad_temp_shared[((((int)threadIdx.x) + 700))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 782))]));
    compute1[(3)] = (compute1[(3)] + (pad_temp_shared[((((int)threadIdx.x) + 707))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 14))]));
    compute1[(10)] = (compute1[(10)] + (pad_temp_shared[((((int)threadIdx.x) + 707))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 270))]));
    compute1[(17)] = (compute1[(17)] + (pad_temp_shared[((((int)threadIdx.x) + 707))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 526))]));
    compute1[(24)] = (compute1[(24)] + (pad_temp_shared[((((int)threadIdx.x) + 707))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 782))]));
    compute1[(4)] = (compute1[(4)] + (pad_temp_shared[((((int)threadIdx.x) + 714))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 14))]));
    compute1[(11)] = (compute1[(11)] + (pad_temp_shared[((((int)threadIdx.x) + 714))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 270))]));
    compute1[(18)] = (compute1[(18)] + (pad_temp_shared[((((int)threadIdx.x) + 714))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 526))]));
    compute1[(25)] = (compute1[(25)] + (pad_temp_shared[((((int)threadIdx.x) + 714))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 782))]));
    compute1[(5)] = (compute1[(5)] + (pad_temp_shared[((((int)threadIdx.x) + 721))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 14))]));
    compute1[(12)] = (compute1[(12)] + (pad_temp_shared[((((int)threadIdx.x) + 721))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 270))]));
    compute1[(19)] = (compute1[(19)] + (pad_temp_shared[((((int)threadIdx.x) + 721))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 526))]));
    compute1[(26)] = (compute1[(26)] + (pad_temp_shared[((((int)threadIdx.x) + 721))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 782))]));
    compute1[(6)] = (compute1[(6)] + (pad_temp_shared[((((int)threadIdx.x) + 728))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 14))]));
    compute1[(13)] = (compute1[(13)] + (pad_temp_shared[((((int)threadIdx.x) + 728))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 270))]));
    compute1[(20)] = (compute1[(20)] + (pad_temp_shared[((((int)threadIdx.x) + 728))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 526))]));
    compute1[(27)] = (compute1[(27)] + (pad_temp_shared[((((int)threadIdx.x) + 728))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 782))]));
    compute1[(0)] = (compute1[(0)] + (pad_temp_shared[((((int)threadIdx.x) + 735))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 15))]));
    compute1[(7)] = (compute1[(7)] + (pad_temp_shared[((((int)threadIdx.x) + 735))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 271))]));
    compute1[(14)] = (compute1[(14)] + (pad_temp_shared[((((int)threadIdx.x) + 735))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 527))]));
    compute1[(21)] = (compute1[(21)] + (pad_temp_shared[((((int)threadIdx.x) + 735))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 783))]));
    compute1[(1)] = (compute1[(1)] + (pad_temp_shared[((((int)threadIdx.x) + 742))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 15))]));
    compute1[(8)] = (compute1[(8)] + (pad_temp_shared[((((int)threadIdx.x) + 742))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 271))]));
    compute1[(15)] = (compute1[(15)] + (pad_temp_shared[((((int)threadIdx.x) + 742))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 527))]));
    compute1[(22)] = (compute1[(22)] + (pad_temp_shared[((((int)threadIdx.x) + 742))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 783))]));
    compute1[(2)] = (compute1[(2)] + (pad_temp_shared[((((int)threadIdx.x) + 749))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 15))]));
    compute1[(9)] = (compute1[(9)] + (pad_temp_shared[((((int)threadIdx.x) + 749))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 271))]));
    compute1[(16)] = (compute1[(16)] + (pad_temp_shared[((((int)threadIdx.x) + 749))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 527))]));
    compute1[(23)] = (compute1[(23)] + (pad_temp_shared[((((int)threadIdx.x) + 749))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 783))]));
    compute1[(3)] = (compute1[(3)] + (pad_temp_shared[((((int)threadIdx.x) + 756))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 15))]));
    compute1[(10)] = (compute1[(10)] + (pad_temp_shared[((((int)threadIdx.x) + 756))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 271))]));
    compute1[(17)] = (compute1[(17)] + (pad_temp_shared[((((int)threadIdx.x) + 756))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 527))]));
    compute1[(24)] = (compute1[(24)] + (pad_temp_shared[((((int)threadIdx.x) + 756))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 783))]));
    compute1[(4)] = (compute1[(4)] + (pad_temp_shared[((((int)threadIdx.x) + 763))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 15))]));
    compute1[(11)] = (compute1[(11)] + (pad_temp_shared[((((int)threadIdx.x) + 763))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 271))]));
    compute1[(18)] = (compute1[(18)] + (pad_temp_shared[((((int)threadIdx.x) + 763))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 527))]));
    compute1[(25)] = (compute1[(25)] + (pad_temp_shared[((((int)threadIdx.x) + 763))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 783))]));
    compute1[(5)] = (compute1[(5)] + (pad_temp_shared[((((int)threadIdx.x) + 770))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 15))]));
    compute1[(12)] = (compute1[(12)] + (pad_temp_shared[((((int)threadIdx.x) + 770))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 271))]));
    compute1[(19)] = (compute1[(19)] + (pad_temp_shared[((((int)threadIdx.x) + 770))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 527))]));
    compute1[(26)] = (compute1[(26)] + (pad_temp_shared[((((int)threadIdx.x) + 770))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 783))]));
    compute1[(6)] = (compute1[(6)] + (pad_temp_shared[((((int)threadIdx.x) + 777))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 15))]));
    compute1[(13)] = (compute1[(13)] + (pad_temp_shared[((((int)threadIdx.x) + 777))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 271))]));
    compute1[(20)] = (compute1[(20)] + (pad_temp_shared[((((int)threadIdx.x) + 777))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 527))]));
    compute1[(27)] = (compute1[(27)] + (pad_temp_shared[((((int)threadIdx.x) + 777))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 783))]));
  }
  compute[((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)))] = max((compute1[(0)] + input2[((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)))]), 0.000000e+00f);
  compute[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 784))] = max((compute1[(7)] + input2[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 784))]), 0.000000e+00f);
  compute[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 1568))] = max((compute1[(14)] + input2[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 1568))]), 0.000000e+00f);
  compute[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 2352))] = max((compute1[(21)] + input2[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 2352))]), 0.000000e+00f);
  compute[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 7))] = max((compute1[(1)] + input2[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 7))]), 0.000000e+00f);
  compute[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 791))] = max((compute1[(8)] + input2[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 791))]), 0.000000e+00f);
  compute[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 1575))] = max((compute1[(15)] + input2[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 1575))]), 0.000000e+00f);
  compute[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 2359))] = max((compute1[(22)] + input2[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 2359))]), 0.000000e+00f);
  compute[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 14))] = max((compute1[(2)] + input2[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 14))]), 0.000000e+00f);
  compute[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 798))] = max((compute1[(9)] + input2[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 798))]), 0.000000e+00f);
  compute[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 1582))] = max((compute1[(16)] + input2[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 1582))]), 0.000000e+00f);
  compute[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 2366))] = max((compute1[(23)] + input2[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 2366))]), 0.000000e+00f);
  compute[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 21))] = max((compute1[(3)] + input2[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 21))]), 0.000000e+00f);
  compute[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 805))] = max((compute1[(10)] + input2[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 805))]), 0.000000e+00f);
  compute[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 1589))] = max((compute1[(17)] + input2[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 1589))]), 0.000000e+00f);
  compute[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 2373))] = max((compute1[(24)] + input2[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 2373))]), 0.000000e+00f);
  compute[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 28))] = max((compute1[(4)] + input2[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 28))]), 0.000000e+00f);
  compute[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 812))] = max((compute1[(11)] + input2[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 812))]), 0.000000e+00f);
  compute[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 1596))] = max((compute1[(18)] + input2[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 1596))]), 0.000000e+00f);
  compute[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 2380))] = max((compute1[(25)] + input2[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 2380))]), 0.000000e+00f);
  compute[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 35))] = max((compute1[(5)] + input2[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 35))]), 0.000000e+00f);
  compute[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 819))] = max((compute1[(12)] + input2[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 819))]), 0.000000e+00f);
  compute[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 1603))] = max((compute1[(19)] + input2[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 1603))]), 0.000000e+00f);
  compute[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 2387))] = max((compute1[(26)] + input2[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 2387))]), 0.000000e+00f);
  compute[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 42))] = max((compute1[(6)] + input2[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 42))]), 0.000000e+00f);
  compute[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 826))] = max((compute1[(13)] + input2[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 826))]), 0.000000e+00f);
  compute[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 1610))] = max((compute1[(20)] + input2[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 1610))]), 0.000000e+00f);
  compute[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 2394))] = max((compute1[(27)] + input2[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 2394))]), 0.000000e+00f);
}

