//1_83_128_83_1_1
//128_96_83_83_42_1_1_SAME
//dim3 grid(1, 83, 128);
//dim3 block(83, 1, 1);

#ifdef _WIN32
  using uint = unsigned int;
  using uchar = unsigned char;
  using ushort = unsigned short;
  using int64_t = long long;
  using uint64_t = unsigned long long;
#else
  #define uint unsigned int
  #define uchar unsigned char
  #define ushort unsigned short
  #define int64_t long long
  #define uint64_t unsigned long long
#endif
extern "C" __global__ void __launch_bounds__(83) conv_kernel0(float* __restrict__ placeholder, float* __restrict__ placeholder1, float* __restrict__ compute) {
  float compute_local[42];
  __shared__ float pad_temp_shared[249];
  __shared__ float placeholder_shared[126];
  compute_local[(0)] = 0.000000e+00f;
  compute_local[(3)] = 0.000000e+00f;
  compute_local[(6)] = 0.000000e+00f;
  compute_local[(9)] = 0.000000e+00f;
  compute_local[(12)] = 0.000000e+00f;
  compute_local[(15)] = 0.000000e+00f;
  compute_local[(18)] = 0.000000e+00f;
  compute_local[(21)] = 0.000000e+00f;
  compute_local[(24)] = 0.000000e+00f;
  compute_local[(27)] = 0.000000e+00f;
  compute_local[(30)] = 0.000000e+00f;
  compute_local[(33)] = 0.000000e+00f;
  compute_local[(36)] = 0.000000e+00f;
  compute_local[(39)] = 0.000000e+00f;
  compute_local[(1)] = 0.000000e+00f;
  compute_local[(4)] = 0.000000e+00f;
  compute_local[(7)] = 0.000000e+00f;
  compute_local[(10)] = 0.000000e+00f;
  compute_local[(13)] = 0.000000e+00f;
  compute_local[(16)] = 0.000000e+00f;
  compute_local[(19)] = 0.000000e+00f;
  compute_local[(22)] = 0.000000e+00f;
  compute_local[(25)] = 0.000000e+00f;
  compute_local[(28)] = 0.000000e+00f;
  compute_local[(31)] = 0.000000e+00f;
  compute_local[(34)] = 0.000000e+00f;
  compute_local[(37)] = 0.000000e+00f;
  compute_local[(40)] = 0.000000e+00f;
  compute_local[(2)] = 0.000000e+00f;
  compute_local[(5)] = 0.000000e+00f;
  compute_local[(8)] = 0.000000e+00f;
  compute_local[(11)] = 0.000000e+00f;
  compute_local[(14)] = 0.000000e+00f;
  compute_local[(17)] = 0.000000e+00f;
  compute_local[(20)] = 0.000000e+00f;
  compute_local[(23)] = 0.000000e+00f;
  compute_local[(26)] = 0.000000e+00f;
  compute_local[(29)] = 0.000000e+00f;
  compute_local[(32)] = 0.000000e+00f;
  compute_local[(35)] = 0.000000e+00f;
  compute_local[(38)] = 0.000000e+00f;
  compute_local[(41)] = 0.000000e+00f;
  for (int rc_outer = 0; rc_outer < 32; ++rc_outer) {
    __syncthreads();
    pad_temp_shared[((((int)threadIdx.x) * 3))] = placeholder[((((((((int)blockIdx.z) * 661344) + (rc_outer * 20667)) + (((((int)threadIdx.x) * 3) / 83) * 6889)) + (((int)blockIdx.y) * 83)) + ((((int)threadIdx.x) * 3) % 83)))];
    pad_temp_shared[(((((int)threadIdx.x) * 3) + 1))] = placeholder[((((((((int)blockIdx.z) * 661344) + (rc_outer * 20667)) + ((((((int)threadIdx.x) * 3) + 1) / 83) * 6889)) + (((int)blockIdx.y) * 83)) + (((((int)threadIdx.x) * 3) + 1) % 83)))];
    pad_temp_shared[(((((int)threadIdx.x) * 3) + 2))] = placeholder[((((((((int)blockIdx.z) * 661344) + (rc_outer * 20667)) + ((((((int)threadIdx.x) * 3) + 2) / 83) * 6889)) + (((int)blockIdx.y) * 83)) + (((((int)threadIdx.x) * 3) + 2) % 83)))];
    if (((int)threadIdx.x) < 63) {
      placeholder_shared[((((int)threadIdx.x) * 2))] = placeholder1[((((((((int)threadIdx.x) * 2) / 3) * 96) + (rc_outer * 3)) + ((((int)threadIdx.x) * 2) % 3)))];
    }
    if (((int)threadIdx.x) < 63) {
      placeholder_shared[(((((int)threadIdx.x) * 2) + 1))] = placeholder1[(((((((((int)threadIdx.x) * 2) + 1) / 3) * 96) + (rc_outer * 3)) + (((((int)threadIdx.x) * 2) + 1) % 3)))];
    }
    __syncthreads();
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((int)threadIdx.x))] * placeholder_shared[(0)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[(((int)threadIdx.x))] * placeholder_shared[(9)]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[(((int)threadIdx.x))] * placeholder_shared[(18)]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[(((int)threadIdx.x))] * placeholder_shared[(27)]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[(((int)threadIdx.x))] * placeholder_shared[(36)]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[(((int)threadIdx.x))] * placeholder_shared[(45)]));
    compute_local[(18)] = (compute_local[(18)] + (pad_temp_shared[(((int)threadIdx.x))] * placeholder_shared[(54)]));
    compute_local[(21)] = (compute_local[(21)] + (pad_temp_shared[(((int)threadIdx.x))] * placeholder_shared[(63)]));
    compute_local[(24)] = (compute_local[(24)] + (pad_temp_shared[(((int)threadIdx.x))] * placeholder_shared[(72)]));
    compute_local[(27)] = (compute_local[(27)] + (pad_temp_shared[(((int)threadIdx.x))] * placeholder_shared[(81)]));
    compute_local[(30)] = (compute_local[(30)] + (pad_temp_shared[(((int)threadIdx.x))] * placeholder_shared[(90)]));
    compute_local[(33)] = (compute_local[(33)] + (pad_temp_shared[(((int)threadIdx.x))] * placeholder_shared[(99)]));
    compute_local[(36)] = (compute_local[(36)] + (pad_temp_shared[(((int)threadIdx.x))] * placeholder_shared[(108)]));
    compute_local[(39)] = (compute_local[(39)] + (pad_temp_shared[(((int)threadIdx.x))] * placeholder_shared[(117)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[(((int)threadIdx.x))] * placeholder_shared[(3)]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[(((int)threadIdx.x))] * placeholder_shared[(12)]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((int)threadIdx.x))] * placeholder_shared[(21)]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[(((int)threadIdx.x))] * placeholder_shared[(30)]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[(((int)threadIdx.x))] * placeholder_shared[(39)]));
    compute_local[(16)] = (compute_local[(16)] + (pad_temp_shared[(((int)threadIdx.x))] * placeholder_shared[(48)]));
    compute_local[(19)] = (compute_local[(19)] + (pad_temp_shared[(((int)threadIdx.x))] * placeholder_shared[(57)]));
    compute_local[(22)] = (compute_local[(22)] + (pad_temp_shared[(((int)threadIdx.x))] * placeholder_shared[(66)]));
    compute_local[(25)] = (compute_local[(25)] + (pad_temp_shared[(((int)threadIdx.x))] * placeholder_shared[(75)]));
    compute_local[(28)] = (compute_local[(28)] + (pad_temp_shared[(((int)threadIdx.x))] * placeholder_shared[(84)]));
    compute_local[(31)] = (compute_local[(31)] + (pad_temp_shared[(((int)threadIdx.x))] * placeholder_shared[(93)]));
    compute_local[(34)] = (compute_local[(34)] + (pad_temp_shared[(((int)threadIdx.x))] * placeholder_shared[(102)]));
    compute_local[(37)] = (compute_local[(37)] + (pad_temp_shared[(((int)threadIdx.x))] * placeholder_shared[(111)]));
    compute_local[(40)] = (compute_local[(40)] + (pad_temp_shared[(((int)threadIdx.x))] * placeholder_shared[(120)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[(((int)threadIdx.x))] * placeholder_shared[(6)]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[(((int)threadIdx.x))] * placeholder_shared[(15)]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[(((int)threadIdx.x))] * placeholder_shared[(24)]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[(((int)threadIdx.x))] * placeholder_shared[(33)]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[(((int)threadIdx.x))] * placeholder_shared[(42)]));
    compute_local[(17)] = (compute_local[(17)] + (pad_temp_shared[(((int)threadIdx.x))] * placeholder_shared[(51)]));
    compute_local[(20)] = (compute_local[(20)] + (pad_temp_shared[(((int)threadIdx.x))] * placeholder_shared[(60)]));
    compute_local[(23)] = (compute_local[(23)] + (pad_temp_shared[(((int)threadIdx.x))] * placeholder_shared[(69)]));
    compute_local[(26)] = (compute_local[(26)] + (pad_temp_shared[(((int)threadIdx.x))] * placeholder_shared[(78)]));
    compute_local[(29)] = (compute_local[(29)] + (pad_temp_shared[(((int)threadIdx.x))] * placeholder_shared[(87)]));
    compute_local[(32)] = (compute_local[(32)] + (pad_temp_shared[(((int)threadIdx.x))] * placeholder_shared[(96)]));
    compute_local[(35)] = (compute_local[(35)] + (pad_temp_shared[(((int)threadIdx.x))] * placeholder_shared[(105)]));
    compute_local[(38)] = (compute_local[(38)] + (pad_temp_shared[(((int)threadIdx.x))] * placeholder_shared[(114)]));
    compute_local[(41)] = (compute_local[(41)] + (pad_temp_shared[(((int)threadIdx.x))] * placeholder_shared[(123)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[((((int)threadIdx.x) + 83))] * placeholder_shared[(1)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[((((int)threadIdx.x) + 83))] * placeholder_shared[(10)]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[((((int)threadIdx.x) + 83))] * placeholder_shared[(19)]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[((((int)threadIdx.x) + 83))] * placeholder_shared[(28)]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[((((int)threadIdx.x) + 83))] * placeholder_shared[(37)]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[((((int)threadIdx.x) + 83))] * placeholder_shared[(46)]));
    compute_local[(18)] = (compute_local[(18)] + (pad_temp_shared[((((int)threadIdx.x) + 83))] * placeholder_shared[(55)]));
    compute_local[(21)] = (compute_local[(21)] + (pad_temp_shared[((((int)threadIdx.x) + 83))] * placeholder_shared[(64)]));
    compute_local[(24)] = (compute_local[(24)] + (pad_temp_shared[((((int)threadIdx.x) + 83))] * placeholder_shared[(73)]));
    compute_local[(27)] = (compute_local[(27)] + (pad_temp_shared[((((int)threadIdx.x) + 83))] * placeholder_shared[(82)]));
    compute_local[(30)] = (compute_local[(30)] + (pad_temp_shared[((((int)threadIdx.x) + 83))] * placeholder_shared[(91)]));
    compute_local[(33)] = (compute_local[(33)] + (pad_temp_shared[((((int)threadIdx.x) + 83))] * placeholder_shared[(100)]));
    compute_local[(36)] = (compute_local[(36)] + (pad_temp_shared[((((int)threadIdx.x) + 83))] * placeholder_shared[(109)]));
    compute_local[(39)] = (compute_local[(39)] + (pad_temp_shared[((((int)threadIdx.x) + 83))] * placeholder_shared[(118)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[((((int)threadIdx.x) + 83))] * placeholder_shared[(4)]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[((((int)threadIdx.x) + 83))] * placeholder_shared[(13)]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[((((int)threadIdx.x) + 83))] * placeholder_shared[(22)]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[((((int)threadIdx.x) + 83))] * placeholder_shared[(31)]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[((((int)threadIdx.x) + 83))] * placeholder_shared[(40)]));
    compute_local[(16)] = (compute_local[(16)] + (pad_temp_shared[((((int)threadIdx.x) + 83))] * placeholder_shared[(49)]));
    compute_local[(19)] = (compute_local[(19)] + (pad_temp_shared[((((int)threadIdx.x) + 83))] * placeholder_shared[(58)]));
    compute_local[(22)] = (compute_local[(22)] + (pad_temp_shared[((((int)threadIdx.x) + 83))] * placeholder_shared[(67)]));
    compute_local[(25)] = (compute_local[(25)] + (pad_temp_shared[((((int)threadIdx.x) + 83))] * placeholder_shared[(76)]));
    compute_local[(28)] = (compute_local[(28)] + (pad_temp_shared[((((int)threadIdx.x) + 83))] * placeholder_shared[(85)]));
    compute_local[(31)] = (compute_local[(31)] + (pad_temp_shared[((((int)threadIdx.x) + 83))] * placeholder_shared[(94)]));
    compute_local[(34)] = (compute_local[(34)] + (pad_temp_shared[((((int)threadIdx.x) + 83))] * placeholder_shared[(103)]));
    compute_local[(37)] = (compute_local[(37)] + (pad_temp_shared[((((int)threadIdx.x) + 83))] * placeholder_shared[(112)]));
    compute_local[(40)] = (compute_local[(40)] + (pad_temp_shared[((((int)threadIdx.x) + 83))] * placeholder_shared[(121)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[((((int)threadIdx.x) + 83))] * placeholder_shared[(7)]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[((((int)threadIdx.x) + 83))] * placeholder_shared[(16)]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[((((int)threadIdx.x) + 83))] * placeholder_shared[(25)]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[((((int)threadIdx.x) + 83))] * placeholder_shared[(34)]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[((((int)threadIdx.x) + 83))] * placeholder_shared[(43)]));
    compute_local[(17)] = (compute_local[(17)] + (pad_temp_shared[((((int)threadIdx.x) + 83))] * placeholder_shared[(52)]));
    compute_local[(20)] = (compute_local[(20)] + (pad_temp_shared[((((int)threadIdx.x) + 83))] * placeholder_shared[(61)]));
    compute_local[(23)] = (compute_local[(23)] + (pad_temp_shared[((((int)threadIdx.x) + 83))] * placeholder_shared[(70)]));
    compute_local[(26)] = (compute_local[(26)] + (pad_temp_shared[((((int)threadIdx.x) + 83))] * placeholder_shared[(79)]));
    compute_local[(29)] = (compute_local[(29)] + (pad_temp_shared[((((int)threadIdx.x) + 83))] * placeholder_shared[(88)]));
    compute_local[(32)] = (compute_local[(32)] + (pad_temp_shared[((((int)threadIdx.x) + 83))] * placeholder_shared[(97)]));
    compute_local[(35)] = (compute_local[(35)] + (pad_temp_shared[((((int)threadIdx.x) + 83))] * placeholder_shared[(106)]));
    compute_local[(38)] = (compute_local[(38)] + (pad_temp_shared[((((int)threadIdx.x) + 83))] * placeholder_shared[(115)]));
    compute_local[(41)] = (compute_local[(41)] + (pad_temp_shared[((((int)threadIdx.x) + 83))] * placeholder_shared[(124)]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[((((int)threadIdx.x) + 166))] * placeholder_shared[(2)]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[((((int)threadIdx.x) + 166))] * placeholder_shared[(11)]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[((((int)threadIdx.x) + 166))] * placeholder_shared[(20)]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[((((int)threadIdx.x) + 166))] * placeholder_shared[(29)]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[((((int)threadIdx.x) + 166))] * placeholder_shared[(38)]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[((((int)threadIdx.x) + 166))] * placeholder_shared[(47)]));
    compute_local[(18)] = (compute_local[(18)] + (pad_temp_shared[((((int)threadIdx.x) + 166))] * placeholder_shared[(56)]));
    compute_local[(21)] = (compute_local[(21)] + (pad_temp_shared[((((int)threadIdx.x) + 166))] * placeholder_shared[(65)]));
    compute_local[(24)] = (compute_local[(24)] + (pad_temp_shared[((((int)threadIdx.x) + 166))] * placeholder_shared[(74)]));
    compute_local[(27)] = (compute_local[(27)] + (pad_temp_shared[((((int)threadIdx.x) + 166))] * placeholder_shared[(83)]));
    compute_local[(30)] = (compute_local[(30)] + (pad_temp_shared[((((int)threadIdx.x) + 166))] * placeholder_shared[(92)]));
    compute_local[(33)] = (compute_local[(33)] + (pad_temp_shared[((((int)threadIdx.x) + 166))] * placeholder_shared[(101)]));
    compute_local[(36)] = (compute_local[(36)] + (pad_temp_shared[((((int)threadIdx.x) + 166))] * placeholder_shared[(110)]));
    compute_local[(39)] = (compute_local[(39)] + (pad_temp_shared[((((int)threadIdx.x) + 166))] * placeholder_shared[(119)]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[((((int)threadIdx.x) + 166))] * placeholder_shared[(5)]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[((((int)threadIdx.x) + 166))] * placeholder_shared[(14)]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[((((int)threadIdx.x) + 166))] * placeholder_shared[(23)]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[((((int)threadIdx.x) + 166))] * placeholder_shared[(32)]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[((((int)threadIdx.x) + 166))] * placeholder_shared[(41)]));
    compute_local[(16)] = (compute_local[(16)] + (pad_temp_shared[((((int)threadIdx.x) + 166))] * placeholder_shared[(50)]));
    compute_local[(19)] = (compute_local[(19)] + (pad_temp_shared[((((int)threadIdx.x) + 166))] * placeholder_shared[(59)]));
    compute_local[(22)] = (compute_local[(22)] + (pad_temp_shared[((((int)threadIdx.x) + 166))] * placeholder_shared[(68)]));
    compute_local[(25)] = (compute_local[(25)] + (pad_temp_shared[((((int)threadIdx.x) + 166))] * placeholder_shared[(77)]));
    compute_local[(28)] = (compute_local[(28)] + (pad_temp_shared[((((int)threadIdx.x) + 166))] * placeholder_shared[(86)]));
    compute_local[(31)] = (compute_local[(31)] + (pad_temp_shared[((((int)threadIdx.x) + 166))] * placeholder_shared[(95)]));
    compute_local[(34)] = (compute_local[(34)] + (pad_temp_shared[((((int)threadIdx.x) + 166))] * placeholder_shared[(104)]));
    compute_local[(37)] = (compute_local[(37)] + (pad_temp_shared[((((int)threadIdx.x) + 166))] * placeholder_shared[(113)]));
    compute_local[(40)] = (compute_local[(40)] + (pad_temp_shared[((((int)threadIdx.x) + 166))] * placeholder_shared[(122)]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[((((int)threadIdx.x) + 166))] * placeholder_shared[(8)]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[((((int)threadIdx.x) + 166))] * placeholder_shared[(17)]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[((((int)threadIdx.x) + 166))] * placeholder_shared[(26)]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[((((int)threadIdx.x) + 166))] * placeholder_shared[(35)]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[((((int)threadIdx.x) + 166))] * placeholder_shared[(44)]));
    compute_local[(17)] = (compute_local[(17)] + (pad_temp_shared[((((int)threadIdx.x) + 166))] * placeholder_shared[(53)]));
    compute_local[(20)] = (compute_local[(20)] + (pad_temp_shared[((((int)threadIdx.x) + 166))] * placeholder_shared[(62)]));
    compute_local[(23)] = (compute_local[(23)] + (pad_temp_shared[((((int)threadIdx.x) + 166))] * placeholder_shared[(71)]));
    compute_local[(26)] = (compute_local[(26)] + (pad_temp_shared[((((int)threadIdx.x) + 166))] * placeholder_shared[(80)]));
    compute_local[(29)] = (compute_local[(29)] + (pad_temp_shared[((((int)threadIdx.x) + 166))] * placeholder_shared[(89)]));
    compute_local[(32)] = (compute_local[(32)] + (pad_temp_shared[((((int)threadIdx.x) + 166))] * placeholder_shared[(98)]));
    compute_local[(35)] = (compute_local[(35)] + (pad_temp_shared[((((int)threadIdx.x) + 166))] * placeholder_shared[(107)]));
    compute_local[(38)] = (compute_local[(38)] + (pad_temp_shared[((((int)threadIdx.x) + 166))] * placeholder_shared[(116)]));
    compute_local[(41)] = (compute_local[(41)] + (pad_temp_shared[((((int)threadIdx.x) + 166))] * placeholder_shared[(125)]));
  }
  compute[((((((int)blockIdx.z) * 289338) + (((int)blockIdx.y) * 83)) + ((int)threadIdx.x)))] = compute_local[(0)];
  compute[(((((((int)blockIdx.z) * 289338) + (((int)blockIdx.y) * 83)) + ((int)threadIdx.x)) + 20667))] = compute_local[(3)];
  compute[(((((((int)blockIdx.z) * 289338) + (((int)blockIdx.y) * 83)) + ((int)threadIdx.x)) + 41334))] = compute_local[(6)];
  compute[(((((((int)blockIdx.z) * 289338) + (((int)blockIdx.y) * 83)) + ((int)threadIdx.x)) + 62001))] = compute_local[(9)];
  compute[(((((((int)blockIdx.z) * 289338) + (((int)blockIdx.y) * 83)) + ((int)threadIdx.x)) + 82668))] = compute_local[(12)];
  compute[(((((((int)blockIdx.z) * 289338) + (((int)blockIdx.y) * 83)) + ((int)threadIdx.x)) + 103335))] = compute_local[(15)];
  compute[(((((((int)blockIdx.z) * 289338) + (((int)blockIdx.y) * 83)) + ((int)threadIdx.x)) + 124002))] = compute_local[(18)];
  compute[(((((((int)blockIdx.z) * 289338) + (((int)blockIdx.y) * 83)) + ((int)threadIdx.x)) + 144669))] = compute_local[(21)];
  compute[(((((((int)blockIdx.z) * 289338) + (((int)blockIdx.y) * 83)) + ((int)threadIdx.x)) + 165336))] = compute_local[(24)];
  compute[(((((((int)blockIdx.z) * 289338) + (((int)blockIdx.y) * 83)) + ((int)threadIdx.x)) + 186003))] = compute_local[(27)];
  compute[(((((((int)blockIdx.z) * 289338) + (((int)blockIdx.y) * 83)) + ((int)threadIdx.x)) + 206670))] = compute_local[(30)];
  compute[(((((((int)blockIdx.z) * 289338) + (((int)blockIdx.y) * 83)) + ((int)threadIdx.x)) + 227337))] = compute_local[(33)];
  compute[(((((((int)blockIdx.z) * 289338) + (((int)blockIdx.y) * 83)) + ((int)threadIdx.x)) + 248004))] = compute_local[(36)];
  compute[(((((((int)blockIdx.z) * 289338) + (((int)blockIdx.y) * 83)) + ((int)threadIdx.x)) + 268671))] = compute_local[(39)];
  compute[(((((((int)blockIdx.z) * 289338) + (((int)blockIdx.y) * 83)) + ((int)threadIdx.x)) + 6889))] = compute_local[(1)];
  compute[(((((((int)blockIdx.z) * 289338) + (((int)blockIdx.y) * 83)) + ((int)threadIdx.x)) + 27556))] = compute_local[(4)];
  compute[(((((((int)blockIdx.z) * 289338) + (((int)blockIdx.y) * 83)) + ((int)threadIdx.x)) + 48223))] = compute_local[(7)];
  compute[(((((((int)blockIdx.z) * 289338) + (((int)blockIdx.y) * 83)) + ((int)threadIdx.x)) + 68890))] = compute_local[(10)];
  compute[(((((((int)blockIdx.z) * 289338) + (((int)blockIdx.y) * 83)) + ((int)threadIdx.x)) + 89557))] = compute_local[(13)];
  compute[(((((((int)blockIdx.z) * 289338) + (((int)blockIdx.y) * 83)) + ((int)threadIdx.x)) + 110224))] = compute_local[(16)];
  compute[(((((((int)blockIdx.z) * 289338) + (((int)blockIdx.y) * 83)) + ((int)threadIdx.x)) + 130891))] = compute_local[(19)];
  compute[(((((((int)blockIdx.z) * 289338) + (((int)blockIdx.y) * 83)) + ((int)threadIdx.x)) + 151558))] = compute_local[(22)];
  compute[(((((((int)blockIdx.z) * 289338) + (((int)blockIdx.y) * 83)) + ((int)threadIdx.x)) + 172225))] = compute_local[(25)];
  compute[(((((((int)blockIdx.z) * 289338) + (((int)blockIdx.y) * 83)) + ((int)threadIdx.x)) + 192892))] = compute_local[(28)];
  compute[(((((((int)blockIdx.z) * 289338) + (((int)blockIdx.y) * 83)) + ((int)threadIdx.x)) + 213559))] = compute_local[(31)];
  compute[(((((((int)blockIdx.z) * 289338) + (((int)blockIdx.y) * 83)) + ((int)threadIdx.x)) + 234226))] = compute_local[(34)];
  compute[(((((((int)blockIdx.z) * 289338) + (((int)blockIdx.y) * 83)) + ((int)threadIdx.x)) + 254893))] = compute_local[(37)];
  compute[(((((((int)blockIdx.z) * 289338) + (((int)blockIdx.y) * 83)) + ((int)threadIdx.x)) + 275560))] = compute_local[(40)];
  compute[(((((((int)blockIdx.z) * 289338) + (((int)blockIdx.y) * 83)) + ((int)threadIdx.x)) + 13778))] = compute_local[(2)];
  compute[(((((((int)blockIdx.z) * 289338) + (((int)blockIdx.y) * 83)) + ((int)threadIdx.x)) + 34445))] = compute_local[(5)];
  compute[(((((((int)blockIdx.z) * 289338) + (((int)blockIdx.y) * 83)) + ((int)threadIdx.x)) + 55112))] = compute_local[(8)];
  compute[(((((((int)blockIdx.z) * 289338) + (((int)blockIdx.y) * 83)) + ((int)threadIdx.x)) + 75779))] = compute_local[(11)];
  compute[(((((((int)blockIdx.z) * 289338) + (((int)blockIdx.y) * 83)) + ((int)threadIdx.x)) + 96446))] = compute_local[(14)];
  compute[(((((((int)blockIdx.z) * 289338) + (((int)blockIdx.y) * 83)) + ((int)threadIdx.x)) + 117113))] = compute_local[(17)];
  compute[(((((((int)blockIdx.z) * 289338) + (((int)blockIdx.y) * 83)) + ((int)threadIdx.x)) + 137780))] = compute_local[(20)];
  compute[(((((((int)blockIdx.z) * 289338) + (((int)blockIdx.y) * 83)) + ((int)threadIdx.x)) + 158447))] = compute_local[(23)];
  compute[(((((((int)blockIdx.z) * 289338) + (((int)blockIdx.y) * 83)) + ((int)threadIdx.x)) + 179114))] = compute_local[(26)];
  compute[(((((((int)blockIdx.z) * 289338) + (((int)blockIdx.y) * 83)) + ((int)threadIdx.x)) + 199781))] = compute_local[(29)];
  compute[(((((((int)blockIdx.z) * 289338) + (((int)blockIdx.y) * 83)) + ((int)threadIdx.x)) + 220448))] = compute_local[(32)];
  compute[(((((((int)blockIdx.z) * 289338) + (((int)blockIdx.y) * 83)) + ((int)threadIdx.x)) + 241115))] = compute_local[(35)];
  compute[(((((((int)blockIdx.z) * 289338) + (((int)blockIdx.y) * 83)) + ((int)threadIdx.x)) + 261782))] = compute_local[(38)];
  compute[(((((((int)blockIdx.z) * 289338) + (((int)blockIdx.y) * 83)) + ((int)threadIdx.x)) + 282449))] = compute_local[(41)];
}

