//1_1_1024_7_1_16
//128_2048_7_7_512_1_1_SAME
//dim3 grid(1, 1, 1024);
//dim3 block(7, 1, 16);

#ifdef _WIN32
  using uint = unsigned int;
  using uchar = unsigned char;
  using ushort = unsigned short;
  using int64_t = long long;
  using uint64_t = unsigned long long;
#else
  #define uint unsigned int
  #define uchar unsigned char
  #define ushort unsigned short
  #define int64_t long long
  #define uint64_t unsigned long long
#endif
extern "C" __global__ void __launch_bounds__(112) conv_kernel0(float* __restrict__ placeholder, float* __restrict__ placeholder1, float* __restrict__ compute) {
  float compute_local[28];
  __shared__ float pad_temp_shared[784];
  __shared__ float placeholder_shared[1024];
  compute_local[(0)] = 0.000000e+00f;
  compute_local[(7)] = 0.000000e+00f;
  compute_local[(14)] = 0.000000e+00f;
  compute_local[(21)] = 0.000000e+00f;
  compute_local[(1)] = 0.000000e+00f;
  compute_local[(8)] = 0.000000e+00f;
  compute_local[(15)] = 0.000000e+00f;
  compute_local[(22)] = 0.000000e+00f;
  compute_local[(2)] = 0.000000e+00f;
  compute_local[(9)] = 0.000000e+00f;
  compute_local[(16)] = 0.000000e+00f;
  compute_local[(23)] = 0.000000e+00f;
  compute_local[(3)] = 0.000000e+00f;
  compute_local[(10)] = 0.000000e+00f;
  compute_local[(17)] = 0.000000e+00f;
  compute_local[(24)] = 0.000000e+00f;
  compute_local[(4)] = 0.000000e+00f;
  compute_local[(11)] = 0.000000e+00f;
  compute_local[(18)] = 0.000000e+00f;
  compute_local[(25)] = 0.000000e+00f;
  compute_local[(5)] = 0.000000e+00f;
  compute_local[(12)] = 0.000000e+00f;
  compute_local[(19)] = 0.000000e+00f;
  compute_local[(26)] = 0.000000e+00f;
  compute_local[(6)] = 0.000000e+00f;
  compute_local[(13)] = 0.000000e+00f;
  compute_local[(20)] = 0.000000e+00f;
  compute_local[(27)] = 0.000000e+00f;
  for (int rc_outer = 0; rc_outer < 128; ++rc_outer) {
    __syncthreads();
    pad_temp_shared[(((((int)threadIdx.z) * 49) + (((int)threadIdx.x) * 7)))] = placeholder[((((((((int)blockIdx.z) >> 3) * 100352) + (rc_outer * 784)) + (((int)threadIdx.z) * 49)) + (((int)threadIdx.x) * 7)))];
    pad_temp_shared[((((((int)threadIdx.z) * 49) + (((int)threadIdx.x) * 7)) + 1))] = placeholder[(((((((((int)blockIdx.z) >> 3) * 100352) + (rc_outer * 784)) + (((int)threadIdx.z) * 49)) + (((int)threadIdx.x) * 7)) + 1))];
    pad_temp_shared[((((((int)threadIdx.z) * 49) + (((int)threadIdx.x) * 7)) + 2))] = placeholder[(((((((((int)blockIdx.z) >> 3) * 100352) + (rc_outer * 784)) + (((int)threadIdx.z) * 49)) + (((int)threadIdx.x) * 7)) + 2))];
    pad_temp_shared[((((((int)threadIdx.z) * 49) + (((int)threadIdx.x) * 7)) + 3))] = placeholder[(((((((((int)blockIdx.z) >> 3) * 100352) + (rc_outer * 784)) + (((int)threadIdx.z) * 49)) + (((int)threadIdx.x) * 7)) + 3))];
    pad_temp_shared[((((((int)threadIdx.z) * 49) + (((int)threadIdx.x) * 7)) + 4))] = placeholder[(((((((((int)blockIdx.z) >> 3) * 100352) + (rc_outer * 784)) + (((int)threadIdx.z) * 49)) + (((int)threadIdx.x) * 7)) + 4))];
    pad_temp_shared[((((((int)threadIdx.z) * 49) + (((int)threadIdx.x) * 7)) + 5))] = placeholder[(((((((((int)blockIdx.z) >> 3) * 100352) + (rc_outer * 784)) + (((int)threadIdx.z) * 49)) + (((int)threadIdx.x) * 7)) + 5))];
    pad_temp_shared[((((((int)threadIdx.z) * 49) + (((int)threadIdx.x) * 7)) + 6))] = placeholder[(((((((((int)blockIdx.z) >> 3) * 100352) + (rc_outer * 784)) + (((int)threadIdx.z) * 49)) + (((int)threadIdx.x) * 7)) + 6))];
    placeholder_shared[(((((int)threadIdx.z) * 64) + (((int)threadIdx.x) * 10)))] = placeholder1[(((((((((int)blockIdx.z) & 7) * 131072) + (((int)threadIdx.z) * 8192)) + (((((int)threadIdx.x) * 10) >> 4) * 2048)) + (rc_outer * 16)) + ((((int)threadIdx.x) * 10) & 15)))];
    placeholder_shared[((((((int)threadIdx.z) * 64) + (((int)threadIdx.x) * 10)) + 1))] = placeholder1[(((((((((int)blockIdx.z) & 7) * 131072) + (((int)threadIdx.z) * 8192)) + ((((((int)threadIdx.x) * 10) + 1) >> 4) * 2048)) + (rc_outer * 16)) + (((((int)threadIdx.x) * 10) + 1) & 15)))];
    placeholder_shared[((((((int)threadIdx.z) * 64) + (((int)threadIdx.x) * 10)) + 2))] = placeholder1[(((((((((int)blockIdx.z) & 7) * 131072) + (((int)threadIdx.z) * 8192)) + ((((((int)threadIdx.x) * 10) + 2) >> 4) * 2048)) + (rc_outer * 16)) + (((((int)threadIdx.x) * 10) + 2) & 15)))];
    placeholder_shared[((((((int)threadIdx.z) * 64) + (((int)threadIdx.x) * 10)) + 3))] = placeholder1[(((((((((int)blockIdx.z) & 7) * 131072) + (((int)threadIdx.z) * 8192)) + ((((((int)threadIdx.x) * 10) + 3) >> 4) * 2048)) + (rc_outer * 16)) + (((((int)threadIdx.x) * 10) + 3) & 15)))];
    if (((((int)threadIdx.z) * 4) + (((((int)threadIdx.x) * 10) + 4) >> 4)) < 64) {
      if (((((int)threadIdx.z) * 64) + (((int)threadIdx.x) * 10)) < 1020) {
        if (((int)threadIdx.x) < 6) {
          placeholder_shared[((((((int)threadIdx.z) * 64) + (((int)threadIdx.x) * 10)) + 4))] = placeholder1[(((((((((int)blockIdx.z) & 7) * 131072) + (((int)threadIdx.z) * 8192)) + ((((((int)threadIdx.x) * 10) + 4) >> 4) * 2048)) + (rc_outer * 16)) + (((((int)threadIdx.x) * 10) + 4) & 15)))];
        }
      }
    }
    if (((((int)threadIdx.z) * 4) + (((((int)threadIdx.x) * 10) + 5) >> 4)) < 64) {
      if (((((int)threadIdx.z) * 64) + (((int)threadIdx.x) * 10)) < 1019) {
        if (((int)threadIdx.x) < 6) {
          placeholder_shared[((((((int)threadIdx.z) * 64) + (((int)threadIdx.x) * 10)) + 5))] = placeholder1[(((((((((int)blockIdx.z) & 7) * 131072) + (((int)threadIdx.z) * 8192)) + ((((((int)threadIdx.x) * 10) + 5) >> 4) * 2048)) + (rc_outer * 16)) + (((((int)threadIdx.x) * 10) + 5) & 15)))];
        }
      }
    }
    if (((((int)threadIdx.z) * 4) + (((((int)threadIdx.x) * 10) + 6) >> 4)) < 64) {
      if (((((int)threadIdx.z) * 64) + (((int)threadIdx.x) * 10)) < 1018) {
        if (((int)threadIdx.x) < 6) {
          placeholder_shared[((((((int)threadIdx.z) * 64) + (((int)threadIdx.x) * 10)) + 6))] = placeholder1[(((((((((int)blockIdx.z) & 7) * 131072) + (((int)threadIdx.z) * 8192)) + ((((((int)threadIdx.x) * 10) + 6) >> 4) * 2048)) + (rc_outer * 16)) + (((((int)threadIdx.x) * 10) + 6) & 15)))];
        }
      }
    }
    if (((((int)threadIdx.z) * 4) + (((((int)threadIdx.x) * 10) + 7) >> 4)) < 64) {
      if (((((int)threadIdx.z) * 64) + (((int)threadIdx.x) * 10)) < 1017) {
        if (((int)threadIdx.x) < 6) {
          placeholder_shared[((((((int)threadIdx.z) * 64) + (((int)threadIdx.x) * 10)) + 7))] = placeholder1[(((((((((int)blockIdx.z) & 7) * 131072) + (((int)threadIdx.z) * 8192)) + ((((((int)threadIdx.x) * 10) + 7) >> 4) * 2048)) + (rc_outer * 16)) + (((((int)threadIdx.x) * 10) + 7) & 15)))];
        }
      }
    }
    if (((((int)threadIdx.z) * 4) + (((((int)threadIdx.x) * 10) + 8) >> 4)) < 64) {
      if (((((int)threadIdx.z) * 64) + (((int)threadIdx.x) * 10)) < 1016) {
        if (((int)threadIdx.x) < 6) {
          placeholder_shared[((((((int)threadIdx.z) * 64) + (((int)threadIdx.x) * 10)) + 8))] = placeholder1[(((((((((int)blockIdx.z) & 7) * 131072) + (((int)threadIdx.z) * 8192)) + ((((((int)threadIdx.x) * 10) + 8) >> 4) * 2048)) + (rc_outer * 16)) + (((((int)threadIdx.x) * 10) + 8) & 15)))];
        }
      }
    }
    if (((((int)threadIdx.z) * 4) + (((((int)threadIdx.x) * 10) + 9) >> 4)) < 64) {
      if (((((int)threadIdx.z) * 64) + (((int)threadIdx.x) * 10)) < 1015) {
        if (((int)threadIdx.x) < 6) {
          placeholder_shared[((((((int)threadIdx.z) * 64) + (((int)threadIdx.x) * 10)) + 9))] = placeholder1[(((((((((int)blockIdx.z) & 7) * 131072) + (((int)threadIdx.z) * 8192)) + ((((((int)threadIdx.x) * 10) + 9) >> 4) * 2048)) + (rc_outer * 16)) + (((((int)threadIdx.x) * 10) + 9) & 15)))];
        }
      }
    }
    __syncthreads();
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[(((int)threadIdx.x))] * placeholder_shared[((((int)threadIdx.z) * 16))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[(((int)threadIdx.x))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 256))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[(((int)threadIdx.x))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 512))]));
    compute_local[(21)] = (compute_local[(21)] + (pad_temp_shared[(((int)threadIdx.x))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 768))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[((((int)threadIdx.x) + 7))] * placeholder_shared[((((int)threadIdx.z) * 16))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[((((int)threadIdx.x) + 7))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 256))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[((((int)threadIdx.x) + 7))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 512))]));
    compute_local[(22)] = (compute_local[(22)] + (pad_temp_shared[((((int)threadIdx.x) + 7))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 768))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[((((int)threadIdx.x) + 14))] * placeholder_shared[((((int)threadIdx.z) * 16))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[((((int)threadIdx.x) + 14))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 256))]));
    compute_local[(16)] = (compute_local[(16)] + (pad_temp_shared[((((int)threadIdx.x) + 14))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 512))]));
    compute_local[(23)] = (compute_local[(23)] + (pad_temp_shared[((((int)threadIdx.x) + 14))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 768))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[((((int)threadIdx.x) + 21))] * placeholder_shared[((((int)threadIdx.z) * 16))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[((((int)threadIdx.x) + 21))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 256))]));
    compute_local[(17)] = (compute_local[(17)] + (pad_temp_shared[((((int)threadIdx.x) + 21))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 512))]));
    compute_local[(24)] = (compute_local[(24)] + (pad_temp_shared[((((int)threadIdx.x) + 21))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 768))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[((((int)threadIdx.x) + 28))] * placeholder_shared[((((int)threadIdx.z) * 16))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[((((int)threadIdx.x) + 28))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 256))]));
    compute_local[(18)] = (compute_local[(18)] + (pad_temp_shared[((((int)threadIdx.x) + 28))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 512))]));
    compute_local[(25)] = (compute_local[(25)] + (pad_temp_shared[((((int)threadIdx.x) + 28))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 768))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[((((int)threadIdx.x) + 35))] * placeholder_shared[((((int)threadIdx.z) * 16))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[((((int)threadIdx.x) + 35))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 256))]));
    compute_local[(19)] = (compute_local[(19)] + (pad_temp_shared[((((int)threadIdx.x) + 35))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 512))]));
    compute_local[(26)] = (compute_local[(26)] + (pad_temp_shared[((((int)threadIdx.x) + 35))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 768))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[((((int)threadIdx.x) + 42))] * placeholder_shared[((((int)threadIdx.z) * 16))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[((((int)threadIdx.x) + 42))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 256))]));
    compute_local[(20)] = (compute_local[(20)] + (pad_temp_shared[((((int)threadIdx.x) + 42))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 512))]));
    compute_local[(27)] = (compute_local[(27)] + (pad_temp_shared[((((int)threadIdx.x) + 42))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 768))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[((((int)threadIdx.x) + 49))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 1))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[((((int)threadIdx.x) + 49))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 257))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[((((int)threadIdx.x) + 49))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 513))]));
    compute_local[(21)] = (compute_local[(21)] + (pad_temp_shared[((((int)threadIdx.x) + 49))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 769))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[((((int)threadIdx.x) + 56))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 1))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[((((int)threadIdx.x) + 56))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 257))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[((((int)threadIdx.x) + 56))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 513))]));
    compute_local[(22)] = (compute_local[(22)] + (pad_temp_shared[((((int)threadIdx.x) + 56))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 769))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[((((int)threadIdx.x) + 63))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 1))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[((((int)threadIdx.x) + 63))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 257))]));
    compute_local[(16)] = (compute_local[(16)] + (pad_temp_shared[((((int)threadIdx.x) + 63))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 513))]));
    compute_local[(23)] = (compute_local[(23)] + (pad_temp_shared[((((int)threadIdx.x) + 63))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 769))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[((((int)threadIdx.x) + 70))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 1))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[((((int)threadIdx.x) + 70))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 257))]));
    compute_local[(17)] = (compute_local[(17)] + (pad_temp_shared[((((int)threadIdx.x) + 70))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 513))]));
    compute_local[(24)] = (compute_local[(24)] + (pad_temp_shared[((((int)threadIdx.x) + 70))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 769))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[((((int)threadIdx.x) + 77))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 1))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[((((int)threadIdx.x) + 77))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 257))]));
    compute_local[(18)] = (compute_local[(18)] + (pad_temp_shared[((((int)threadIdx.x) + 77))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 513))]));
    compute_local[(25)] = (compute_local[(25)] + (pad_temp_shared[((((int)threadIdx.x) + 77))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 769))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[((((int)threadIdx.x) + 84))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 1))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[((((int)threadIdx.x) + 84))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 257))]));
    compute_local[(19)] = (compute_local[(19)] + (pad_temp_shared[((((int)threadIdx.x) + 84))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 513))]));
    compute_local[(26)] = (compute_local[(26)] + (pad_temp_shared[((((int)threadIdx.x) + 84))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 769))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[((((int)threadIdx.x) + 91))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 1))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[((((int)threadIdx.x) + 91))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 257))]));
    compute_local[(20)] = (compute_local[(20)] + (pad_temp_shared[((((int)threadIdx.x) + 91))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 513))]));
    compute_local[(27)] = (compute_local[(27)] + (pad_temp_shared[((((int)threadIdx.x) + 91))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 769))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[((((int)threadIdx.x) + 98))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 2))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[((((int)threadIdx.x) + 98))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 258))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[((((int)threadIdx.x) + 98))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 514))]));
    compute_local[(21)] = (compute_local[(21)] + (pad_temp_shared[((((int)threadIdx.x) + 98))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 770))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[((((int)threadIdx.x) + 105))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 2))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[((((int)threadIdx.x) + 105))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 258))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[((((int)threadIdx.x) + 105))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 514))]));
    compute_local[(22)] = (compute_local[(22)] + (pad_temp_shared[((((int)threadIdx.x) + 105))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 770))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[((((int)threadIdx.x) + 112))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 2))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[((((int)threadIdx.x) + 112))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 258))]));
    compute_local[(16)] = (compute_local[(16)] + (pad_temp_shared[((((int)threadIdx.x) + 112))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 514))]));
    compute_local[(23)] = (compute_local[(23)] + (pad_temp_shared[((((int)threadIdx.x) + 112))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 770))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[((((int)threadIdx.x) + 119))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 2))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[((((int)threadIdx.x) + 119))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 258))]));
    compute_local[(17)] = (compute_local[(17)] + (pad_temp_shared[((((int)threadIdx.x) + 119))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 514))]));
    compute_local[(24)] = (compute_local[(24)] + (pad_temp_shared[((((int)threadIdx.x) + 119))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 770))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[((((int)threadIdx.x) + 126))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 2))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[((((int)threadIdx.x) + 126))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 258))]));
    compute_local[(18)] = (compute_local[(18)] + (pad_temp_shared[((((int)threadIdx.x) + 126))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 514))]));
    compute_local[(25)] = (compute_local[(25)] + (pad_temp_shared[((((int)threadIdx.x) + 126))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 770))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[((((int)threadIdx.x) + 133))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 2))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[((((int)threadIdx.x) + 133))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 258))]));
    compute_local[(19)] = (compute_local[(19)] + (pad_temp_shared[((((int)threadIdx.x) + 133))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 514))]));
    compute_local[(26)] = (compute_local[(26)] + (pad_temp_shared[((((int)threadIdx.x) + 133))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 770))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[((((int)threadIdx.x) + 140))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 2))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[((((int)threadIdx.x) + 140))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 258))]));
    compute_local[(20)] = (compute_local[(20)] + (pad_temp_shared[((((int)threadIdx.x) + 140))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 514))]));
    compute_local[(27)] = (compute_local[(27)] + (pad_temp_shared[((((int)threadIdx.x) + 140))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 770))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[((((int)threadIdx.x) + 147))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 3))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[((((int)threadIdx.x) + 147))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 259))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[((((int)threadIdx.x) + 147))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 515))]));
    compute_local[(21)] = (compute_local[(21)] + (pad_temp_shared[((((int)threadIdx.x) + 147))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 771))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[((((int)threadIdx.x) + 154))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 3))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[((((int)threadIdx.x) + 154))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 259))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[((((int)threadIdx.x) + 154))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 515))]));
    compute_local[(22)] = (compute_local[(22)] + (pad_temp_shared[((((int)threadIdx.x) + 154))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 771))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[((((int)threadIdx.x) + 161))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 3))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[((((int)threadIdx.x) + 161))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 259))]));
    compute_local[(16)] = (compute_local[(16)] + (pad_temp_shared[((((int)threadIdx.x) + 161))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 515))]));
    compute_local[(23)] = (compute_local[(23)] + (pad_temp_shared[((((int)threadIdx.x) + 161))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 771))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[((((int)threadIdx.x) + 168))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 3))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[((((int)threadIdx.x) + 168))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 259))]));
    compute_local[(17)] = (compute_local[(17)] + (pad_temp_shared[((((int)threadIdx.x) + 168))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 515))]));
    compute_local[(24)] = (compute_local[(24)] + (pad_temp_shared[((((int)threadIdx.x) + 168))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 771))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[((((int)threadIdx.x) + 175))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 3))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[((((int)threadIdx.x) + 175))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 259))]));
    compute_local[(18)] = (compute_local[(18)] + (pad_temp_shared[((((int)threadIdx.x) + 175))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 515))]));
    compute_local[(25)] = (compute_local[(25)] + (pad_temp_shared[((((int)threadIdx.x) + 175))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 771))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[((((int)threadIdx.x) + 182))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 3))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[((((int)threadIdx.x) + 182))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 259))]));
    compute_local[(19)] = (compute_local[(19)] + (pad_temp_shared[((((int)threadIdx.x) + 182))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 515))]));
    compute_local[(26)] = (compute_local[(26)] + (pad_temp_shared[((((int)threadIdx.x) + 182))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 771))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[((((int)threadIdx.x) + 189))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 3))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[((((int)threadIdx.x) + 189))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 259))]));
    compute_local[(20)] = (compute_local[(20)] + (pad_temp_shared[((((int)threadIdx.x) + 189))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 515))]));
    compute_local[(27)] = (compute_local[(27)] + (pad_temp_shared[((((int)threadIdx.x) + 189))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 771))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[((((int)threadIdx.x) + 196))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 4))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[((((int)threadIdx.x) + 196))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 260))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[((((int)threadIdx.x) + 196))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 516))]));
    compute_local[(21)] = (compute_local[(21)] + (pad_temp_shared[((((int)threadIdx.x) + 196))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 772))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[((((int)threadIdx.x) + 203))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 4))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[((((int)threadIdx.x) + 203))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 260))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[((((int)threadIdx.x) + 203))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 516))]));
    compute_local[(22)] = (compute_local[(22)] + (pad_temp_shared[((((int)threadIdx.x) + 203))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 772))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[((((int)threadIdx.x) + 210))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 4))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[((((int)threadIdx.x) + 210))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 260))]));
    compute_local[(16)] = (compute_local[(16)] + (pad_temp_shared[((((int)threadIdx.x) + 210))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 516))]));
    compute_local[(23)] = (compute_local[(23)] + (pad_temp_shared[((((int)threadIdx.x) + 210))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 772))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[((((int)threadIdx.x) + 217))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 4))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[((((int)threadIdx.x) + 217))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 260))]));
    compute_local[(17)] = (compute_local[(17)] + (pad_temp_shared[((((int)threadIdx.x) + 217))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 516))]));
    compute_local[(24)] = (compute_local[(24)] + (pad_temp_shared[((((int)threadIdx.x) + 217))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 772))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[((((int)threadIdx.x) + 224))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 4))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[((((int)threadIdx.x) + 224))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 260))]));
    compute_local[(18)] = (compute_local[(18)] + (pad_temp_shared[((((int)threadIdx.x) + 224))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 516))]));
    compute_local[(25)] = (compute_local[(25)] + (pad_temp_shared[((((int)threadIdx.x) + 224))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 772))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[((((int)threadIdx.x) + 231))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 4))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[((((int)threadIdx.x) + 231))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 260))]));
    compute_local[(19)] = (compute_local[(19)] + (pad_temp_shared[((((int)threadIdx.x) + 231))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 516))]));
    compute_local[(26)] = (compute_local[(26)] + (pad_temp_shared[((((int)threadIdx.x) + 231))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 772))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[((((int)threadIdx.x) + 238))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 4))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[((((int)threadIdx.x) + 238))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 260))]));
    compute_local[(20)] = (compute_local[(20)] + (pad_temp_shared[((((int)threadIdx.x) + 238))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 516))]));
    compute_local[(27)] = (compute_local[(27)] + (pad_temp_shared[((((int)threadIdx.x) + 238))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 772))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[((((int)threadIdx.x) + 245))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 5))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[((((int)threadIdx.x) + 245))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 261))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[((((int)threadIdx.x) + 245))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 517))]));
    compute_local[(21)] = (compute_local[(21)] + (pad_temp_shared[((((int)threadIdx.x) + 245))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 773))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[((((int)threadIdx.x) + 252))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 5))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[((((int)threadIdx.x) + 252))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 261))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[((((int)threadIdx.x) + 252))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 517))]));
    compute_local[(22)] = (compute_local[(22)] + (pad_temp_shared[((((int)threadIdx.x) + 252))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 773))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[((((int)threadIdx.x) + 259))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 5))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[((((int)threadIdx.x) + 259))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 261))]));
    compute_local[(16)] = (compute_local[(16)] + (pad_temp_shared[((((int)threadIdx.x) + 259))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 517))]));
    compute_local[(23)] = (compute_local[(23)] + (pad_temp_shared[((((int)threadIdx.x) + 259))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 773))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[((((int)threadIdx.x) + 266))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 5))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[((((int)threadIdx.x) + 266))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 261))]));
    compute_local[(17)] = (compute_local[(17)] + (pad_temp_shared[((((int)threadIdx.x) + 266))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 517))]));
    compute_local[(24)] = (compute_local[(24)] + (pad_temp_shared[((((int)threadIdx.x) + 266))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 773))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[((((int)threadIdx.x) + 273))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 5))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[((((int)threadIdx.x) + 273))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 261))]));
    compute_local[(18)] = (compute_local[(18)] + (pad_temp_shared[((((int)threadIdx.x) + 273))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 517))]));
    compute_local[(25)] = (compute_local[(25)] + (pad_temp_shared[((((int)threadIdx.x) + 273))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 773))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[((((int)threadIdx.x) + 280))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 5))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[((((int)threadIdx.x) + 280))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 261))]));
    compute_local[(19)] = (compute_local[(19)] + (pad_temp_shared[((((int)threadIdx.x) + 280))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 517))]));
    compute_local[(26)] = (compute_local[(26)] + (pad_temp_shared[((((int)threadIdx.x) + 280))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 773))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[((((int)threadIdx.x) + 287))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 5))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[((((int)threadIdx.x) + 287))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 261))]));
    compute_local[(20)] = (compute_local[(20)] + (pad_temp_shared[((((int)threadIdx.x) + 287))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 517))]));
    compute_local[(27)] = (compute_local[(27)] + (pad_temp_shared[((((int)threadIdx.x) + 287))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 773))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[((((int)threadIdx.x) + 294))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 6))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[((((int)threadIdx.x) + 294))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 262))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[((((int)threadIdx.x) + 294))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 518))]));
    compute_local[(21)] = (compute_local[(21)] + (pad_temp_shared[((((int)threadIdx.x) + 294))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 774))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[((((int)threadIdx.x) + 301))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 6))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[((((int)threadIdx.x) + 301))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 262))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[((((int)threadIdx.x) + 301))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 518))]));
    compute_local[(22)] = (compute_local[(22)] + (pad_temp_shared[((((int)threadIdx.x) + 301))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 774))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[((((int)threadIdx.x) + 308))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 6))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[((((int)threadIdx.x) + 308))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 262))]));
    compute_local[(16)] = (compute_local[(16)] + (pad_temp_shared[((((int)threadIdx.x) + 308))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 518))]));
    compute_local[(23)] = (compute_local[(23)] + (pad_temp_shared[((((int)threadIdx.x) + 308))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 774))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[((((int)threadIdx.x) + 315))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 6))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[((((int)threadIdx.x) + 315))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 262))]));
    compute_local[(17)] = (compute_local[(17)] + (pad_temp_shared[((((int)threadIdx.x) + 315))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 518))]));
    compute_local[(24)] = (compute_local[(24)] + (pad_temp_shared[((((int)threadIdx.x) + 315))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 774))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[((((int)threadIdx.x) + 322))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 6))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[((((int)threadIdx.x) + 322))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 262))]));
    compute_local[(18)] = (compute_local[(18)] + (pad_temp_shared[((((int)threadIdx.x) + 322))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 518))]));
    compute_local[(25)] = (compute_local[(25)] + (pad_temp_shared[((((int)threadIdx.x) + 322))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 774))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[((((int)threadIdx.x) + 329))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 6))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[((((int)threadIdx.x) + 329))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 262))]));
    compute_local[(19)] = (compute_local[(19)] + (pad_temp_shared[((((int)threadIdx.x) + 329))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 518))]));
    compute_local[(26)] = (compute_local[(26)] + (pad_temp_shared[((((int)threadIdx.x) + 329))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 774))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[((((int)threadIdx.x) + 336))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 6))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[((((int)threadIdx.x) + 336))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 262))]));
    compute_local[(20)] = (compute_local[(20)] + (pad_temp_shared[((((int)threadIdx.x) + 336))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 518))]));
    compute_local[(27)] = (compute_local[(27)] + (pad_temp_shared[((((int)threadIdx.x) + 336))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 774))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[((((int)threadIdx.x) + 343))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 7))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[((((int)threadIdx.x) + 343))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 263))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[((((int)threadIdx.x) + 343))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 519))]));
    compute_local[(21)] = (compute_local[(21)] + (pad_temp_shared[((((int)threadIdx.x) + 343))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 775))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[((((int)threadIdx.x) + 350))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 7))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[((((int)threadIdx.x) + 350))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 263))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[((((int)threadIdx.x) + 350))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 519))]));
    compute_local[(22)] = (compute_local[(22)] + (pad_temp_shared[((((int)threadIdx.x) + 350))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 775))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[((((int)threadIdx.x) + 357))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 7))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[((((int)threadIdx.x) + 357))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 263))]));
    compute_local[(16)] = (compute_local[(16)] + (pad_temp_shared[((((int)threadIdx.x) + 357))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 519))]));
    compute_local[(23)] = (compute_local[(23)] + (pad_temp_shared[((((int)threadIdx.x) + 357))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 775))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[((((int)threadIdx.x) + 364))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 7))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[((((int)threadIdx.x) + 364))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 263))]));
    compute_local[(17)] = (compute_local[(17)] + (pad_temp_shared[((((int)threadIdx.x) + 364))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 519))]));
    compute_local[(24)] = (compute_local[(24)] + (pad_temp_shared[((((int)threadIdx.x) + 364))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 775))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[((((int)threadIdx.x) + 371))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 7))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[((((int)threadIdx.x) + 371))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 263))]));
    compute_local[(18)] = (compute_local[(18)] + (pad_temp_shared[((((int)threadIdx.x) + 371))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 519))]));
    compute_local[(25)] = (compute_local[(25)] + (pad_temp_shared[((((int)threadIdx.x) + 371))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 775))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[((((int)threadIdx.x) + 378))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 7))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[((((int)threadIdx.x) + 378))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 263))]));
    compute_local[(19)] = (compute_local[(19)] + (pad_temp_shared[((((int)threadIdx.x) + 378))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 519))]));
    compute_local[(26)] = (compute_local[(26)] + (pad_temp_shared[((((int)threadIdx.x) + 378))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 775))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[((((int)threadIdx.x) + 385))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 7))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[((((int)threadIdx.x) + 385))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 263))]));
    compute_local[(20)] = (compute_local[(20)] + (pad_temp_shared[((((int)threadIdx.x) + 385))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 519))]));
    compute_local[(27)] = (compute_local[(27)] + (pad_temp_shared[((((int)threadIdx.x) + 385))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 775))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[((((int)threadIdx.x) + 392))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 8))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[((((int)threadIdx.x) + 392))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 264))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[((((int)threadIdx.x) + 392))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 520))]));
    compute_local[(21)] = (compute_local[(21)] + (pad_temp_shared[((((int)threadIdx.x) + 392))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 776))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[((((int)threadIdx.x) + 399))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 8))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[((((int)threadIdx.x) + 399))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 264))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[((((int)threadIdx.x) + 399))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 520))]));
    compute_local[(22)] = (compute_local[(22)] + (pad_temp_shared[((((int)threadIdx.x) + 399))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 776))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[((((int)threadIdx.x) + 406))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 8))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[((((int)threadIdx.x) + 406))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 264))]));
    compute_local[(16)] = (compute_local[(16)] + (pad_temp_shared[((((int)threadIdx.x) + 406))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 520))]));
    compute_local[(23)] = (compute_local[(23)] + (pad_temp_shared[((((int)threadIdx.x) + 406))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 776))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[((((int)threadIdx.x) + 413))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 8))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[((((int)threadIdx.x) + 413))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 264))]));
    compute_local[(17)] = (compute_local[(17)] + (pad_temp_shared[((((int)threadIdx.x) + 413))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 520))]));
    compute_local[(24)] = (compute_local[(24)] + (pad_temp_shared[((((int)threadIdx.x) + 413))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 776))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[((((int)threadIdx.x) + 420))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 8))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[((((int)threadIdx.x) + 420))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 264))]));
    compute_local[(18)] = (compute_local[(18)] + (pad_temp_shared[((((int)threadIdx.x) + 420))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 520))]));
    compute_local[(25)] = (compute_local[(25)] + (pad_temp_shared[((((int)threadIdx.x) + 420))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 776))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[((((int)threadIdx.x) + 427))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 8))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[((((int)threadIdx.x) + 427))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 264))]));
    compute_local[(19)] = (compute_local[(19)] + (pad_temp_shared[((((int)threadIdx.x) + 427))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 520))]));
    compute_local[(26)] = (compute_local[(26)] + (pad_temp_shared[((((int)threadIdx.x) + 427))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 776))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[((((int)threadIdx.x) + 434))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 8))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[((((int)threadIdx.x) + 434))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 264))]));
    compute_local[(20)] = (compute_local[(20)] + (pad_temp_shared[((((int)threadIdx.x) + 434))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 520))]));
    compute_local[(27)] = (compute_local[(27)] + (pad_temp_shared[((((int)threadIdx.x) + 434))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 776))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[((((int)threadIdx.x) + 441))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 9))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[((((int)threadIdx.x) + 441))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 265))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[((((int)threadIdx.x) + 441))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 521))]));
    compute_local[(21)] = (compute_local[(21)] + (pad_temp_shared[((((int)threadIdx.x) + 441))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 777))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[((((int)threadIdx.x) + 448))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 9))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[((((int)threadIdx.x) + 448))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 265))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[((((int)threadIdx.x) + 448))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 521))]));
    compute_local[(22)] = (compute_local[(22)] + (pad_temp_shared[((((int)threadIdx.x) + 448))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 777))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[((((int)threadIdx.x) + 455))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 9))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[((((int)threadIdx.x) + 455))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 265))]));
    compute_local[(16)] = (compute_local[(16)] + (pad_temp_shared[((((int)threadIdx.x) + 455))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 521))]));
    compute_local[(23)] = (compute_local[(23)] + (pad_temp_shared[((((int)threadIdx.x) + 455))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 777))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[((((int)threadIdx.x) + 462))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 9))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[((((int)threadIdx.x) + 462))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 265))]));
    compute_local[(17)] = (compute_local[(17)] + (pad_temp_shared[((((int)threadIdx.x) + 462))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 521))]));
    compute_local[(24)] = (compute_local[(24)] + (pad_temp_shared[((((int)threadIdx.x) + 462))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 777))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[((((int)threadIdx.x) + 469))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 9))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[((((int)threadIdx.x) + 469))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 265))]));
    compute_local[(18)] = (compute_local[(18)] + (pad_temp_shared[((((int)threadIdx.x) + 469))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 521))]));
    compute_local[(25)] = (compute_local[(25)] + (pad_temp_shared[((((int)threadIdx.x) + 469))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 777))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[((((int)threadIdx.x) + 476))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 9))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[((((int)threadIdx.x) + 476))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 265))]));
    compute_local[(19)] = (compute_local[(19)] + (pad_temp_shared[((((int)threadIdx.x) + 476))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 521))]));
    compute_local[(26)] = (compute_local[(26)] + (pad_temp_shared[((((int)threadIdx.x) + 476))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 777))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[((((int)threadIdx.x) + 483))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 9))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[((((int)threadIdx.x) + 483))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 265))]));
    compute_local[(20)] = (compute_local[(20)] + (pad_temp_shared[((((int)threadIdx.x) + 483))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 521))]));
    compute_local[(27)] = (compute_local[(27)] + (pad_temp_shared[((((int)threadIdx.x) + 483))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 777))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[((((int)threadIdx.x) + 490))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 10))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[((((int)threadIdx.x) + 490))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 266))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[((((int)threadIdx.x) + 490))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 522))]));
    compute_local[(21)] = (compute_local[(21)] + (pad_temp_shared[((((int)threadIdx.x) + 490))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 778))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[((((int)threadIdx.x) + 497))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 10))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[((((int)threadIdx.x) + 497))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 266))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[((((int)threadIdx.x) + 497))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 522))]));
    compute_local[(22)] = (compute_local[(22)] + (pad_temp_shared[((((int)threadIdx.x) + 497))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 778))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[((((int)threadIdx.x) + 504))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 10))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[((((int)threadIdx.x) + 504))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 266))]));
    compute_local[(16)] = (compute_local[(16)] + (pad_temp_shared[((((int)threadIdx.x) + 504))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 522))]));
    compute_local[(23)] = (compute_local[(23)] + (pad_temp_shared[((((int)threadIdx.x) + 504))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 778))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[((((int)threadIdx.x) + 511))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 10))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[((((int)threadIdx.x) + 511))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 266))]));
    compute_local[(17)] = (compute_local[(17)] + (pad_temp_shared[((((int)threadIdx.x) + 511))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 522))]));
    compute_local[(24)] = (compute_local[(24)] + (pad_temp_shared[((((int)threadIdx.x) + 511))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 778))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[((((int)threadIdx.x) + 518))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 10))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[((((int)threadIdx.x) + 518))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 266))]));
    compute_local[(18)] = (compute_local[(18)] + (pad_temp_shared[((((int)threadIdx.x) + 518))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 522))]));
    compute_local[(25)] = (compute_local[(25)] + (pad_temp_shared[((((int)threadIdx.x) + 518))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 778))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[((((int)threadIdx.x) + 525))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 10))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[((((int)threadIdx.x) + 525))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 266))]));
    compute_local[(19)] = (compute_local[(19)] + (pad_temp_shared[((((int)threadIdx.x) + 525))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 522))]));
    compute_local[(26)] = (compute_local[(26)] + (pad_temp_shared[((((int)threadIdx.x) + 525))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 778))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[((((int)threadIdx.x) + 532))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 10))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[((((int)threadIdx.x) + 532))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 266))]));
    compute_local[(20)] = (compute_local[(20)] + (pad_temp_shared[((((int)threadIdx.x) + 532))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 522))]));
    compute_local[(27)] = (compute_local[(27)] + (pad_temp_shared[((((int)threadIdx.x) + 532))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 778))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[((((int)threadIdx.x) + 539))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 11))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[((((int)threadIdx.x) + 539))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 267))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[((((int)threadIdx.x) + 539))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 523))]));
    compute_local[(21)] = (compute_local[(21)] + (pad_temp_shared[((((int)threadIdx.x) + 539))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 779))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[((((int)threadIdx.x) + 546))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 11))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[((((int)threadIdx.x) + 546))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 267))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[((((int)threadIdx.x) + 546))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 523))]));
    compute_local[(22)] = (compute_local[(22)] + (pad_temp_shared[((((int)threadIdx.x) + 546))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 779))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[((((int)threadIdx.x) + 553))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 11))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[((((int)threadIdx.x) + 553))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 267))]));
    compute_local[(16)] = (compute_local[(16)] + (pad_temp_shared[((((int)threadIdx.x) + 553))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 523))]));
    compute_local[(23)] = (compute_local[(23)] + (pad_temp_shared[((((int)threadIdx.x) + 553))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 779))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[((((int)threadIdx.x) + 560))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 11))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[((((int)threadIdx.x) + 560))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 267))]));
    compute_local[(17)] = (compute_local[(17)] + (pad_temp_shared[((((int)threadIdx.x) + 560))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 523))]));
    compute_local[(24)] = (compute_local[(24)] + (pad_temp_shared[((((int)threadIdx.x) + 560))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 779))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[((((int)threadIdx.x) + 567))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 11))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[((((int)threadIdx.x) + 567))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 267))]));
    compute_local[(18)] = (compute_local[(18)] + (pad_temp_shared[((((int)threadIdx.x) + 567))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 523))]));
    compute_local[(25)] = (compute_local[(25)] + (pad_temp_shared[((((int)threadIdx.x) + 567))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 779))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[((((int)threadIdx.x) + 574))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 11))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[((((int)threadIdx.x) + 574))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 267))]));
    compute_local[(19)] = (compute_local[(19)] + (pad_temp_shared[((((int)threadIdx.x) + 574))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 523))]));
    compute_local[(26)] = (compute_local[(26)] + (pad_temp_shared[((((int)threadIdx.x) + 574))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 779))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[((((int)threadIdx.x) + 581))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 11))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[((((int)threadIdx.x) + 581))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 267))]));
    compute_local[(20)] = (compute_local[(20)] + (pad_temp_shared[((((int)threadIdx.x) + 581))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 523))]));
    compute_local[(27)] = (compute_local[(27)] + (pad_temp_shared[((((int)threadIdx.x) + 581))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 779))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[((((int)threadIdx.x) + 588))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 12))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[((((int)threadIdx.x) + 588))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 268))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[((((int)threadIdx.x) + 588))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 524))]));
    compute_local[(21)] = (compute_local[(21)] + (pad_temp_shared[((((int)threadIdx.x) + 588))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 780))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[((((int)threadIdx.x) + 595))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 12))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[((((int)threadIdx.x) + 595))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 268))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[((((int)threadIdx.x) + 595))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 524))]));
    compute_local[(22)] = (compute_local[(22)] + (pad_temp_shared[((((int)threadIdx.x) + 595))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 780))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[((((int)threadIdx.x) + 602))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 12))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[((((int)threadIdx.x) + 602))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 268))]));
    compute_local[(16)] = (compute_local[(16)] + (pad_temp_shared[((((int)threadIdx.x) + 602))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 524))]));
    compute_local[(23)] = (compute_local[(23)] + (pad_temp_shared[((((int)threadIdx.x) + 602))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 780))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[((((int)threadIdx.x) + 609))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 12))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[((((int)threadIdx.x) + 609))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 268))]));
    compute_local[(17)] = (compute_local[(17)] + (pad_temp_shared[((((int)threadIdx.x) + 609))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 524))]));
    compute_local[(24)] = (compute_local[(24)] + (pad_temp_shared[((((int)threadIdx.x) + 609))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 780))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[((((int)threadIdx.x) + 616))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 12))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[((((int)threadIdx.x) + 616))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 268))]));
    compute_local[(18)] = (compute_local[(18)] + (pad_temp_shared[((((int)threadIdx.x) + 616))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 524))]));
    compute_local[(25)] = (compute_local[(25)] + (pad_temp_shared[((((int)threadIdx.x) + 616))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 780))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[((((int)threadIdx.x) + 623))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 12))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[((((int)threadIdx.x) + 623))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 268))]));
    compute_local[(19)] = (compute_local[(19)] + (pad_temp_shared[((((int)threadIdx.x) + 623))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 524))]));
    compute_local[(26)] = (compute_local[(26)] + (pad_temp_shared[((((int)threadIdx.x) + 623))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 780))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[((((int)threadIdx.x) + 630))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 12))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[((((int)threadIdx.x) + 630))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 268))]));
    compute_local[(20)] = (compute_local[(20)] + (pad_temp_shared[((((int)threadIdx.x) + 630))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 524))]));
    compute_local[(27)] = (compute_local[(27)] + (pad_temp_shared[((((int)threadIdx.x) + 630))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 780))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[((((int)threadIdx.x) + 637))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 13))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[((((int)threadIdx.x) + 637))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 269))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[((((int)threadIdx.x) + 637))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 525))]));
    compute_local[(21)] = (compute_local[(21)] + (pad_temp_shared[((((int)threadIdx.x) + 637))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 781))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[((((int)threadIdx.x) + 644))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 13))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[((((int)threadIdx.x) + 644))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 269))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[((((int)threadIdx.x) + 644))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 525))]));
    compute_local[(22)] = (compute_local[(22)] + (pad_temp_shared[((((int)threadIdx.x) + 644))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 781))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[((((int)threadIdx.x) + 651))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 13))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[((((int)threadIdx.x) + 651))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 269))]));
    compute_local[(16)] = (compute_local[(16)] + (pad_temp_shared[((((int)threadIdx.x) + 651))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 525))]));
    compute_local[(23)] = (compute_local[(23)] + (pad_temp_shared[((((int)threadIdx.x) + 651))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 781))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[((((int)threadIdx.x) + 658))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 13))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[((((int)threadIdx.x) + 658))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 269))]));
    compute_local[(17)] = (compute_local[(17)] + (pad_temp_shared[((((int)threadIdx.x) + 658))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 525))]));
    compute_local[(24)] = (compute_local[(24)] + (pad_temp_shared[((((int)threadIdx.x) + 658))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 781))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[((((int)threadIdx.x) + 665))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 13))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[((((int)threadIdx.x) + 665))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 269))]));
    compute_local[(18)] = (compute_local[(18)] + (pad_temp_shared[((((int)threadIdx.x) + 665))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 525))]));
    compute_local[(25)] = (compute_local[(25)] + (pad_temp_shared[((((int)threadIdx.x) + 665))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 781))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[((((int)threadIdx.x) + 672))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 13))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[((((int)threadIdx.x) + 672))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 269))]));
    compute_local[(19)] = (compute_local[(19)] + (pad_temp_shared[((((int)threadIdx.x) + 672))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 525))]));
    compute_local[(26)] = (compute_local[(26)] + (pad_temp_shared[((((int)threadIdx.x) + 672))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 781))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[((((int)threadIdx.x) + 679))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 13))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[((((int)threadIdx.x) + 679))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 269))]));
    compute_local[(20)] = (compute_local[(20)] + (pad_temp_shared[((((int)threadIdx.x) + 679))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 525))]));
    compute_local[(27)] = (compute_local[(27)] + (pad_temp_shared[((((int)threadIdx.x) + 679))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 781))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[((((int)threadIdx.x) + 686))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 14))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[((((int)threadIdx.x) + 686))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 270))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[((((int)threadIdx.x) + 686))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 526))]));
    compute_local[(21)] = (compute_local[(21)] + (pad_temp_shared[((((int)threadIdx.x) + 686))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 782))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[((((int)threadIdx.x) + 693))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 14))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[((((int)threadIdx.x) + 693))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 270))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[((((int)threadIdx.x) + 693))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 526))]));
    compute_local[(22)] = (compute_local[(22)] + (pad_temp_shared[((((int)threadIdx.x) + 693))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 782))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[((((int)threadIdx.x) + 700))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 14))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[((((int)threadIdx.x) + 700))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 270))]));
    compute_local[(16)] = (compute_local[(16)] + (pad_temp_shared[((((int)threadIdx.x) + 700))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 526))]));
    compute_local[(23)] = (compute_local[(23)] + (pad_temp_shared[((((int)threadIdx.x) + 700))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 782))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[((((int)threadIdx.x) + 707))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 14))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[((((int)threadIdx.x) + 707))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 270))]));
    compute_local[(17)] = (compute_local[(17)] + (pad_temp_shared[((((int)threadIdx.x) + 707))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 526))]));
    compute_local[(24)] = (compute_local[(24)] + (pad_temp_shared[((((int)threadIdx.x) + 707))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 782))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[((((int)threadIdx.x) + 714))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 14))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[((((int)threadIdx.x) + 714))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 270))]));
    compute_local[(18)] = (compute_local[(18)] + (pad_temp_shared[((((int)threadIdx.x) + 714))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 526))]));
    compute_local[(25)] = (compute_local[(25)] + (pad_temp_shared[((((int)threadIdx.x) + 714))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 782))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[((((int)threadIdx.x) + 721))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 14))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[((((int)threadIdx.x) + 721))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 270))]));
    compute_local[(19)] = (compute_local[(19)] + (pad_temp_shared[((((int)threadIdx.x) + 721))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 526))]));
    compute_local[(26)] = (compute_local[(26)] + (pad_temp_shared[((((int)threadIdx.x) + 721))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 782))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[((((int)threadIdx.x) + 728))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 14))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[((((int)threadIdx.x) + 728))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 270))]));
    compute_local[(20)] = (compute_local[(20)] + (pad_temp_shared[((((int)threadIdx.x) + 728))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 526))]));
    compute_local[(27)] = (compute_local[(27)] + (pad_temp_shared[((((int)threadIdx.x) + 728))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 782))]));
    compute_local[(0)] = (compute_local[(0)] + (pad_temp_shared[((((int)threadIdx.x) + 735))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 15))]));
    compute_local[(7)] = (compute_local[(7)] + (pad_temp_shared[((((int)threadIdx.x) + 735))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 271))]));
    compute_local[(14)] = (compute_local[(14)] + (pad_temp_shared[((((int)threadIdx.x) + 735))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 527))]));
    compute_local[(21)] = (compute_local[(21)] + (pad_temp_shared[((((int)threadIdx.x) + 735))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 783))]));
    compute_local[(1)] = (compute_local[(1)] + (pad_temp_shared[((((int)threadIdx.x) + 742))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 15))]));
    compute_local[(8)] = (compute_local[(8)] + (pad_temp_shared[((((int)threadIdx.x) + 742))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 271))]));
    compute_local[(15)] = (compute_local[(15)] + (pad_temp_shared[((((int)threadIdx.x) + 742))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 527))]));
    compute_local[(22)] = (compute_local[(22)] + (pad_temp_shared[((((int)threadIdx.x) + 742))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 783))]));
    compute_local[(2)] = (compute_local[(2)] + (pad_temp_shared[((((int)threadIdx.x) + 749))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 15))]));
    compute_local[(9)] = (compute_local[(9)] + (pad_temp_shared[((((int)threadIdx.x) + 749))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 271))]));
    compute_local[(16)] = (compute_local[(16)] + (pad_temp_shared[((((int)threadIdx.x) + 749))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 527))]));
    compute_local[(23)] = (compute_local[(23)] + (pad_temp_shared[((((int)threadIdx.x) + 749))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 783))]));
    compute_local[(3)] = (compute_local[(3)] + (pad_temp_shared[((((int)threadIdx.x) + 756))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 15))]));
    compute_local[(10)] = (compute_local[(10)] + (pad_temp_shared[((((int)threadIdx.x) + 756))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 271))]));
    compute_local[(17)] = (compute_local[(17)] + (pad_temp_shared[((((int)threadIdx.x) + 756))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 527))]));
    compute_local[(24)] = (compute_local[(24)] + (pad_temp_shared[((((int)threadIdx.x) + 756))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 783))]));
    compute_local[(4)] = (compute_local[(4)] + (pad_temp_shared[((((int)threadIdx.x) + 763))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 15))]));
    compute_local[(11)] = (compute_local[(11)] + (pad_temp_shared[((((int)threadIdx.x) + 763))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 271))]));
    compute_local[(18)] = (compute_local[(18)] + (pad_temp_shared[((((int)threadIdx.x) + 763))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 527))]));
    compute_local[(25)] = (compute_local[(25)] + (pad_temp_shared[((((int)threadIdx.x) + 763))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 783))]));
    compute_local[(5)] = (compute_local[(5)] + (pad_temp_shared[((((int)threadIdx.x) + 770))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 15))]));
    compute_local[(12)] = (compute_local[(12)] + (pad_temp_shared[((((int)threadIdx.x) + 770))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 271))]));
    compute_local[(19)] = (compute_local[(19)] + (pad_temp_shared[((((int)threadIdx.x) + 770))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 527))]));
    compute_local[(26)] = (compute_local[(26)] + (pad_temp_shared[((((int)threadIdx.x) + 770))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 783))]));
    compute_local[(6)] = (compute_local[(6)] + (pad_temp_shared[((((int)threadIdx.x) + 777))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 15))]));
    compute_local[(13)] = (compute_local[(13)] + (pad_temp_shared[((((int)threadIdx.x) + 777))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 271))]));
    compute_local[(20)] = (compute_local[(20)] + (pad_temp_shared[((((int)threadIdx.x) + 777))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 527))]));
    compute_local[(27)] = (compute_local[(27)] + (pad_temp_shared[((((int)threadIdx.x) + 777))] * placeholder_shared[(((((int)threadIdx.z) * 16) + 783))]));
  }
  compute[((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)))] = compute_local[(0)];
  compute[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 784))] = compute_local[(7)];
  compute[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 1568))] = compute_local[(14)];
  compute[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 2352))] = compute_local[(21)];
  compute[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 7))] = compute_local[(1)];
  compute[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 791))] = compute_local[(8)];
  compute[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 1575))] = compute_local[(15)];
  compute[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 2359))] = compute_local[(22)];
  compute[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 14))] = compute_local[(2)];
  compute[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 798))] = compute_local[(9)];
  compute[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 1582))] = compute_local[(16)];
  compute[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 2366))] = compute_local[(23)];
  compute[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 21))] = compute_local[(3)];
  compute[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 805))] = compute_local[(10)];
  compute[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 1589))] = compute_local[(17)];
  compute[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 2373))] = compute_local[(24)];
  compute[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 28))] = compute_local[(4)];
  compute[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 812))] = compute_local[(11)];
  compute[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 1596))] = compute_local[(18)];
  compute[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 2380))] = compute_local[(25)];
  compute[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 35))] = compute_local[(5)];
  compute[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 819))] = compute_local[(12)];
  compute[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 1603))] = compute_local[(19)];
  compute[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 2387))] = compute_local[(26)];
  compute[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 42))] = compute_local[(6)];
  compute[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 826))] = compute_local[(13)];
  compute[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 1610))] = compute_local[(20)];
  compute[(((((((int)blockIdx.z) * 3136) + (((int)threadIdx.z) * 49)) + ((int)threadIdx.x)) + 2394))] = compute_local[(27)];
}

