//2_7_10752_21_1_1
//128_84_83_83_5_2_SAME
//dim3 grid(2, 7, 10752);
//dim3 block(21, 1, 1);

#ifdef _WIN32
  using uint = unsigned int;
  using uchar = unsigned char;
  using ushort = unsigned short;
  using int64_t = long long;
  using uint64_t = unsigned long long;
#else
  #define uint unsigned int
  #define uchar unsigned char
  #define ushort unsigned short
  #define int64_t long long
  #define uint64_t unsigned long long
#endif
extern "C" __global__ void __launch_bounds__(21) depthwise_kernel0(float* __restrict__ placeholder, float* __restrict__ placeholder1, float* __restrict__ DepthwiseConv2d) {
  __shared__ float PaddedInput_shared[675];
  __shared__ float placeholder_shared[25];
  float PaddedInput_shared_local[75];
  float placeholder_shared_local[25];
  float DepthwiseConv2d_local[6];
  PaddedInput_shared[(((int)threadIdx.x))] = (((1 <= ((int)blockIdx.y)) && (2 <= ((((int)blockIdx.x) * 42) + ((int)threadIdx.x)))) ? placeholder[((((((((int)blockIdx.z) * 6889) + (((int)blockIdx.y) * 996)) + (((int)blockIdx.x) * 42)) + ((int)threadIdx.x)) - 168))] : 0.000000e+00f);
  PaddedInput_shared[((((int)threadIdx.x) + 21))] = ((1 <= ((int)blockIdx.y)) ? placeholder[((((((((int)blockIdx.z) * 6889) + (((int)blockIdx.y) * 996)) + (((int)blockIdx.x) * 42)) + ((int)threadIdx.x)) - 147))] : 0.000000e+00f);
  PaddedInput_shared[((((int)threadIdx.x) + 42))] = ((((2 <= ((((int)blockIdx.y) * 12) + ((((int)threadIdx.x) + 42) / 45))) && (2 <= ((((int)blockIdx.x) * 42) + ((((int)threadIdx.x) + 42) % 45)))) && (((((int)blockIdx.x) * 42) + ((((int)threadIdx.x) + 42) % 45)) < 85)) ? placeholder[(((((((((int)blockIdx.z) * 6889) + (((int)blockIdx.y) * 996)) + (((((int)threadIdx.x) + 42) / 45) * 83)) + (((int)blockIdx.x) * 42)) + ((((int)threadIdx.x) + 42) % 45)) - 168))] : 0.000000e+00f);
  PaddedInput_shared[((((int)threadIdx.x) + 63))] = ((2 <= ((((int)blockIdx.y) * 12) + ((((int)threadIdx.x) + 63) / 45))) ? placeholder[(((((((((int)blockIdx.z) * 6889) + (((int)blockIdx.y) * 996)) + (((((int)threadIdx.x) + 63) / 45) * 83)) + (((int)blockIdx.x) * 42)) + (((int)threadIdx.x) + 18)) - 168))] : 0.000000e+00f);
  PaddedInput_shared[((((int)threadIdx.x) + 84))] = ((((2 <= ((((int)blockIdx.y) * 12) + ((((int)threadIdx.x) + 84) / 45))) && (2 <= ((((int)blockIdx.x) * 42) + ((((int)threadIdx.x) + 39) % 45)))) && (((((int)blockIdx.x) * 42) + ((((int)threadIdx.x) + 39) % 45)) < 85)) ? placeholder[(((((((((int)blockIdx.z) * 6889) + (((int)blockIdx.y) * 996)) + (((((int)threadIdx.x) + 84) / 45) * 83)) + (((int)blockIdx.x) * 42)) + ((((int)threadIdx.x) + 39) % 45)) - 168))] : 0.000000e+00f);
  PaddedInput_shared[((((int)threadIdx.x) + 105))] = placeholder[(((((((((int)blockIdx.z) * 6889) + (((int)blockIdx.y) * 996)) + (((((int)threadIdx.x) + 105) / 45) * 83)) + (((int)blockIdx.x) * 42)) + (((int)threadIdx.x) + 15)) - 168))];
  PaddedInput_shared[((((int)threadIdx.x) + 126))] = (((2 <= ((((int)blockIdx.x) * 42) + ((((int)threadIdx.x) + 36) % 45))) && (((((int)blockIdx.x) * 42) + ((((int)threadIdx.x) + 36) % 45)) < 85)) ? placeholder[(((((((((int)blockIdx.z) * 6889) + (((int)blockIdx.y) * 996)) + (((((int)threadIdx.x) + 126) / 45) * 83)) + (((int)blockIdx.x) * 42)) + ((((int)threadIdx.x) + 36) % 45)) - 168))] : 0.000000e+00f);
  PaddedInput_shared[((((int)threadIdx.x) + 147))] = placeholder[(((((((((int)blockIdx.z) * 6889) + (((int)blockIdx.y) * 996)) + (((((int)threadIdx.x) + 147) / 45) * 83)) + (((int)blockIdx.x) * 42)) + (((int)threadIdx.x) + 12)) - 168))];
  PaddedInput_shared[((((int)threadIdx.x) + 168))] = (((2 <= ((((int)blockIdx.x) * 42) + ((((int)threadIdx.x) + 33) % 45))) && (((((int)blockIdx.x) * 42) + ((((int)threadIdx.x) + 33) % 45)) < 85)) ? placeholder[(((((((((int)blockIdx.z) * 6889) + (((int)blockIdx.y) * 996)) + (((((int)threadIdx.x) + 168) / 45) * 83)) + (((int)blockIdx.x) * 42)) + ((((int)threadIdx.x) + 33) % 45)) - 168))] : 0.000000e+00f);
  PaddedInput_shared[((((int)threadIdx.x) + 189))] = placeholder[(((((((((int)blockIdx.z) * 6889) + (((int)blockIdx.y) * 996)) + (((((int)threadIdx.x) + 189) / 45) * 83)) + (((int)blockIdx.x) * 42)) + (((int)threadIdx.x) + 9)) - 168))];
  PaddedInput_shared[((((int)threadIdx.x) + 210))] = (((2 <= ((((int)blockIdx.x) * 42) + ((((int)threadIdx.x) + 30) % 45))) && (((((int)blockIdx.x) * 42) + ((((int)threadIdx.x) + 30) % 45)) < 85)) ? placeholder[(((((((((int)blockIdx.z) * 6889) + (((int)blockIdx.y) * 996)) + (((((int)threadIdx.x) + 210) / 45) * 83)) + (((int)blockIdx.x) * 42)) + ((((int)threadIdx.x) + 30) % 45)) - 168))] : 0.000000e+00f);
  PaddedInput_shared[((((int)threadIdx.x) + 231))] = placeholder[(((((((((int)blockIdx.z) * 6889) + (((int)blockIdx.y) * 996)) + (((((int)threadIdx.x) + 231) / 45) * 83)) + (((int)blockIdx.x) * 42)) + (((int)threadIdx.x) + 6)) - 168))];
  PaddedInput_shared[((((int)threadIdx.x) + 252))] = (((2 <= ((((int)blockIdx.x) * 42) + ((((int)threadIdx.x) + 27) % 45))) && (((((int)blockIdx.x) * 42) + ((((int)threadIdx.x) + 27) % 45)) < 85)) ? placeholder[(((((((((int)blockIdx.z) * 6889) + (((int)blockIdx.y) * 996)) + (((((int)threadIdx.x) + 252) / 45) * 83)) + (((int)blockIdx.x) * 42)) + ((((int)threadIdx.x) + 27) % 45)) - 168))] : 0.000000e+00f);
  PaddedInput_shared[((((int)threadIdx.x) + 273))] = placeholder[(((((((((int)blockIdx.z) * 6889) + (((int)blockIdx.y) * 996)) + (((((int)threadIdx.x) + 273) / 45) * 83)) + (((int)blockIdx.x) * 42)) + (((int)threadIdx.x) + 3)) - 168))];
  PaddedInput_shared[((((int)threadIdx.x) + 294))] = ((((((int)blockIdx.x) * 42) + (((int)threadIdx.x) + 24)) < 85) ? placeholder[(((((((((int)blockIdx.z) * 6889) + (((int)blockIdx.y) * 996)) + (((((int)threadIdx.x) + 294) / 45) * 83)) + (((int)blockIdx.x) * 42)) + (((int)threadIdx.x) + 24)) - 168))] : 0.000000e+00f);
  PaddedInput_shared[((((int)threadIdx.x) + 315))] = ((2 <= ((((int)blockIdx.x) * 42) + ((int)threadIdx.x))) ? placeholder[((((((((int)blockIdx.z) * 6889) + (((int)blockIdx.y) * 996)) + (((int)blockIdx.x) * 42)) + ((int)threadIdx.x)) + 413))] : 0.000000e+00f);
  PaddedInput_shared[((((int)threadIdx.x) + 336))] = placeholder[(((((((((int)blockIdx.z) * 6889) + (((int)blockIdx.y) * 996)) + (((((int)threadIdx.x) + 336) / 45) * 83)) + (((int)blockIdx.x) * 42)) + (((int)threadIdx.x) + 21)) - 168))];
  PaddedInput_shared[((((int)threadIdx.x) + 357))] = (((2 <= ((((int)blockIdx.x) * 42) + ((((int)threadIdx.x) + 42) % 45))) && (((((int)blockIdx.x) * 42) + ((((int)threadIdx.x) + 42) % 45)) < 85)) ? placeholder[(((((((((int)blockIdx.z) * 6889) + (((int)blockIdx.y) * 996)) + (((((int)threadIdx.x) + 357) / 45) * 83)) + (((int)blockIdx.x) * 42)) + ((((int)threadIdx.x) + 42) % 45)) - 168))] : 0.000000e+00f);
  PaddedInput_shared[((((int)threadIdx.x) + 378))] = placeholder[(((((((((int)blockIdx.z) * 6889) + (((int)blockIdx.y) * 996)) + (((((int)threadIdx.x) + 378) / 45) * 83)) + (((int)blockIdx.x) * 42)) + (((int)threadIdx.x) + 18)) - 168))];
  PaddedInput_shared[((((int)threadIdx.x) + 399))] = (((2 <= ((((int)blockIdx.x) * 42) + ((((int)threadIdx.x) + 39) % 45))) && (((((int)blockIdx.x) * 42) + ((((int)threadIdx.x) + 39) % 45)) < 85)) ? placeholder[(((((((((int)blockIdx.z) * 6889) + (((int)blockIdx.y) * 996)) + (((((int)threadIdx.x) + 399) / 45) * 83)) + (((int)blockIdx.x) * 42)) + ((((int)threadIdx.x) + 39) % 45)) - 168))] : 0.000000e+00f);
  PaddedInput_shared[((((int)threadIdx.x) + 420))] = placeholder[(((((((((int)blockIdx.z) * 6889) + (((int)blockIdx.y) * 996)) + (((((int)threadIdx.x) + 420) / 45) * 83)) + (((int)blockIdx.x) * 42)) + (((int)threadIdx.x) + 15)) - 168))];
  PaddedInput_shared[((((int)threadIdx.x) + 441))] = (((2 <= ((((int)blockIdx.x) * 42) + ((((int)threadIdx.x) + 36) % 45))) && (((((int)blockIdx.x) * 42) + ((((int)threadIdx.x) + 36) % 45)) < 85)) ? placeholder[(((((((((int)blockIdx.z) * 6889) + (((int)blockIdx.y) * 996)) + (((((int)threadIdx.x) + 441) / 45) * 83)) + (((int)blockIdx.x) * 42)) + ((((int)threadIdx.x) + 36) % 45)) - 168))] : 0.000000e+00f);
  PaddedInput_shared[((((int)threadIdx.x) + 462))] = placeholder[(((((((((int)blockIdx.z) * 6889) + (((int)blockIdx.y) * 996)) + (((((int)threadIdx.x) + 462) / 45) * 83)) + (((int)blockIdx.x) * 42)) + (((int)threadIdx.x) + 12)) - 168))];
  PaddedInput_shared[((((int)threadIdx.x) + 483))] = (((2 <= ((((int)blockIdx.x) * 42) + ((((int)threadIdx.x) + 33) % 45))) && (((((int)blockIdx.x) * 42) + ((((int)threadIdx.x) + 33) % 45)) < 85)) ? placeholder[(((((((((int)blockIdx.z) * 6889) + (((int)blockIdx.y) * 996)) + (((((int)threadIdx.x) + 483) / 45) * 83)) + (((int)blockIdx.x) * 42)) + ((((int)threadIdx.x) + 33) % 45)) - 168))] : 0.000000e+00f);
  PaddedInput_shared[((((int)threadIdx.x) + 504))] = placeholder[(((((((((int)blockIdx.z) * 6889) + (((int)blockIdx.y) * 996)) + (((((int)threadIdx.x) + 504) / 45) * 83)) + (((int)blockIdx.x) * 42)) + (((int)threadIdx.x) + 9)) - 168))];
  PaddedInput_shared[((((int)threadIdx.x) + 525))] = (((2 <= ((((int)blockIdx.x) * 42) + ((((int)threadIdx.x) + 30) % 45))) && (((((int)blockIdx.x) * 42) + ((((int)threadIdx.x) + 30) % 45)) < 85)) ? placeholder[(((((((((int)blockIdx.z) * 6889) + (((int)blockIdx.y) * 996)) + (((((int)threadIdx.x) + 525) / 45) * 83)) + (((int)blockIdx.x) * 42)) + ((((int)threadIdx.x) + 30) % 45)) - 168))] : 0.000000e+00f);
  PaddedInput_shared[((((int)threadIdx.x) + 546))] = placeholder[(((((((((int)blockIdx.z) * 6889) + (((int)blockIdx.y) * 996)) + (((((int)threadIdx.x) + 546) / 45) * 83)) + (((int)blockIdx.x) * 42)) + (((int)threadIdx.x) + 6)) - 168))];
  PaddedInput_shared[((((int)threadIdx.x) + 567))] = ((((((((int)blockIdx.y) * 12) + ((((int)threadIdx.x) + 567) / 45)) < 85) && (2 <= ((((int)blockIdx.x) * 42) + ((((int)threadIdx.x) + 27) % 45)))) && (((((int)blockIdx.x) * 42) + ((((int)threadIdx.x) + 27) % 45)) < 85)) ? placeholder[(((((((((int)blockIdx.z) * 6889) + (((int)blockIdx.y) * 996)) + (((((int)threadIdx.x) + 567) / 45) * 83)) + (((int)blockIdx.x) * 42)) + ((((int)threadIdx.x) + 27) % 45)) - 168))] : 0.000000e+00f);
  PaddedInput_shared[((((int)threadIdx.x) + 588))] = ((((((int)blockIdx.y) * 12) + ((((int)threadIdx.x) + 588) / 45)) < 85) ? placeholder[(((((((((int)blockIdx.z) * 6889) + (((int)blockIdx.y) * 996)) + (((((int)threadIdx.x) + 588) / 45) * 83)) + (((int)blockIdx.x) * 42)) + (((int)threadIdx.x) + 3)) - 168))] : 0.000000e+00f);
  PaddedInput_shared[((((int)threadIdx.x) + 609))] = (((((((int)blockIdx.y) * 12) + ((((int)threadIdx.x) + 609) / 45)) < 85) && (((((int)blockIdx.x) * 42) + (((int)threadIdx.x) + 24)) < 85)) ? placeholder[(((((((((int)blockIdx.z) * 6889) + (((int)blockIdx.y) * 996)) + (((((int)threadIdx.x) + 609) / 45) * 83)) + (((int)blockIdx.x) * 42)) + (((int)threadIdx.x) + 24)) - 168))] : 0.000000e+00f);
  PaddedInput_shared[((((int)threadIdx.x) + 630))] = (((((int)blockIdx.y) < 6) && (2 <= ((((int)blockIdx.x) * 42) + ((int)threadIdx.x)))) ? placeholder[((((((((int)blockIdx.z) * 6889) + (((int)blockIdx.y) * 996)) + (((int)blockIdx.x) * 42)) + ((int)threadIdx.x)) + 994))] : 0.000000e+00f);
  PaddedInput_shared[((((int)threadIdx.x) + 651))] = ((((((int)blockIdx.y) * 12) + ((((int)threadIdx.x) + 651) / 45)) < 85) ? placeholder[(((((((((int)blockIdx.z) * 6889) + (((int)blockIdx.y) * 996)) + (((((int)threadIdx.x) + 651) / 45) * 83)) + (((int)blockIdx.x) * 42)) + (((int)threadIdx.x) + 21)) - 168))] : 0.000000e+00f);
  if (((int)threadIdx.x) < 3) {
    PaddedInput_shared[((((int)threadIdx.x) + 672))] = (((((((int)blockIdx.y) * 12) + ((((int)threadIdx.x) + 672) / 45)) < 85) && (((((int)blockIdx.x) * 42) + (((int)threadIdx.x) + 42)) < 85)) ? placeholder[(((((((((int)blockIdx.z) * 6889) + (((int)blockIdx.y) * 996)) + (((((int)threadIdx.x) + 672) / 45) * 83)) + (((int)blockIdx.x) * 42)) + (((int)threadIdx.x) + 42)) - 168))] : 0.000000e+00f);
  }
  placeholder_shared[(((int)threadIdx.x))] = placeholder1[((((((int)blockIdx.z) % 84) * 25) + ((int)threadIdx.x)))];
  if (((int)threadIdx.x) < 4) {
    placeholder_shared[((((int)threadIdx.x) + 21))] = placeholder1[(((((((int)blockIdx.z) % 84) * 25) + ((int)threadIdx.x)) + 21))];
  }
  __syncthreads();
  PaddedInput_shared_local[(0)] = PaddedInput_shared[((((int)threadIdx.x) * 2))];
  PaddedInput_shared_local[(1)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 1))];
  PaddedInput_shared_local[(2)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 2))];
  PaddedInput_shared_local[(3)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 3))];
  PaddedInput_shared_local[(4)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 4))];
  PaddedInput_shared_local[(5)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 45))];
  PaddedInput_shared_local[(6)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 46))];
  PaddedInput_shared_local[(7)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 47))];
  PaddedInput_shared_local[(8)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 48))];
  PaddedInput_shared_local[(9)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 49))];
  PaddedInput_shared_local[(10)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 90))];
  PaddedInput_shared_local[(11)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 91))];
  PaddedInput_shared_local[(12)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 92))];
  PaddedInput_shared_local[(13)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 93))];
  PaddedInput_shared_local[(14)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 94))];
  PaddedInput_shared_local[(15)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 135))];
  PaddedInput_shared_local[(16)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 136))];
  PaddedInput_shared_local[(17)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 137))];
  PaddedInput_shared_local[(18)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 138))];
  PaddedInput_shared_local[(19)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 139))];
  PaddedInput_shared_local[(20)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 180))];
  PaddedInput_shared_local[(21)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 181))];
  PaddedInput_shared_local[(22)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 182))];
  PaddedInput_shared_local[(23)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 183))];
  PaddedInput_shared_local[(24)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 184))];
  PaddedInput_shared_local[(25)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 225))];
  PaddedInput_shared_local[(26)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 226))];
  PaddedInput_shared_local[(27)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 227))];
  PaddedInput_shared_local[(28)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 228))];
  PaddedInput_shared_local[(29)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 229))];
  PaddedInput_shared_local[(30)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 270))];
  PaddedInput_shared_local[(31)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 271))];
  PaddedInput_shared_local[(32)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 272))];
  PaddedInput_shared_local[(33)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 273))];
  PaddedInput_shared_local[(34)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 274))];
  PaddedInput_shared_local[(35)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 315))];
  PaddedInput_shared_local[(36)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 316))];
  PaddedInput_shared_local[(37)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 317))];
  PaddedInput_shared_local[(38)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 318))];
  PaddedInput_shared_local[(39)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 319))];
  PaddedInput_shared_local[(40)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 360))];
  PaddedInput_shared_local[(41)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 361))];
  PaddedInput_shared_local[(42)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 362))];
  PaddedInput_shared_local[(43)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 363))];
  PaddedInput_shared_local[(44)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 364))];
  PaddedInput_shared_local[(45)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 405))];
  PaddedInput_shared_local[(46)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 406))];
  PaddedInput_shared_local[(47)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 407))];
  PaddedInput_shared_local[(48)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 408))];
  PaddedInput_shared_local[(49)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 409))];
  PaddedInput_shared_local[(50)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 450))];
  PaddedInput_shared_local[(51)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 451))];
  PaddedInput_shared_local[(52)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 452))];
  PaddedInput_shared_local[(53)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 453))];
  PaddedInput_shared_local[(54)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 454))];
  PaddedInput_shared_local[(55)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 495))];
  PaddedInput_shared_local[(56)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 496))];
  PaddedInput_shared_local[(57)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 497))];
  PaddedInput_shared_local[(58)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 498))];
  PaddedInput_shared_local[(59)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 499))];
  PaddedInput_shared_local[(60)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 540))];
  PaddedInput_shared_local[(61)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 541))];
  PaddedInput_shared_local[(62)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 542))];
  PaddedInput_shared_local[(63)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 543))];
  PaddedInput_shared_local[(64)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 544))];
  PaddedInput_shared_local[(65)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 585))];
  PaddedInput_shared_local[(66)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 586))];
  PaddedInput_shared_local[(67)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 587))];
  PaddedInput_shared_local[(68)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 588))];
  PaddedInput_shared_local[(69)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 589))];
  PaddedInput_shared_local[(70)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 630))];
  PaddedInput_shared_local[(71)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 631))];
  PaddedInput_shared_local[(72)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 632))];
  PaddedInput_shared_local[(73)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 633))];
  PaddedInput_shared_local[(74)] = PaddedInput_shared[(((((int)threadIdx.x) * 2) + 634))];
  placeholder_shared_local[(0)] = placeholder_shared[(0)];
  placeholder_shared_local[(1)] = placeholder_shared[(1)];
  placeholder_shared_local[(2)] = placeholder_shared[(2)];
  placeholder_shared_local[(3)] = placeholder_shared[(3)];
  placeholder_shared_local[(4)] = placeholder_shared[(4)];
  placeholder_shared_local[(5)] = placeholder_shared[(5)];
  placeholder_shared_local[(6)] = placeholder_shared[(6)];
  placeholder_shared_local[(7)] = placeholder_shared[(7)];
  placeholder_shared_local[(8)] = placeholder_shared[(8)];
  placeholder_shared_local[(9)] = placeholder_shared[(9)];
  placeholder_shared_local[(10)] = placeholder_shared[(10)];
  placeholder_shared_local[(11)] = placeholder_shared[(11)];
  placeholder_shared_local[(12)] = placeholder_shared[(12)];
  placeholder_shared_local[(13)] = placeholder_shared[(13)];
  placeholder_shared_local[(14)] = placeholder_shared[(14)];
  placeholder_shared_local[(15)] = placeholder_shared[(15)];
  placeholder_shared_local[(16)] = placeholder_shared[(16)];
  placeholder_shared_local[(17)] = placeholder_shared[(17)];
  placeholder_shared_local[(18)] = placeholder_shared[(18)];
  placeholder_shared_local[(19)] = placeholder_shared[(19)];
  placeholder_shared_local[(20)] = placeholder_shared[(20)];
  placeholder_shared_local[(21)] = placeholder_shared[(21)];
  placeholder_shared_local[(22)] = placeholder_shared[(22)];
  placeholder_shared_local[(23)] = placeholder_shared[(23)];
  placeholder_shared_local[(24)] = placeholder_shared[(24)];
  DepthwiseConv2d_local[(0)] = 0.000000e+00f;
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(0)] * placeholder_shared_local[(0)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(1)] * placeholder_shared_local[(1)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(2)] * placeholder_shared_local[(2)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(3)] * placeholder_shared_local[(3)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(4)] * placeholder_shared_local[(4)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(5)] * placeholder_shared_local[(5)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(6)] * placeholder_shared_local[(6)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(7)] * placeholder_shared_local[(7)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(8)] * placeholder_shared_local[(8)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(9)] * placeholder_shared_local[(9)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(10)] * placeholder_shared_local[(10)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(11)] * placeholder_shared_local[(11)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(12)] * placeholder_shared_local[(12)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(13)] * placeholder_shared_local[(13)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(14)] * placeholder_shared_local[(14)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(15)] * placeholder_shared_local[(15)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(16)] * placeholder_shared_local[(16)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(17)] * placeholder_shared_local[(17)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(18)] * placeholder_shared_local[(18)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(19)] * placeholder_shared_local[(19)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(20)] * placeholder_shared_local[(20)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(21)] * placeholder_shared_local[(21)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(22)] * placeholder_shared_local[(22)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(23)] * placeholder_shared_local[(23)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(24)] * placeholder_shared_local[(24)]));
  DepthwiseConv2d_local[(1)] = 0.000000e+00f;
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(10)] * placeholder_shared_local[(0)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(11)] * placeholder_shared_local[(1)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(12)] * placeholder_shared_local[(2)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(13)] * placeholder_shared_local[(3)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(14)] * placeholder_shared_local[(4)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(15)] * placeholder_shared_local[(5)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(16)] * placeholder_shared_local[(6)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(17)] * placeholder_shared_local[(7)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(18)] * placeholder_shared_local[(8)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(19)] * placeholder_shared_local[(9)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(20)] * placeholder_shared_local[(10)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(21)] * placeholder_shared_local[(11)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(22)] * placeholder_shared_local[(12)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(23)] * placeholder_shared_local[(13)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(24)] * placeholder_shared_local[(14)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(25)] * placeholder_shared_local[(15)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(26)] * placeholder_shared_local[(16)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(27)] * placeholder_shared_local[(17)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(28)] * placeholder_shared_local[(18)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(29)] * placeholder_shared_local[(19)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(30)] * placeholder_shared_local[(20)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(31)] * placeholder_shared_local[(21)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(32)] * placeholder_shared_local[(22)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(33)] * placeholder_shared_local[(23)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(34)] * placeholder_shared_local[(24)]));
  DepthwiseConv2d_local[(2)] = 0.000000e+00f;
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(20)] * placeholder_shared_local[(0)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(21)] * placeholder_shared_local[(1)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(22)] * placeholder_shared_local[(2)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(23)] * placeholder_shared_local[(3)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(24)] * placeholder_shared_local[(4)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(25)] * placeholder_shared_local[(5)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(26)] * placeholder_shared_local[(6)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(27)] * placeholder_shared_local[(7)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(28)] * placeholder_shared_local[(8)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(29)] * placeholder_shared_local[(9)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(30)] * placeholder_shared_local[(10)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(31)] * placeholder_shared_local[(11)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(32)] * placeholder_shared_local[(12)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(33)] * placeholder_shared_local[(13)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(34)] * placeholder_shared_local[(14)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(35)] * placeholder_shared_local[(15)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(36)] * placeholder_shared_local[(16)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(37)] * placeholder_shared_local[(17)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(38)] * placeholder_shared_local[(18)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(39)] * placeholder_shared_local[(19)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(40)] * placeholder_shared_local[(20)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(41)] * placeholder_shared_local[(21)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(42)] * placeholder_shared_local[(22)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(43)] * placeholder_shared_local[(23)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(44)] * placeholder_shared_local[(24)]));
  DepthwiseConv2d_local[(3)] = 0.000000e+00f;
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(30)] * placeholder_shared_local[(0)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(31)] * placeholder_shared_local[(1)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(32)] * placeholder_shared_local[(2)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(33)] * placeholder_shared_local[(3)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(34)] * placeholder_shared_local[(4)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(35)] * placeholder_shared_local[(5)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(36)] * placeholder_shared_local[(6)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(37)] * placeholder_shared_local[(7)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(38)] * placeholder_shared_local[(8)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(39)] * placeholder_shared_local[(9)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(40)] * placeholder_shared_local[(10)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(41)] * placeholder_shared_local[(11)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(42)] * placeholder_shared_local[(12)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(43)] * placeholder_shared_local[(13)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(44)] * placeholder_shared_local[(14)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(45)] * placeholder_shared_local[(15)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(46)] * placeholder_shared_local[(16)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(47)] * placeholder_shared_local[(17)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(48)] * placeholder_shared_local[(18)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(49)] * placeholder_shared_local[(19)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(50)] * placeholder_shared_local[(20)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(51)] * placeholder_shared_local[(21)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(52)] * placeholder_shared_local[(22)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(53)] * placeholder_shared_local[(23)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(54)] * placeholder_shared_local[(24)]));
  DepthwiseConv2d_local[(4)] = 0.000000e+00f;
  DepthwiseConv2d_local[(4)] = (DepthwiseConv2d_local[(4)] + (PaddedInput_shared_local[(40)] * placeholder_shared_local[(0)]));
  DepthwiseConv2d_local[(4)] = (DepthwiseConv2d_local[(4)] + (PaddedInput_shared_local[(41)] * placeholder_shared_local[(1)]));
  DepthwiseConv2d_local[(4)] = (DepthwiseConv2d_local[(4)] + (PaddedInput_shared_local[(42)] * placeholder_shared_local[(2)]));
  DepthwiseConv2d_local[(4)] = (DepthwiseConv2d_local[(4)] + (PaddedInput_shared_local[(43)] * placeholder_shared_local[(3)]));
  DepthwiseConv2d_local[(4)] = (DepthwiseConv2d_local[(4)] + (PaddedInput_shared_local[(44)] * placeholder_shared_local[(4)]));
  DepthwiseConv2d_local[(4)] = (DepthwiseConv2d_local[(4)] + (PaddedInput_shared_local[(45)] * placeholder_shared_local[(5)]));
  DepthwiseConv2d_local[(4)] = (DepthwiseConv2d_local[(4)] + (PaddedInput_shared_local[(46)] * placeholder_shared_local[(6)]));
  DepthwiseConv2d_local[(4)] = (DepthwiseConv2d_local[(4)] + (PaddedInput_shared_local[(47)] * placeholder_shared_local[(7)]));
  DepthwiseConv2d_local[(4)] = (DepthwiseConv2d_local[(4)] + (PaddedInput_shared_local[(48)] * placeholder_shared_local[(8)]));
  DepthwiseConv2d_local[(4)] = (DepthwiseConv2d_local[(4)] + (PaddedInput_shared_local[(49)] * placeholder_shared_local[(9)]));
  DepthwiseConv2d_local[(4)] = (DepthwiseConv2d_local[(4)] + (PaddedInput_shared_local[(50)] * placeholder_shared_local[(10)]));
  DepthwiseConv2d_local[(4)] = (DepthwiseConv2d_local[(4)] + (PaddedInput_shared_local[(51)] * placeholder_shared_local[(11)]));
  DepthwiseConv2d_local[(4)] = (DepthwiseConv2d_local[(4)] + (PaddedInput_shared_local[(52)] * placeholder_shared_local[(12)]));
  DepthwiseConv2d_local[(4)] = (DepthwiseConv2d_local[(4)] + (PaddedInput_shared_local[(53)] * placeholder_shared_local[(13)]));
  DepthwiseConv2d_local[(4)] = (DepthwiseConv2d_local[(4)] + (PaddedInput_shared_local[(54)] * placeholder_shared_local[(14)]));
  DepthwiseConv2d_local[(4)] = (DepthwiseConv2d_local[(4)] + (PaddedInput_shared_local[(55)] * placeholder_shared_local[(15)]));
  DepthwiseConv2d_local[(4)] = (DepthwiseConv2d_local[(4)] + (PaddedInput_shared_local[(56)] * placeholder_shared_local[(16)]));
  DepthwiseConv2d_local[(4)] = (DepthwiseConv2d_local[(4)] + (PaddedInput_shared_local[(57)] * placeholder_shared_local[(17)]));
  DepthwiseConv2d_local[(4)] = (DepthwiseConv2d_local[(4)] + (PaddedInput_shared_local[(58)] * placeholder_shared_local[(18)]));
  DepthwiseConv2d_local[(4)] = (DepthwiseConv2d_local[(4)] + (PaddedInput_shared_local[(59)] * placeholder_shared_local[(19)]));
  DepthwiseConv2d_local[(4)] = (DepthwiseConv2d_local[(4)] + (PaddedInput_shared_local[(60)] * placeholder_shared_local[(20)]));
  DepthwiseConv2d_local[(4)] = (DepthwiseConv2d_local[(4)] + (PaddedInput_shared_local[(61)] * placeholder_shared_local[(21)]));
  DepthwiseConv2d_local[(4)] = (DepthwiseConv2d_local[(4)] + (PaddedInput_shared_local[(62)] * placeholder_shared_local[(22)]));
  DepthwiseConv2d_local[(4)] = (DepthwiseConv2d_local[(4)] + (PaddedInput_shared_local[(63)] * placeholder_shared_local[(23)]));
  DepthwiseConv2d_local[(4)] = (DepthwiseConv2d_local[(4)] + (PaddedInput_shared_local[(64)] * placeholder_shared_local[(24)]));
  DepthwiseConv2d_local[(5)] = 0.000000e+00f;
  DepthwiseConv2d_local[(5)] = (DepthwiseConv2d_local[(5)] + (PaddedInput_shared_local[(50)] * placeholder_shared_local[(0)]));
  DepthwiseConv2d_local[(5)] = (DepthwiseConv2d_local[(5)] + (PaddedInput_shared_local[(51)] * placeholder_shared_local[(1)]));
  DepthwiseConv2d_local[(5)] = (DepthwiseConv2d_local[(5)] + (PaddedInput_shared_local[(52)] * placeholder_shared_local[(2)]));
  DepthwiseConv2d_local[(5)] = (DepthwiseConv2d_local[(5)] + (PaddedInput_shared_local[(53)] * placeholder_shared_local[(3)]));
  DepthwiseConv2d_local[(5)] = (DepthwiseConv2d_local[(5)] + (PaddedInput_shared_local[(54)] * placeholder_shared_local[(4)]));
  DepthwiseConv2d_local[(5)] = (DepthwiseConv2d_local[(5)] + (PaddedInput_shared_local[(55)] * placeholder_shared_local[(5)]));
  DepthwiseConv2d_local[(5)] = (DepthwiseConv2d_local[(5)] + (PaddedInput_shared_local[(56)] * placeholder_shared_local[(6)]));
  DepthwiseConv2d_local[(5)] = (DepthwiseConv2d_local[(5)] + (PaddedInput_shared_local[(57)] * placeholder_shared_local[(7)]));
  DepthwiseConv2d_local[(5)] = (DepthwiseConv2d_local[(5)] + (PaddedInput_shared_local[(58)] * placeholder_shared_local[(8)]));
  DepthwiseConv2d_local[(5)] = (DepthwiseConv2d_local[(5)] + (PaddedInput_shared_local[(59)] * placeholder_shared_local[(9)]));
  DepthwiseConv2d_local[(5)] = (DepthwiseConv2d_local[(5)] + (PaddedInput_shared_local[(60)] * placeholder_shared_local[(10)]));
  DepthwiseConv2d_local[(5)] = (DepthwiseConv2d_local[(5)] + (PaddedInput_shared_local[(61)] * placeholder_shared_local[(11)]));
  DepthwiseConv2d_local[(5)] = (DepthwiseConv2d_local[(5)] + (PaddedInput_shared_local[(62)] * placeholder_shared_local[(12)]));
  DepthwiseConv2d_local[(5)] = (DepthwiseConv2d_local[(5)] + (PaddedInput_shared_local[(63)] * placeholder_shared_local[(13)]));
  DepthwiseConv2d_local[(5)] = (DepthwiseConv2d_local[(5)] + (PaddedInput_shared_local[(64)] * placeholder_shared_local[(14)]));
  DepthwiseConv2d_local[(5)] = (DepthwiseConv2d_local[(5)] + (PaddedInput_shared_local[(65)] * placeholder_shared_local[(15)]));
  DepthwiseConv2d_local[(5)] = (DepthwiseConv2d_local[(5)] + (PaddedInput_shared_local[(66)] * placeholder_shared_local[(16)]));
  DepthwiseConv2d_local[(5)] = (DepthwiseConv2d_local[(5)] + (PaddedInput_shared_local[(67)] * placeholder_shared_local[(17)]));
  DepthwiseConv2d_local[(5)] = (DepthwiseConv2d_local[(5)] + (PaddedInput_shared_local[(68)] * placeholder_shared_local[(18)]));
  DepthwiseConv2d_local[(5)] = (DepthwiseConv2d_local[(5)] + (PaddedInput_shared_local[(69)] * placeholder_shared_local[(19)]));
  DepthwiseConv2d_local[(5)] = (DepthwiseConv2d_local[(5)] + (PaddedInput_shared_local[(70)] * placeholder_shared_local[(20)]));
  DepthwiseConv2d_local[(5)] = (DepthwiseConv2d_local[(5)] + (PaddedInput_shared_local[(71)] * placeholder_shared_local[(21)]));
  DepthwiseConv2d_local[(5)] = (DepthwiseConv2d_local[(5)] + (PaddedInput_shared_local[(72)] * placeholder_shared_local[(22)]));
  DepthwiseConv2d_local[(5)] = (DepthwiseConv2d_local[(5)] + (PaddedInput_shared_local[(73)] * placeholder_shared_local[(23)]));
  DepthwiseConv2d_local[(5)] = (DepthwiseConv2d_local[(5)] + (PaddedInput_shared_local[(74)] * placeholder_shared_local[(24)]));
  DepthwiseConv2d[(((((((int)blockIdx.z) * 1764) + (((int)blockIdx.y) * 252)) + (((int)blockIdx.x) * 21)) + ((int)threadIdx.x)))] = DepthwiseConv2d_local[(0)];
  DepthwiseConv2d[((((((((int)blockIdx.z) * 1764) + (((int)blockIdx.y) * 252)) + (((int)blockIdx.x) * 21)) + ((int)threadIdx.x)) + 42))] = DepthwiseConv2d_local[(1)];
  DepthwiseConv2d[((((((((int)blockIdx.z) * 1764) + (((int)blockIdx.y) * 252)) + (((int)blockIdx.x) * 21)) + ((int)threadIdx.x)) + 84))] = DepthwiseConv2d_local[(2)];
  DepthwiseConv2d[((((((((int)blockIdx.z) * 1764) + (((int)blockIdx.y) * 252)) + (((int)blockIdx.x) * 21)) + ((int)threadIdx.x)) + 126))] = DepthwiseConv2d_local[(3)];
  DepthwiseConv2d[((((((((int)blockIdx.z) * 1764) + (((int)blockIdx.y) * 252)) + (((int)blockIdx.x) * 21)) + ((int)threadIdx.x)) + 168))] = DepthwiseConv2d_local[(4)];
  DepthwiseConv2d[((((((((int)blockIdx.z) * 1764) + (((int)blockIdx.y) * 252)) + (((int)blockIdx.x) * 21)) + ((int)threadIdx.x)) + 210))] = DepthwiseConv2d_local[(5)];
}

