//1_7_10752_21_3_1
//128_84_83_83_7_2_SAME
//dim3 grid(1, 7, 10752);
//dim3 block(21, 3, 1);

#ifdef _WIN32
  using uint = unsigned int;
  using uchar = unsigned char;
  using ushort = unsigned short;
  using int64_t = long long;
  using uint64_t = unsigned long long;
#else
  #define uint unsigned int
  #define uchar unsigned char
  #define ushort unsigned short
  #define int64_t long long
  #define uint64_t unsigned long long
#endif
extern "C" __global__ void __launch_bounds__(63) depthwise_kernel0(float* __restrict__ placeholder, float* __restrict__ placeholder1, float* __restrict__ DepthwiseConv2d) {
  __shared__ float PaddedInput_shared[1513];
  __shared__ float placeholder_shared[49];
  float PaddedInput_shared_local[81];
  float placeholder_shared_local[49];
  float DepthwiseConv2d_local[4];
  PaddedInput_shared[(((((int)threadIdx.y) * 21) + ((int)threadIdx.x)))] = (((1 <= ((int)blockIdx.y)) && (3 <= ((((int)threadIdx.y) * 21) + ((int)threadIdx.x)))) ? placeholder[((((((((int)blockIdx.z) * 6889) + (((int)blockIdx.y) * 996)) + (((int)threadIdx.y) * 21)) + ((int)threadIdx.x)) - 252))] : 0.000000e+00f);
  PaddedInput_shared[((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 63))] = ((((3 <= ((((int)blockIdx.y) * 12) + ((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 63) / 89))) && (3 <= ((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 63) % 89))) && (((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 63) % 89) < 86)) ? placeholder[((((((((int)blockIdx.z) * 6889) + (((int)blockIdx.y) * 996)) + (((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 63) / 89) * 83)) + ((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 63) % 89)) - 252))] : 0.000000e+00f);
  PaddedInput_shared[((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 126))] = ((((3 <= ((((int)blockIdx.y) * 12) + ((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 126) / 89))) && (3 <= ((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 37) % 89))) && (((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 37) % 89) < 86)) ? placeholder[((((((((int)blockIdx.z) * 6889) + (((int)blockIdx.y) * 996)) + (((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 126) / 89) * 83)) + ((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 37) % 89)) - 252))] : 0.000000e+00f);
  PaddedInput_shared[((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 189))] = ((3 <= ((((int)blockIdx.y) * 12) + ((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 189) / 89))) ? placeholder[((((((((int)blockIdx.z) * 6889) + (((int)blockIdx.y) * 996)) + (((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 189) / 89) * 83)) + (((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 11)) - 252))] : 0.000000e+00f);
  PaddedInput_shared[((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 252))] = ((((3 <= ((((int)blockIdx.y) * 12) + ((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 252) / 89))) && (3 <= ((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 74) % 89))) && (((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 74) % 89) < 86)) ? placeholder[((((((((int)blockIdx.z) * 6889) + (((int)blockIdx.y) * 996)) + (((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 252) / 89) * 83)) + ((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 74) % 89)) - 252))] : 0.000000e+00f);
  PaddedInput_shared[((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 315))] = (((3 <= ((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 48) % 89)) && (((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 48) % 89) < 86)) ? placeholder[((((((((int)blockIdx.z) * 6889) + (((int)blockIdx.y) * 996)) + (((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 315) / 89) * 83)) + ((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 48) % 89)) - 252))] : 0.000000e+00f);
  PaddedInput_shared[((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 378))] = placeholder[((((((((int)blockIdx.z) * 6889) + (((int)blockIdx.y) * 996)) + (((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 378) / 89) * 83)) + (((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 22)) - 252))];
  PaddedInput_shared[((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 441))] = (((3 <= ((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 85) % 89)) && (((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 85) % 89) < 86)) ? placeholder[((((((((int)blockIdx.z) * 6889) + (((int)blockIdx.y) * 996)) + (((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 441) / 89) * 83)) + ((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 85) % 89)) - 252))] : 0.000000e+00f);
  PaddedInput_shared[((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 504))] = (((3 <= ((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 59) % 89)) && (((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 59) % 89) < 86)) ? placeholder[((((((((int)blockIdx.z) * 6889) + (((int)blockIdx.y) * 996)) + (((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 504) / 89) * 83)) + ((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 59) % 89)) - 252))] : 0.000000e+00f);
  PaddedInput_shared[((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 567))] = (((3 <= ((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 33) % 89)) && (((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 33) % 89) < 86)) ? placeholder[((((((((int)blockIdx.z) * 6889) + (((int)blockIdx.y) * 996)) + (((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 567) / 89) * 83)) + ((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 33) % 89)) - 252))] : 0.000000e+00f);
  PaddedInput_shared[((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 630))] = placeholder[((((((((int)blockIdx.z) * 6889) + (((int)blockIdx.y) * 996)) + (((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 630) / 89) * 83)) + (((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 7)) - 252))];
  PaddedInput_shared[((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 693))] = (((3 <= ((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 70) % 89)) && (((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 70) % 89) < 86)) ? placeholder[((((((((int)blockIdx.z) * 6889) + (((int)blockIdx.y) * 996)) + (((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 693) / 89) * 83)) + ((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 70) % 89)) - 252))] : 0.000000e+00f);
  PaddedInput_shared[((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 756))] = (((3 <= ((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 44) % 89)) && (((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 44) % 89) < 86)) ? placeholder[((((((((int)blockIdx.z) * 6889) + (((int)blockIdx.y) * 996)) + (((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 756) / 89) * 83)) + ((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 44) % 89)) - 252))] : 0.000000e+00f);
  PaddedInput_shared[((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 819))] = placeholder[((((((((int)blockIdx.z) * 6889) + (((int)blockIdx.y) * 996)) + (((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 819) / 89) * 83)) + (((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 18)) - 252))];
  PaddedInput_shared[((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 882))] = (((3 <= ((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 81) % 89)) && (((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 81) % 89) < 86)) ? placeholder[((((((((int)blockIdx.z) * 6889) + (((int)blockIdx.y) * 996)) + (((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 882) / 89) * 83)) + ((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 81) % 89)) - 252))] : 0.000000e+00f);
  PaddedInput_shared[((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 945))] = (((3 <= ((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 55) % 89)) && (((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 55) % 89) < 86)) ? placeholder[((((((((int)blockIdx.z) * 6889) + (((int)blockIdx.y) * 996)) + (((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 945) / 89) * 83)) + ((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 55) % 89)) - 252))] : 0.000000e+00f);
  PaddedInput_shared[((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 1008))] = (((3 <= ((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 29) % 89)) && (((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 29) % 89) < 86)) ? placeholder[((((((((int)blockIdx.z) * 6889) + (((int)blockIdx.y) * 996)) + (((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 1008) / 89) * 83)) + ((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 29) % 89)) - 252))] : 0.000000e+00f);
  PaddedInput_shared[((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 1071))] = placeholder[((((((((int)blockIdx.z) * 6889) + (((int)blockIdx.y) * 996)) + (((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 1071) / 89) * 83)) + (((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 3)) - 252))];
  PaddedInput_shared[((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 1134))] = (((3 <= ((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 66) % 89)) && (((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 66) % 89) < 86)) ? placeholder[((((((((int)blockIdx.z) * 6889) + (((int)blockIdx.y) * 996)) + (((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 1134) / 89) * 83)) + ((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 66) % 89)) - 252))] : 0.000000e+00f);
  PaddedInput_shared[((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 1197))] = ((((((((int)blockIdx.y) * 12) + ((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 1197) / 89)) < 86) && (3 <= ((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 40) % 89))) && (((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 40) % 89) < 86)) ? placeholder[((((((((int)blockIdx.z) * 6889) + (((int)blockIdx.y) * 996)) + (((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 1197) / 89) * 83)) + ((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 40) % 89)) - 252))] : 0.000000e+00f);
  PaddedInput_shared[((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 1260))] = ((((((int)blockIdx.y) * 12) + ((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 1260) / 89)) < 86) ? placeholder[((((((((int)blockIdx.z) * 6889) + (((int)blockIdx.y) * 996)) + (((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 1260) / 89) * 83)) + (((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 14)) - 252))] : 0.000000e+00f);
  PaddedInput_shared[((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 1323))] = ((((((((int)blockIdx.y) * 12) + ((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 1323) / 89)) < 86) && (3 <= ((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 77) % 89))) && (((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 77) % 89) < 86)) ? placeholder[((((((((int)blockIdx.z) * 6889) + (((int)blockIdx.y) * 996)) + (((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 1323) / 89) * 83)) + ((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 77) % 89)) - 252))] : 0.000000e+00f);
  PaddedInput_shared[((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 1386))] = ((((((((int)blockIdx.y) * 12) + ((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 1386) / 89)) < 86) && (3 <= ((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 51) % 89))) && (((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 51) % 89) < 86)) ? placeholder[((((((((int)blockIdx.z) * 6889) + (((int)blockIdx.y) * 996)) + (((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 1386) / 89) * 83)) + ((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 51) % 89)) - 252))] : 0.000000e+00f);
  PaddedInput_shared[((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 1449))] = (((((((int)blockIdx.y) * 12) + ((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 1449) / 89)) < 86) && (((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) < 61)) ? placeholder[((((((((int)blockIdx.z) * 6889) + (((int)blockIdx.y) * 996)) + (((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 1449) / 89) * 83)) + (((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 25)) - 252))] : 0.000000e+00f);
  if (((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) < 1) {
    if (((int)threadIdx.y) < 1) {
      PaddedInput_shared[((((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) + 1512))] = 0.000000e+00f;
    }
  }
  if (((((int)threadIdx.y) * 3) + (((int)threadIdx.x) / 7)) < 7) {
    if (((((int)threadIdx.y) * 21) + ((int)threadIdx.x)) < 49) {
      placeholder_shared[(((((int)threadIdx.y) * 21) + ((int)threadIdx.x)))] = placeholder1[(((((((int)blockIdx.z) % 84) * 49) + (((int)threadIdx.y) * 21)) + ((int)threadIdx.x)))];
    }
  }
  __syncthreads();
  PaddedInput_shared_local[(0)] = PaddedInput_shared[(((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)))];
  PaddedInput_shared_local[(1)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 1))];
  PaddedInput_shared_local[(2)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 2))];
  PaddedInput_shared_local[(3)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 3))];
  PaddedInput_shared_local[(4)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 4))];
  PaddedInput_shared_local[(5)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 5))];
  PaddedInput_shared_local[(6)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 6))];
  PaddedInput_shared_local[(7)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 7))];
  PaddedInput_shared_local[(8)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 8))];
  PaddedInput_shared_local[(9)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 89))];
  PaddedInput_shared_local[(10)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 90))];
  PaddedInput_shared_local[(11)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 91))];
  PaddedInput_shared_local[(12)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 92))];
  PaddedInput_shared_local[(13)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 93))];
  PaddedInput_shared_local[(14)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 94))];
  PaddedInput_shared_local[(15)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 95))];
  PaddedInput_shared_local[(16)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 96))];
  PaddedInput_shared_local[(17)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 97))];
  PaddedInput_shared_local[(18)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 178))];
  PaddedInput_shared_local[(19)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 179))];
  PaddedInput_shared_local[(20)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 180))];
  PaddedInput_shared_local[(21)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 181))];
  PaddedInput_shared_local[(22)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 182))];
  PaddedInput_shared_local[(23)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 183))];
  PaddedInput_shared_local[(24)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 184))];
  PaddedInput_shared_local[(25)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 185))];
  PaddedInput_shared_local[(26)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 186))];
  PaddedInput_shared_local[(27)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 267))];
  PaddedInput_shared_local[(28)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 268))];
  PaddedInput_shared_local[(29)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 269))];
  PaddedInput_shared_local[(30)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 270))];
  PaddedInput_shared_local[(31)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 271))];
  PaddedInput_shared_local[(32)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 272))];
  PaddedInput_shared_local[(33)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 273))];
  PaddedInput_shared_local[(34)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 274))];
  PaddedInput_shared_local[(35)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 275))];
  PaddedInput_shared_local[(36)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 356))];
  PaddedInput_shared_local[(37)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 357))];
  PaddedInput_shared_local[(38)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 358))];
  PaddedInput_shared_local[(39)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 359))];
  PaddedInput_shared_local[(40)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 360))];
  PaddedInput_shared_local[(41)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 361))];
  PaddedInput_shared_local[(42)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 362))];
  PaddedInput_shared_local[(43)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 363))];
  PaddedInput_shared_local[(44)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 364))];
  PaddedInput_shared_local[(45)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 445))];
  PaddedInput_shared_local[(46)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 446))];
  PaddedInput_shared_local[(47)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 447))];
  PaddedInput_shared_local[(48)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 448))];
  PaddedInput_shared_local[(49)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 449))];
  PaddedInput_shared_local[(50)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 450))];
  PaddedInput_shared_local[(51)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 451))];
  PaddedInput_shared_local[(52)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 452))];
  PaddedInput_shared_local[(53)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 453))];
  PaddedInput_shared_local[(54)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 534))];
  PaddedInput_shared_local[(55)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 535))];
  PaddedInput_shared_local[(56)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 536))];
  PaddedInput_shared_local[(57)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 537))];
  PaddedInput_shared_local[(58)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 538))];
  PaddedInput_shared_local[(59)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 539))];
  PaddedInput_shared_local[(60)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 540))];
  PaddedInput_shared_local[(61)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 541))];
  PaddedInput_shared_local[(62)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 542))];
  PaddedInput_shared_local[(63)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 623))];
  PaddedInput_shared_local[(64)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 624))];
  PaddedInput_shared_local[(65)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 625))];
  PaddedInput_shared_local[(66)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 626))];
  PaddedInput_shared_local[(67)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 627))];
  PaddedInput_shared_local[(68)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 628))];
  PaddedInput_shared_local[(69)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 629))];
  PaddedInput_shared_local[(70)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 630))];
  PaddedInput_shared_local[(71)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 631))];
  PaddedInput_shared_local[(72)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 712))];
  PaddedInput_shared_local[(73)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 713))];
  PaddedInput_shared_local[(74)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 714))];
  PaddedInput_shared_local[(75)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 715))];
  PaddedInput_shared_local[(76)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 716))];
  PaddedInput_shared_local[(77)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 717))];
  PaddedInput_shared_local[(78)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 718))];
  PaddedInput_shared_local[(79)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 719))];
  PaddedInput_shared_local[(80)] = PaddedInput_shared[((((((int)threadIdx.y) * 356) + (((int)threadIdx.x) * 4)) + 720))];
  placeholder_shared_local[(0)] = placeholder_shared[(0)];
  placeholder_shared_local[(1)] = placeholder_shared[(1)];
  placeholder_shared_local[(2)] = placeholder_shared[(2)];
  placeholder_shared_local[(3)] = placeholder_shared[(3)];
  placeholder_shared_local[(4)] = placeholder_shared[(4)];
  placeholder_shared_local[(5)] = placeholder_shared[(5)];
  placeholder_shared_local[(6)] = placeholder_shared[(6)];
  placeholder_shared_local[(7)] = placeholder_shared[(7)];
  placeholder_shared_local[(8)] = placeholder_shared[(8)];
  placeholder_shared_local[(9)] = placeholder_shared[(9)];
  placeholder_shared_local[(10)] = placeholder_shared[(10)];
  placeholder_shared_local[(11)] = placeholder_shared[(11)];
  placeholder_shared_local[(12)] = placeholder_shared[(12)];
  placeholder_shared_local[(13)] = placeholder_shared[(13)];
  placeholder_shared_local[(14)] = placeholder_shared[(14)];
  placeholder_shared_local[(15)] = placeholder_shared[(15)];
  placeholder_shared_local[(16)] = placeholder_shared[(16)];
  placeholder_shared_local[(17)] = placeholder_shared[(17)];
  placeholder_shared_local[(18)] = placeholder_shared[(18)];
  placeholder_shared_local[(19)] = placeholder_shared[(19)];
  placeholder_shared_local[(20)] = placeholder_shared[(20)];
  placeholder_shared_local[(21)] = placeholder_shared[(21)];
  placeholder_shared_local[(22)] = placeholder_shared[(22)];
  placeholder_shared_local[(23)] = placeholder_shared[(23)];
  placeholder_shared_local[(24)] = placeholder_shared[(24)];
  placeholder_shared_local[(25)] = placeholder_shared[(25)];
  placeholder_shared_local[(26)] = placeholder_shared[(26)];
  placeholder_shared_local[(27)] = placeholder_shared[(27)];
  placeholder_shared_local[(28)] = placeholder_shared[(28)];
  placeholder_shared_local[(29)] = placeholder_shared[(29)];
  placeholder_shared_local[(30)] = placeholder_shared[(30)];
  placeholder_shared_local[(31)] = placeholder_shared[(31)];
  placeholder_shared_local[(32)] = placeholder_shared[(32)];
  placeholder_shared_local[(33)] = placeholder_shared[(33)];
  placeholder_shared_local[(34)] = placeholder_shared[(34)];
  placeholder_shared_local[(35)] = placeholder_shared[(35)];
  placeholder_shared_local[(36)] = placeholder_shared[(36)];
  placeholder_shared_local[(37)] = placeholder_shared[(37)];
  placeholder_shared_local[(38)] = placeholder_shared[(38)];
  placeholder_shared_local[(39)] = placeholder_shared[(39)];
  placeholder_shared_local[(40)] = placeholder_shared[(40)];
  placeholder_shared_local[(41)] = placeholder_shared[(41)];
  placeholder_shared_local[(42)] = placeholder_shared[(42)];
  placeholder_shared_local[(43)] = placeholder_shared[(43)];
  placeholder_shared_local[(44)] = placeholder_shared[(44)];
  placeholder_shared_local[(45)] = placeholder_shared[(45)];
  placeholder_shared_local[(46)] = placeholder_shared[(46)];
  placeholder_shared_local[(47)] = placeholder_shared[(47)];
  placeholder_shared_local[(48)] = placeholder_shared[(48)];
  DepthwiseConv2d_local[(0)] = 0.000000e+00f;
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(0)] * placeholder_shared_local[(0)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(1)] * placeholder_shared_local[(1)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(2)] * placeholder_shared_local[(2)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(3)] * placeholder_shared_local[(3)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(4)] * placeholder_shared_local[(4)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(5)] * placeholder_shared_local[(5)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(6)] * placeholder_shared_local[(6)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(9)] * placeholder_shared_local[(7)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(10)] * placeholder_shared_local[(8)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(11)] * placeholder_shared_local[(9)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(12)] * placeholder_shared_local[(10)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(13)] * placeholder_shared_local[(11)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(14)] * placeholder_shared_local[(12)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(15)] * placeholder_shared_local[(13)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(18)] * placeholder_shared_local[(14)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(19)] * placeholder_shared_local[(15)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(20)] * placeholder_shared_local[(16)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(21)] * placeholder_shared_local[(17)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(22)] * placeholder_shared_local[(18)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(23)] * placeholder_shared_local[(19)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(24)] * placeholder_shared_local[(20)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(27)] * placeholder_shared_local[(21)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(28)] * placeholder_shared_local[(22)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(29)] * placeholder_shared_local[(23)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(30)] * placeholder_shared_local[(24)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(31)] * placeholder_shared_local[(25)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(32)] * placeholder_shared_local[(26)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(33)] * placeholder_shared_local[(27)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(36)] * placeholder_shared_local[(28)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(37)] * placeholder_shared_local[(29)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(38)] * placeholder_shared_local[(30)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(39)] * placeholder_shared_local[(31)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(40)] * placeholder_shared_local[(32)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(41)] * placeholder_shared_local[(33)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(42)] * placeholder_shared_local[(34)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(45)] * placeholder_shared_local[(35)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(46)] * placeholder_shared_local[(36)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(47)] * placeholder_shared_local[(37)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(48)] * placeholder_shared_local[(38)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(49)] * placeholder_shared_local[(39)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(50)] * placeholder_shared_local[(40)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(51)] * placeholder_shared_local[(41)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(54)] * placeholder_shared_local[(42)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(55)] * placeholder_shared_local[(43)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(56)] * placeholder_shared_local[(44)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(57)] * placeholder_shared_local[(45)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(58)] * placeholder_shared_local[(46)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(59)] * placeholder_shared_local[(47)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(60)] * placeholder_shared_local[(48)]));
  DepthwiseConv2d_local[(1)] = 0.000000e+00f;
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(2)] * placeholder_shared_local[(0)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(3)] * placeholder_shared_local[(1)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(4)] * placeholder_shared_local[(2)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(5)] * placeholder_shared_local[(3)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(6)] * placeholder_shared_local[(4)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(7)] * placeholder_shared_local[(5)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(8)] * placeholder_shared_local[(6)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(11)] * placeholder_shared_local[(7)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(12)] * placeholder_shared_local[(8)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(13)] * placeholder_shared_local[(9)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(14)] * placeholder_shared_local[(10)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(15)] * placeholder_shared_local[(11)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(16)] * placeholder_shared_local[(12)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(17)] * placeholder_shared_local[(13)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(20)] * placeholder_shared_local[(14)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(21)] * placeholder_shared_local[(15)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(22)] * placeholder_shared_local[(16)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(23)] * placeholder_shared_local[(17)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(24)] * placeholder_shared_local[(18)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(25)] * placeholder_shared_local[(19)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(26)] * placeholder_shared_local[(20)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(29)] * placeholder_shared_local[(21)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(30)] * placeholder_shared_local[(22)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(31)] * placeholder_shared_local[(23)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(32)] * placeholder_shared_local[(24)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(33)] * placeholder_shared_local[(25)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(34)] * placeholder_shared_local[(26)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(35)] * placeholder_shared_local[(27)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(38)] * placeholder_shared_local[(28)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(39)] * placeholder_shared_local[(29)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(40)] * placeholder_shared_local[(30)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(41)] * placeholder_shared_local[(31)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(42)] * placeholder_shared_local[(32)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(43)] * placeholder_shared_local[(33)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(44)] * placeholder_shared_local[(34)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(47)] * placeholder_shared_local[(35)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(48)] * placeholder_shared_local[(36)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(49)] * placeholder_shared_local[(37)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(50)] * placeholder_shared_local[(38)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(51)] * placeholder_shared_local[(39)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(52)] * placeholder_shared_local[(40)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(53)] * placeholder_shared_local[(41)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(56)] * placeholder_shared_local[(42)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(57)] * placeholder_shared_local[(43)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(58)] * placeholder_shared_local[(44)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(59)] * placeholder_shared_local[(45)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(60)] * placeholder_shared_local[(46)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(61)] * placeholder_shared_local[(47)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(62)] * placeholder_shared_local[(48)]));
  DepthwiseConv2d_local[(2)] = 0.000000e+00f;
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(18)] * placeholder_shared_local[(0)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(19)] * placeholder_shared_local[(1)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(20)] * placeholder_shared_local[(2)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(21)] * placeholder_shared_local[(3)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(22)] * placeholder_shared_local[(4)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(23)] * placeholder_shared_local[(5)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(24)] * placeholder_shared_local[(6)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(27)] * placeholder_shared_local[(7)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(28)] * placeholder_shared_local[(8)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(29)] * placeholder_shared_local[(9)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(30)] * placeholder_shared_local[(10)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(31)] * placeholder_shared_local[(11)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(32)] * placeholder_shared_local[(12)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(33)] * placeholder_shared_local[(13)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(36)] * placeholder_shared_local[(14)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(37)] * placeholder_shared_local[(15)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(38)] * placeholder_shared_local[(16)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(39)] * placeholder_shared_local[(17)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(40)] * placeholder_shared_local[(18)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(41)] * placeholder_shared_local[(19)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(42)] * placeholder_shared_local[(20)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(45)] * placeholder_shared_local[(21)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(46)] * placeholder_shared_local[(22)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(47)] * placeholder_shared_local[(23)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(48)] * placeholder_shared_local[(24)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(49)] * placeholder_shared_local[(25)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(50)] * placeholder_shared_local[(26)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(51)] * placeholder_shared_local[(27)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(54)] * placeholder_shared_local[(28)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(55)] * placeholder_shared_local[(29)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(56)] * placeholder_shared_local[(30)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(57)] * placeholder_shared_local[(31)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(58)] * placeholder_shared_local[(32)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(59)] * placeholder_shared_local[(33)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(60)] * placeholder_shared_local[(34)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(63)] * placeholder_shared_local[(35)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(64)] * placeholder_shared_local[(36)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(65)] * placeholder_shared_local[(37)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(66)] * placeholder_shared_local[(38)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(67)] * placeholder_shared_local[(39)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(68)] * placeholder_shared_local[(40)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(69)] * placeholder_shared_local[(41)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(72)] * placeholder_shared_local[(42)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(73)] * placeholder_shared_local[(43)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(74)] * placeholder_shared_local[(44)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(75)] * placeholder_shared_local[(45)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(76)] * placeholder_shared_local[(46)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(77)] * placeholder_shared_local[(47)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(78)] * placeholder_shared_local[(48)]));
  DepthwiseConv2d_local[(3)] = 0.000000e+00f;
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(20)] * placeholder_shared_local[(0)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(21)] * placeholder_shared_local[(1)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(22)] * placeholder_shared_local[(2)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(23)] * placeholder_shared_local[(3)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(24)] * placeholder_shared_local[(4)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(25)] * placeholder_shared_local[(5)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(26)] * placeholder_shared_local[(6)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(29)] * placeholder_shared_local[(7)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(30)] * placeholder_shared_local[(8)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(31)] * placeholder_shared_local[(9)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(32)] * placeholder_shared_local[(10)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(33)] * placeholder_shared_local[(11)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(34)] * placeholder_shared_local[(12)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(35)] * placeholder_shared_local[(13)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(38)] * placeholder_shared_local[(14)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(39)] * placeholder_shared_local[(15)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(40)] * placeholder_shared_local[(16)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(41)] * placeholder_shared_local[(17)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(42)] * placeholder_shared_local[(18)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(43)] * placeholder_shared_local[(19)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(44)] * placeholder_shared_local[(20)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(47)] * placeholder_shared_local[(21)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(48)] * placeholder_shared_local[(22)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(49)] * placeholder_shared_local[(23)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(50)] * placeholder_shared_local[(24)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(51)] * placeholder_shared_local[(25)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(52)] * placeholder_shared_local[(26)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(53)] * placeholder_shared_local[(27)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(56)] * placeholder_shared_local[(28)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(57)] * placeholder_shared_local[(29)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(58)] * placeholder_shared_local[(30)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(59)] * placeholder_shared_local[(31)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(60)] * placeholder_shared_local[(32)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(61)] * placeholder_shared_local[(33)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(62)] * placeholder_shared_local[(34)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(65)] * placeholder_shared_local[(35)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(66)] * placeholder_shared_local[(36)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(67)] * placeholder_shared_local[(37)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(68)] * placeholder_shared_local[(38)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(69)] * placeholder_shared_local[(39)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(70)] * placeholder_shared_local[(40)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(71)] * placeholder_shared_local[(41)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(74)] * placeholder_shared_local[(42)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(75)] * placeholder_shared_local[(43)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(76)] * placeholder_shared_local[(44)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(77)] * placeholder_shared_local[(45)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(78)] * placeholder_shared_local[(46)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(79)] * placeholder_shared_local[(47)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(80)] * placeholder_shared_local[(48)]));
  DepthwiseConv2d[(((((((int)blockIdx.z) * 1764) + (((int)blockIdx.y) * 252)) + (((int)threadIdx.y) * 84)) + (((int)threadIdx.x) * 2)))] = DepthwiseConv2d_local[(0)];
  DepthwiseConv2d[((((((((int)blockIdx.z) * 1764) + (((int)blockIdx.y) * 252)) + (((int)threadIdx.y) * 84)) + (((int)threadIdx.x) * 2)) + 1))] = DepthwiseConv2d_local[(1)];
  DepthwiseConv2d[((((((((int)blockIdx.z) * 1764) + (((int)blockIdx.y) * 252)) + (((int)threadIdx.y) * 84)) + (((int)threadIdx.x) * 2)) + 42))] = DepthwiseConv2d_local[(2)];
  DepthwiseConv2d[((((((((int)blockIdx.z) * 1764) + (((int)blockIdx.y) * 252)) + (((int)threadIdx.y) * 84)) + (((int)threadIdx.x) * 2)) + 43))] = DepthwiseConv2d_local[(3)];
}

