//1_1_43008_11_1_1
//128_672_11_11_3_1_SAME
//dim3 grid(1, 1, 43008);
//dim3 block(11, 1, 1);

#ifdef _WIN32
  using uint = unsigned int;
  using uchar = unsigned char;
  using ushort = unsigned short;
  using int64_t = long long;
  using uint64_t = unsigned long long;
#else
  #define uint unsigned int
  #define uchar unsigned char
  #define ushort unsigned short
  #define int64_t long long
  #define uint64_t unsigned long long
#endif
extern "C" __global__ void __launch_bounds__(11) depthwise_kernel0(float* __restrict__ placeholder, float* __restrict__ placeholder1, float* __restrict__ DepthwiseConv2d) {
  __shared__ float PaddedInput_shared[338];
  __shared__ float placeholder_shared[18];
  float PaddedInput_shared_local[78];
  float placeholder_shared_local[18];
  float DepthwiseConv2d_local[22];
  PaddedInput_shared[(((int)threadIdx.x))] = 0.000000e+00f;
  PaddedInput_shared[((((int)threadIdx.x) + 11))] = ((((2 <= ((int)threadIdx.x)) && (1 <= ((((int)threadIdx.x) + 11) % 13))) && (((((int)threadIdx.x) + 11) % 13) < 12)) ? placeholder[(((((((int)blockIdx.z) * 242) + (((((int)threadIdx.x) + 11) / 13) * 11)) + ((((int)threadIdx.x) + 11) % 13)) - 12))] : 0.000000e+00f);
  PaddedInput_shared[((((int)threadIdx.x) + 22))] = (((1 <= ((((int)threadIdx.x) + 9) % 13)) && (((((int)threadIdx.x) + 9) % 13) < 12)) ? placeholder[(((((((int)blockIdx.z) * 242) + (((((int)threadIdx.x) + 22) / 13) * 11)) + ((((int)threadIdx.x) + 9) % 13)) - 12))] : 0.000000e+00f);
  PaddedInput_shared[((((int)threadIdx.x) + 33))] = (((1 <= ((((int)threadIdx.x) + 7) % 13)) && (((((int)threadIdx.x) + 7) % 13) < 12)) ? placeholder[(((((((int)blockIdx.z) * 242) + (((((int)threadIdx.x) + 33) / 13) * 11)) + ((((int)threadIdx.x) + 7) % 13)) - 12))] : 0.000000e+00f);
  PaddedInput_shared[((((int)threadIdx.x) + 44))] = (((1 <= ((((int)threadIdx.x) + 5) % 13)) && (((((int)threadIdx.x) + 5) % 13) < 12)) ? placeholder[(((((((int)blockIdx.z) * 242) + (((((int)threadIdx.x) + 44) / 13) * 11)) + ((((int)threadIdx.x) + 5) % 13)) - 12))] : 0.000000e+00f);
  PaddedInput_shared[((((int)threadIdx.x) + 55))] = (((1 <= ((((int)threadIdx.x) + 3) % 13)) && (((((int)threadIdx.x) + 3) % 13) < 12)) ? placeholder[(((((((int)blockIdx.z) * 242) + (((((int)threadIdx.x) + 55) / 13) * 11)) + ((((int)threadIdx.x) + 3) % 13)) - 12))] : 0.000000e+00f);
  PaddedInput_shared[((((int)threadIdx.x) + 66))] = placeholder[(((((((int)blockIdx.z) * 242) + (((((int)threadIdx.x) + 66) / 13) * 11)) + (((int)threadIdx.x) + 1)) - 12))];
  PaddedInput_shared[((((int)threadIdx.x) + 77))] = (((1 <= ((((int)threadIdx.x) + 12) % 13)) && (((((int)threadIdx.x) + 12) % 13) < 12)) ? placeholder[(((((((int)blockIdx.z) * 242) + (((((int)threadIdx.x) + 77) / 13) * 11)) + ((((int)threadIdx.x) + 12) % 13)) - 12))] : 0.000000e+00f);
  PaddedInput_shared[((((int)threadIdx.x) + 88))] = (((1 <= ((((int)threadIdx.x) + 10) % 13)) && (((((int)threadIdx.x) + 10) % 13) < 12)) ? placeholder[(((((((int)blockIdx.z) * 242) + (((((int)threadIdx.x) + 88) / 13) * 11)) + ((((int)threadIdx.x) + 10) % 13)) - 12))] : 0.000000e+00f);
  PaddedInput_shared[((((int)threadIdx.x) + 99))] = (((1 <= ((((int)threadIdx.x) + 8) % 13)) && (((((int)threadIdx.x) + 8) % 13) < 12)) ? placeholder[(((((((int)blockIdx.z) * 242) + (((((int)threadIdx.x) + 99) / 13) * 11)) + ((((int)threadIdx.x) + 8) % 13)) - 12))] : 0.000000e+00f);
  PaddedInput_shared[((((int)threadIdx.x) + 110))] = (((1 <= ((((int)threadIdx.x) + 6) % 13)) && (((((int)threadIdx.x) + 6) % 13) < 12)) ? placeholder[(((((((int)blockIdx.z) * 242) + (((((int)threadIdx.x) + 110) / 13) * 11)) + ((((int)threadIdx.x) + 6) % 13)) - 12))] : 0.000000e+00f);
  PaddedInput_shared[((((int)threadIdx.x) + 121))] = (((1 <= ((((int)threadIdx.x) + 4) % 13)) && (((((int)threadIdx.x) + 4) % 13) < 12)) ? placeholder[(((((((int)blockIdx.z) * 242) + (((((int)threadIdx.x) + 121) / 13) * 11)) + ((((int)threadIdx.x) + 4) % 13)) - 12))] : 0.000000e+00f);
  PaddedInput_shared[((((int)threadIdx.x) + 132))] = ((((int)threadIdx.x) < 10) ? placeholder[(((((((int)blockIdx.z) * 242) + (((((int)threadIdx.x) + 132) / 13) * 11)) + (((int)threadIdx.x) + 2)) - 12))] : 0.000000e+00f);
  PaddedInput_shared[((((int)threadIdx.x) + 143))] = ((1 <= ((int)threadIdx.x)) ? placeholder[((((((int)blockIdx.z) * 242) + ((int)threadIdx.x)) + 109))] : 0.000000e+00f);
  PaddedInput_shared[((((int)threadIdx.x) + 154))] = ((((((int)threadIdx.x) < 2) && (1 <= ((((int)threadIdx.x) + 11) % 13))) && (((((int)threadIdx.x) + 11) % 13) < 12)) ? placeholder[(((((((int)blockIdx.z) * 242) + (((((int)threadIdx.x) + 154) / 13) * 11)) + (((int)threadIdx.x) + 11)) - 12))] : 0.000000e+00f);
  PaddedInput_shared[((((int)threadIdx.x) + 165))] = (((((13 <= ((((int)threadIdx.x) + 165) % 169)) && (((((int)threadIdx.x) + 165) % 169) < 156)) && (1 <= ((((int)threadIdx.x) + 9) % 13))) && (((((int)threadIdx.x) + 9) % 13) < 12)) ? placeholder[((((((((int)blockIdx.z) * 242) + (((((int)threadIdx.x) + 165) / 169) * 121)) + ((((((int)threadIdx.x) + 165) % 169) / 13) * 11)) + ((((int)threadIdx.x) + 9) % 13)) - 12))] : 0.000000e+00f);
  PaddedInput_shared[((((int)threadIdx.x) + 176))] = ((((6 <= ((int)threadIdx.x)) && (1 <= ((((int)threadIdx.x) + 7) % 13))) && (((((int)threadIdx.x) + 7) % 13) < 12)) ? placeholder[((((((((int)blockIdx.z) * 242) + (((((int)threadIdx.x) + 176) / 169) * 121)) + (((((int)threadIdx.x) + 7) / 13) * 11)) + ((((int)threadIdx.x) + 7) % 13)) - 12))] : 0.000000e+00f);
  PaddedInput_shared[((((int)threadIdx.x) + 187))] = (((1 <= ((((int)threadIdx.x) + 5) % 13)) && (((((int)threadIdx.x) + 5) % 13) < 12)) ? placeholder[((((((((int)blockIdx.z) * 242) + (((((int)threadIdx.x) + 187) / 169) * 121)) + (((((int)threadIdx.x) + 18) / 13) * 11)) + ((((int)threadIdx.x) + 5) % 13)) - 12))] : 0.000000e+00f);
  PaddedInput_shared[((((int)threadIdx.x) + 198))] = (((1 <= ((((int)threadIdx.x) + 3) % 13)) && (((((int)threadIdx.x) + 3) % 13) < 12)) ? placeholder[((((((((int)blockIdx.z) * 242) + (((((int)threadIdx.x) + 198) / 169) * 121)) + (((((int)threadIdx.x) + 29) / 13) * 11)) + ((((int)threadIdx.x) + 3) % 13)) - 12))] : 0.000000e+00f);
  PaddedInput_shared[((((int)threadIdx.x) + 209))] = placeholder[((((((((int)blockIdx.z) * 242) + (((((int)threadIdx.x) + 209) / 169) * 121)) + (((((int)threadIdx.x) + 40) / 13) * 11)) + (((int)threadIdx.x) + 1)) - 12))];
  PaddedInput_shared[((((int)threadIdx.x) + 220))] = (((1 <= ((((int)threadIdx.x) + 12) % 13)) && (((((int)threadIdx.x) + 12) % 13) < 12)) ? placeholder[((((((((int)blockIdx.z) * 242) + (((((int)threadIdx.x) + 220) / 169) * 121)) + (((((int)threadIdx.x) + 51) / 13) * 11)) + ((((int)threadIdx.x) + 12) % 13)) - 12))] : 0.000000e+00f);
  PaddedInput_shared[((((int)threadIdx.x) + 231))] = (((1 <= ((((int)threadIdx.x) + 10) % 13)) && (((((int)threadIdx.x) + 10) % 13) < 12)) ? placeholder[((((((((int)blockIdx.z) * 242) + (((((int)threadIdx.x) + 231) / 169) * 121)) + (((((int)threadIdx.x) + 62) / 13) * 11)) + ((((int)threadIdx.x) + 10) % 13)) - 12))] : 0.000000e+00f);
  PaddedInput_shared[((((int)threadIdx.x) + 242))] = (((1 <= ((((int)threadIdx.x) + 8) % 13)) && (((((int)threadIdx.x) + 8) % 13) < 12)) ? placeholder[((((((((int)blockIdx.z) * 242) + (((((int)threadIdx.x) + 242) / 169) * 121)) + (((((int)threadIdx.x) + 73) / 13) * 11)) + ((((int)threadIdx.x) + 8) % 13)) - 12))] : 0.000000e+00f);
  PaddedInput_shared[((((int)threadIdx.x) + 253))] = (((1 <= ((((int)threadIdx.x) + 6) % 13)) && (((((int)threadIdx.x) + 6) % 13) < 12)) ? placeholder[((((((((int)blockIdx.z) * 242) + (((((int)threadIdx.x) + 253) / 169) * 121)) + (((((int)threadIdx.x) + 84) / 13) * 11)) + ((((int)threadIdx.x) + 6) % 13)) - 12))] : 0.000000e+00f);
  PaddedInput_shared[((((int)threadIdx.x) + 264))] = (((1 <= ((((int)threadIdx.x) + 4) % 13)) && (((((int)threadIdx.x) + 4) % 13) < 12)) ? placeholder[((((((((int)blockIdx.z) * 242) + (((((int)threadIdx.x) + 264) / 169) * 121)) + (((((int)threadIdx.x) + 95) / 13) * 11)) + ((((int)threadIdx.x) + 4) % 13)) - 12))] : 0.000000e+00f);
  PaddedInput_shared[((((int)threadIdx.x) + 275))] = ((((int)threadIdx.x) < 10) ? placeholder[((((((((int)blockIdx.z) * 242) + (((((int)threadIdx.x) + 275) / 169) * 121)) + (((((int)threadIdx.x) + 106) / 13) * 11)) + (((int)threadIdx.x) + 2)) - 12))] : 0.000000e+00f);
  PaddedInput_shared[((((int)threadIdx.x) + 286))] = ((1 <= ((int)threadIdx.x)) ? placeholder[((((((((int)blockIdx.z) * 242) + (((((int)threadIdx.x) + 286) / 169) * 121)) + (((((int)threadIdx.x) + 117) / 13) * 11)) + ((int)threadIdx.x)) - 12))] : 0.000000e+00f);
  PaddedInput_shared[((((int)threadIdx.x) + 297))] = (((1 <= ((((int)threadIdx.x) + 11) % 13)) && (((((int)threadIdx.x) + 11) % 13) < 12)) ? placeholder[((((((((int)blockIdx.z) * 242) + (((((int)threadIdx.x) + 297) / 169) * 121)) + (((((int)threadIdx.x) + 128) / 13) * 11)) + ((((int)threadIdx.x) + 11) % 13)) - 12))] : 0.000000e+00f);
  PaddedInput_shared[((((int)threadIdx.x) + 308))] = (((1 <= ((((int)threadIdx.x) + 9) % 13)) && (((((int)threadIdx.x) + 9) % 13) < 12)) ? placeholder[((((((((int)blockIdx.z) * 242) + (((((int)threadIdx.x) + 308) / 169) * 121)) + (((((int)threadIdx.x) + 139) / 13) * 11)) + ((((int)threadIdx.x) + 9) % 13)) - 12))] : 0.000000e+00f);
  PaddedInput_shared[((((int)threadIdx.x) + 319))] = ((((((int)threadIdx.x) < 6) && (1 <= ((((int)threadIdx.x) + 7) % 13))) && (((((int)threadIdx.x) + 7) % 13) < 12)) ? placeholder[((((((((int)blockIdx.z) * 242) + (((((int)threadIdx.x) + 319) / 169) * 121)) + (((((int)threadIdx.x) + 150) / 13) * 11)) + (((int)threadIdx.x) + 7)) - 12))] : 0.000000e+00f);
  if (((int)threadIdx.x) < 8) {
    PaddedInput_shared[((((int)threadIdx.x) + 330))] = 0.000000e+00f;
  }
  placeholder_shared[(((int)threadIdx.x))] = placeholder1[((((((int)blockIdx.z) % 336) * 18) + ((int)threadIdx.x)))];
  if (((int)threadIdx.x) < 7) {
    placeholder_shared[((((int)threadIdx.x) + 11))] = placeholder1[(((((((int)blockIdx.z) % 336) * 18) + ((int)threadIdx.x)) + 11))];
  }
  __syncthreads();
  PaddedInput_shared_local[(0)] = PaddedInput_shared[(((int)threadIdx.x))];
  PaddedInput_shared_local[(39)] = PaddedInput_shared[((((int)threadIdx.x) + 169))];
  PaddedInput_shared_local[(1)] = PaddedInput_shared[((((int)threadIdx.x) + 1))];
  PaddedInput_shared_local[(40)] = PaddedInput_shared[((((int)threadIdx.x) + 170))];
  PaddedInput_shared_local[(2)] = PaddedInput_shared[((((int)threadIdx.x) + 2))];
  PaddedInput_shared_local[(41)] = PaddedInput_shared[((((int)threadIdx.x) + 171))];
  PaddedInput_shared_local[(3)] = PaddedInput_shared[((((int)threadIdx.x) + 13))];
  PaddedInput_shared_local[(42)] = PaddedInput_shared[((((int)threadIdx.x) + 182))];
  PaddedInput_shared_local[(4)] = PaddedInput_shared[((((int)threadIdx.x) + 14))];
  PaddedInput_shared_local[(43)] = PaddedInput_shared[((((int)threadIdx.x) + 183))];
  PaddedInput_shared_local[(5)] = PaddedInput_shared[((((int)threadIdx.x) + 15))];
  PaddedInput_shared_local[(44)] = PaddedInput_shared[((((int)threadIdx.x) + 184))];
  PaddedInput_shared_local[(6)] = PaddedInput_shared[((((int)threadIdx.x) + 26))];
  PaddedInput_shared_local[(45)] = PaddedInput_shared[((((int)threadIdx.x) + 195))];
  PaddedInput_shared_local[(7)] = PaddedInput_shared[((((int)threadIdx.x) + 27))];
  PaddedInput_shared_local[(46)] = PaddedInput_shared[((((int)threadIdx.x) + 196))];
  PaddedInput_shared_local[(8)] = PaddedInput_shared[((((int)threadIdx.x) + 28))];
  PaddedInput_shared_local[(47)] = PaddedInput_shared[((((int)threadIdx.x) + 197))];
  PaddedInput_shared_local[(9)] = PaddedInput_shared[((((int)threadIdx.x) + 39))];
  PaddedInput_shared_local[(48)] = PaddedInput_shared[((((int)threadIdx.x) + 208))];
  PaddedInput_shared_local[(10)] = PaddedInput_shared[((((int)threadIdx.x) + 40))];
  PaddedInput_shared_local[(49)] = PaddedInput_shared[((((int)threadIdx.x) + 209))];
  PaddedInput_shared_local[(11)] = PaddedInput_shared[((((int)threadIdx.x) + 41))];
  PaddedInput_shared_local[(50)] = PaddedInput_shared[((((int)threadIdx.x) + 210))];
  PaddedInput_shared_local[(12)] = PaddedInput_shared[((((int)threadIdx.x) + 52))];
  PaddedInput_shared_local[(51)] = PaddedInput_shared[((((int)threadIdx.x) + 221))];
  PaddedInput_shared_local[(13)] = PaddedInput_shared[((((int)threadIdx.x) + 53))];
  PaddedInput_shared_local[(52)] = PaddedInput_shared[((((int)threadIdx.x) + 222))];
  PaddedInput_shared_local[(14)] = PaddedInput_shared[((((int)threadIdx.x) + 54))];
  PaddedInput_shared_local[(53)] = PaddedInput_shared[((((int)threadIdx.x) + 223))];
  PaddedInput_shared_local[(15)] = PaddedInput_shared[((((int)threadIdx.x) + 65))];
  PaddedInput_shared_local[(54)] = PaddedInput_shared[((((int)threadIdx.x) + 234))];
  PaddedInput_shared_local[(16)] = PaddedInput_shared[((((int)threadIdx.x) + 66))];
  PaddedInput_shared_local[(55)] = PaddedInput_shared[((((int)threadIdx.x) + 235))];
  PaddedInput_shared_local[(17)] = PaddedInput_shared[((((int)threadIdx.x) + 67))];
  PaddedInput_shared_local[(56)] = PaddedInput_shared[((((int)threadIdx.x) + 236))];
  PaddedInput_shared_local[(18)] = PaddedInput_shared[((((int)threadIdx.x) + 78))];
  PaddedInput_shared_local[(57)] = PaddedInput_shared[((((int)threadIdx.x) + 247))];
  PaddedInput_shared_local[(19)] = PaddedInput_shared[((((int)threadIdx.x) + 79))];
  PaddedInput_shared_local[(58)] = PaddedInput_shared[((((int)threadIdx.x) + 248))];
  PaddedInput_shared_local[(20)] = PaddedInput_shared[((((int)threadIdx.x) + 80))];
  PaddedInput_shared_local[(59)] = PaddedInput_shared[((((int)threadIdx.x) + 249))];
  PaddedInput_shared_local[(21)] = PaddedInput_shared[((((int)threadIdx.x) + 91))];
  PaddedInput_shared_local[(60)] = PaddedInput_shared[((((int)threadIdx.x) + 260))];
  PaddedInput_shared_local[(22)] = PaddedInput_shared[((((int)threadIdx.x) + 92))];
  PaddedInput_shared_local[(61)] = PaddedInput_shared[((((int)threadIdx.x) + 261))];
  PaddedInput_shared_local[(23)] = PaddedInput_shared[((((int)threadIdx.x) + 93))];
  PaddedInput_shared_local[(62)] = PaddedInput_shared[((((int)threadIdx.x) + 262))];
  PaddedInput_shared_local[(24)] = PaddedInput_shared[((((int)threadIdx.x) + 104))];
  PaddedInput_shared_local[(63)] = PaddedInput_shared[((((int)threadIdx.x) + 273))];
  PaddedInput_shared_local[(25)] = PaddedInput_shared[((((int)threadIdx.x) + 105))];
  PaddedInput_shared_local[(64)] = PaddedInput_shared[((((int)threadIdx.x) + 274))];
  PaddedInput_shared_local[(26)] = PaddedInput_shared[((((int)threadIdx.x) + 106))];
  PaddedInput_shared_local[(65)] = PaddedInput_shared[((((int)threadIdx.x) + 275))];
  PaddedInput_shared_local[(27)] = PaddedInput_shared[((((int)threadIdx.x) + 117))];
  PaddedInput_shared_local[(66)] = PaddedInput_shared[((((int)threadIdx.x) + 286))];
  PaddedInput_shared_local[(28)] = PaddedInput_shared[((((int)threadIdx.x) + 118))];
  PaddedInput_shared_local[(67)] = PaddedInput_shared[((((int)threadIdx.x) + 287))];
  PaddedInput_shared_local[(29)] = PaddedInput_shared[((((int)threadIdx.x) + 119))];
  PaddedInput_shared_local[(68)] = PaddedInput_shared[((((int)threadIdx.x) + 288))];
  PaddedInput_shared_local[(30)] = PaddedInput_shared[((((int)threadIdx.x) + 130))];
  PaddedInput_shared_local[(69)] = PaddedInput_shared[((((int)threadIdx.x) + 299))];
  PaddedInput_shared_local[(31)] = PaddedInput_shared[((((int)threadIdx.x) + 131))];
  PaddedInput_shared_local[(70)] = PaddedInput_shared[((((int)threadIdx.x) + 300))];
  PaddedInput_shared_local[(32)] = PaddedInput_shared[((((int)threadIdx.x) + 132))];
  PaddedInput_shared_local[(71)] = PaddedInput_shared[((((int)threadIdx.x) + 301))];
  PaddedInput_shared_local[(33)] = PaddedInput_shared[((((int)threadIdx.x) + 143))];
  PaddedInput_shared_local[(72)] = PaddedInput_shared[((((int)threadIdx.x) + 312))];
  PaddedInput_shared_local[(34)] = PaddedInput_shared[((((int)threadIdx.x) + 144))];
  PaddedInput_shared_local[(73)] = PaddedInput_shared[((((int)threadIdx.x) + 313))];
  PaddedInput_shared_local[(35)] = PaddedInput_shared[((((int)threadIdx.x) + 145))];
  PaddedInput_shared_local[(74)] = PaddedInput_shared[((((int)threadIdx.x) + 314))];
  PaddedInput_shared_local[(36)] = PaddedInput_shared[((((int)threadIdx.x) + 156))];
  PaddedInput_shared_local[(75)] = PaddedInput_shared[((((int)threadIdx.x) + 325))];
  PaddedInput_shared_local[(37)] = PaddedInput_shared[((((int)threadIdx.x) + 157))];
  PaddedInput_shared_local[(76)] = PaddedInput_shared[((((int)threadIdx.x) + 326))];
  PaddedInput_shared_local[(38)] = PaddedInput_shared[((((int)threadIdx.x) + 158))];
  PaddedInput_shared_local[(77)] = PaddedInput_shared[((((int)threadIdx.x) + 327))];
  placeholder_shared_local[(0)] = placeholder_shared[(0)];
  placeholder_shared_local[(9)] = placeholder_shared[(9)];
  placeholder_shared_local[(1)] = placeholder_shared[(1)];
  placeholder_shared_local[(10)] = placeholder_shared[(10)];
  placeholder_shared_local[(2)] = placeholder_shared[(2)];
  placeholder_shared_local[(11)] = placeholder_shared[(11)];
  placeholder_shared_local[(3)] = placeholder_shared[(3)];
  placeholder_shared_local[(12)] = placeholder_shared[(12)];
  placeholder_shared_local[(4)] = placeholder_shared[(4)];
  placeholder_shared_local[(13)] = placeholder_shared[(13)];
  placeholder_shared_local[(5)] = placeholder_shared[(5)];
  placeholder_shared_local[(14)] = placeholder_shared[(14)];
  placeholder_shared_local[(6)] = placeholder_shared[(6)];
  placeholder_shared_local[(15)] = placeholder_shared[(15)];
  placeholder_shared_local[(7)] = placeholder_shared[(7)];
  placeholder_shared_local[(16)] = placeholder_shared[(16)];
  placeholder_shared_local[(8)] = placeholder_shared[(8)];
  placeholder_shared_local[(17)] = placeholder_shared[(17)];
  DepthwiseConv2d_local[(0)] = 0.000000e+00f;
  DepthwiseConv2d_local[(11)] = 0.000000e+00f;
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(0)] * placeholder_shared_local[(0)]));
  DepthwiseConv2d_local[(11)] = (DepthwiseConv2d_local[(11)] + (PaddedInput_shared_local[(39)] * placeholder_shared_local[(9)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(1)] * placeholder_shared_local[(1)]));
  DepthwiseConv2d_local[(11)] = (DepthwiseConv2d_local[(11)] + (PaddedInput_shared_local[(40)] * placeholder_shared_local[(10)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(2)] * placeholder_shared_local[(2)]));
  DepthwiseConv2d_local[(11)] = (DepthwiseConv2d_local[(11)] + (PaddedInput_shared_local[(41)] * placeholder_shared_local[(11)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(3)] * placeholder_shared_local[(3)]));
  DepthwiseConv2d_local[(11)] = (DepthwiseConv2d_local[(11)] + (PaddedInput_shared_local[(42)] * placeholder_shared_local[(12)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(4)] * placeholder_shared_local[(4)]));
  DepthwiseConv2d_local[(11)] = (DepthwiseConv2d_local[(11)] + (PaddedInput_shared_local[(43)] * placeholder_shared_local[(13)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(5)] * placeholder_shared_local[(5)]));
  DepthwiseConv2d_local[(11)] = (DepthwiseConv2d_local[(11)] + (PaddedInput_shared_local[(44)] * placeholder_shared_local[(14)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(6)] * placeholder_shared_local[(6)]));
  DepthwiseConv2d_local[(11)] = (DepthwiseConv2d_local[(11)] + (PaddedInput_shared_local[(45)] * placeholder_shared_local[(15)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(7)] * placeholder_shared_local[(7)]));
  DepthwiseConv2d_local[(11)] = (DepthwiseConv2d_local[(11)] + (PaddedInput_shared_local[(46)] * placeholder_shared_local[(16)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared_local[(8)] * placeholder_shared_local[(8)]));
  DepthwiseConv2d_local[(11)] = (DepthwiseConv2d_local[(11)] + (PaddedInput_shared_local[(47)] * placeholder_shared_local[(17)]));
  DepthwiseConv2d_local[(1)] = 0.000000e+00f;
  DepthwiseConv2d_local[(12)] = 0.000000e+00f;
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(3)] * placeholder_shared_local[(0)]));
  DepthwiseConv2d_local[(12)] = (DepthwiseConv2d_local[(12)] + (PaddedInput_shared_local[(42)] * placeholder_shared_local[(9)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(4)] * placeholder_shared_local[(1)]));
  DepthwiseConv2d_local[(12)] = (DepthwiseConv2d_local[(12)] + (PaddedInput_shared_local[(43)] * placeholder_shared_local[(10)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(5)] * placeholder_shared_local[(2)]));
  DepthwiseConv2d_local[(12)] = (DepthwiseConv2d_local[(12)] + (PaddedInput_shared_local[(44)] * placeholder_shared_local[(11)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(6)] * placeholder_shared_local[(3)]));
  DepthwiseConv2d_local[(12)] = (DepthwiseConv2d_local[(12)] + (PaddedInput_shared_local[(45)] * placeholder_shared_local[(12)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(7)] * placeholder_shared_local[(4)]));
  DepthwiseConv2d_local[(12)] = (DepthwiseConv2d_local[(12)] + (PaddedInput_shared_local[(46)] * placeholder_shared_local[(13)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(8)] * placeholder_shared_local[(5)]));
  DepthwiseConv2d_local[(12)] = (DepthwiseConv2d_local[(12)] + (PaddedInput_shared_local[(47)] * placeholder_shared_local[(14)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(9)] * placeholder_shared_local[(6)]));
  DepthwiseConv2d_local[(12)] = (DepthwiseConv2d_local[(12)] + (PaddedInput_shared_local[(48)] * placeholder_shared_local[(15)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(10)] * placeholder_shared_local[(7)]));
  DepthwiseConv2d_local[(12)] = (DepthwiseConv2d_local[(12)] + (PaddedInput_shared_local[(49)] * placeholder_shared_local[(16)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared_local[(11)] * placeholder_shared_local[(8)]));
  DepthwiseConv2d_local[(12)] = (DepthwiseConv2d_local[(12)] + (PaddedInput_shared_local[(50)] * placeholder_shared_local[(17)]));
  DepthwiseConv2d_local[(2)] = 0.000000e+00f;
  DepthwiseConv2d_local[(13)] = 0.000000e+00f;
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(6)] * placeholder_shared_local[(0)]));
  DepthwiseConv2d_local[(13)] = (DepthwiseConv2d_local[(13)] + (PaddedInput_shared_local[(45)] * placeholder_shared_local[(9)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(7)] * placeholder_shared_local[(1)]));
  DepthwiseConv2d_local[(13)] = (DepthwiseConv2d_local[(13)] + (PaddedInput_shared_local[(46)] * placeholder_shared_local[(10)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(8)] * placeholder_shared_local[(2)]));
  DepthwiseConv2d_local[(13)] = (DepthwiseConv2d_local[(13)] + (PaddedInput_shared_local[(47)] * placeholder_shared_local[(11)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(9)] * placeholder_shared_local[(3)]));
  DepthwiseConv2d_local[(13)] = (DepthwiseConv2d_local[(13)] + (PaddedInput_shared_local[(48)] * placeholder_shared_local[(12)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(10)] * placeholder_shared_local[(4)]));
  DepthwiseConv2d_local[(13)] = (DepthwiseConv2d_local[(13)] + (PaddedInput_shared_local[(49)] * placeholder_shared_local[(13)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(11)] * placeholder_shared_local[(5)]));
  DepthwiseConv2d_local[(13)] = (DepthwiseConv2d_local[(13)] + (PaddedInput_shared_local[(50)] * placeholder_shared_local[(14)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(12)] * placeholder_shared_local[(6)]));
  DepthwiseConv2d_local[(13)] = (DepthwiseConv2d_local[(13)] + (PaddedInput_shared_local[(51)] * placeholder_shared_local[(15)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(13)] * placeholder_shared_local[(7)]));
  DepthwiseConv2d_local[(13)] = (DepthwiseConv2d_local[(13)] + (PaddedInput_shared_local[(52)] * placeholder_shared_local[(16)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared_local[(14)] * placeholder_shared_local[(8)]));
  DepthwiseConv2d_local[(13)] = (DepthwiseConv2d_local[(13)] + (PaddedInput_shared_local[(53)] * placeholder_shared_local[(17)]));
  DepthwiseConv2d_local[(3)] = 0.000000e+00f;
  DepthwiseConv2d_local[(14)] = 0.000000e+00f;
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(9)] * placeholder_shared_local[(0)]));
  DepthwiseConv2d_local[(14)] = (DepthwiseConv2d_local[(14)] + (PaddedInput_shared_local[(48)] * placeholder_shared_local[(9)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(10)] * placeholder_shared_local[(1)]));
  DepthwiseConv2d_local[(14)] = (DepthwiseConv2d_local[(14)] + (PaddedInput_shared_local[(49)] * placeholder_shared_local[(10)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(11)] * placeholder_shared_local[(2)]));
  DepthwiseConv2d_local[(14)] = (DepthwiseConv2d_local[(14)] + (PaddedInput_shared_local[(50)] * placeholder_shared_local[(11)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(12)] * placeholder_shared_local[(3)]));
  DepthwiseConv2d_local[(14)] = (DepthwiseConv2d_local[(14)] + (PaddedInput_shared_local[(51)] * placeholder_shared_local[(12)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(13)] * placeholder_shared_local[(4)]));
  DepthwiseConv2d_local[(14)] = (DepthwiseConv2d_local[(14)] + (PaddedInput_shared_local[(52)] * placeholder_shared_local[(13)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(14)] * placeholder_shared_local[(5)]));
  DepthwiseConv2d_local[(14)] = (DepthwiseConv2d_local[(14)] + (PaddedInput_shared_local[(53)] * placeholder_shared_local[(14)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(15)] * placeholder_shared_local[(6)]));
  DepthwiseConv2d_local[(14)] = (DepthwiseConv2d_local[(14)] + (PaddedInput_shared_local[(54)] * placeholder_shared_local[(15)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(16)] * placeholder_shared_local[(7)]));
  DepthwiseConv2d_local[(14)] = (DepthwiseConv2d_local[(14)] + (PaddedInput_shared_local[(55)] * placeholder_shared_local[(16)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared_local[(17)] * placeholder_shared_local[(8)]));
  DepthwiseConv2d_local[(14)] = (DepthwiseConv2d_local[(14)] + (PaddedInput_shared_local[(56)] * placeholder_shared_local[(17)]));
  DepthwiseConv2d_local[(4)] = 0.000000e+00f;
  DepthwiseConv2d_local[(15)] = 0.000000e+00f;
  DepthwiseConv2d_local[(4)] = (DepthwiseConv2d_local[(4)] + (PaddedInput_shared_local[(12)] * placeholder_shared_local[(0)]));
  DepthwiseConv2d_local[(15)] = (DepthwiseConv2d_local[(15)] + (PaddedInput_shared_local[(51)] * placeholder_shared_local[(9)]));
  DepthwiseConv2d_local[(4)] = (DepthwiseConv2d_local[(4)] + (PaddedInput_shared_local[(13)] * placeholder_shared_local[(1)]));
  DepthwiseConv2d_local[(15)] = (DepthwiseConv2d_local[(15)] + (PaddedInput_shared_local[(52)] * placeholder_shared_local[(10)]));
  DepthwiseConv2d_local[(4)] = (DepthwiseConv2d_local[(4)] + (PaddedInput_shared_local[(14)] * placeholder_shared_local[(2)]));
  DepthwiseConv2d_local[(15)] = (DepthwiseConv2d_local[(15)] + (PaddedInput_shared_local[(53)] * placeholder_shared_local[(11)]));
  DepthwiseConv2d_local[(4)] = (DepthwiseConv2d_local[(4)] + (PaddedInput_shared_local[(15)] * placeholder_shared_local[(3)]));
  DepthwiseConv2d_local[(15)] = (DepthwiseConv2d_local[(15)] + (PaddedInput_shared_local[(54)] * placeholder_shared_local[(12)]));
  DepthwiseConv2d_local[(4)] = (DepthwiseConv2d_local[(4)] + (PaddedInput_shared_local[(16)] * placeholder_shared_local[(4)]));
  DepthwiseConv2d_local[(15)] = (DepthwiseConv2d_local[(15)] + (PaddedInput_shared_local[(55)] * placeholder_shared_local[(13)]));
  DepthwiseConv2d_local[(4)] = (DepthwiseConv2d_local[(4)] + (PaddedInput_shared_local[(17)] * placeholder_shared_local[(5)]));
  DepthwiseConv2d_local[(15)] = (DepthwiseConv2d_local[(15)] + (PaddedInput_shared_local[(56)] * placeholder_shared_local[(14)]));
  DepthwiseConv2d_local[(4)] = (DepthwiseConv2d_local[(4)] + (PaddedInput_shared_local[(18)] * placeholder_shared_local[(6)]));
  DepthwiseConv2d_local[(15)] = (DepthwiseConv2d_local[(15)] + (PaddedInput_shared_local[(57)] * placeholder_shared_local[(15)]));
  DepthwiseConv2d_local[(4)] = (DepthwiseConv2d_local[(4)] + (PaddedInput_shared_local[(19)] * placeholder_shared_local[(7)]));
  DepthwiseConv2d_local[(15)] = (DepthwiseConv2d_local[(15)] + (PaddedInput_shared_local[(58)] * placeholder_shared_local[(16)]));
  DepthwiseConv2d_local[(4)] = (DepthwiseConv2d_local[(4)] + (PaddedInput_shared_local[(20)] * placeholder_shared_local[(8)]));
  DepthwiseConv2d_local[(15)] = (DepthwiseConv2d_local[(15)] + (PaddedInput_shared_local[(59)] * placeholder_shared_local[(17)]));
  DepthwiseConv2d_local[(5)] = 0.000000e+00f;
  DepthwiseConv2d_local[(16)] = 0.000000e+00f;
  DepthwiseConv2d_local[(5)] = (DepthwiseConv2d_local[(5)] + (PaddedInput_shared_local[(15)] * placeholder_shared_local[(0)]));
  DepthwiseConv2d_local[(16)] = (DepthwiseConv2d_local[(16)] + (PaddedInput_shared_local[(54)] * placeholder_shared_local[(9)]));
  DepthwiseConv2d_local[(5)] = (DepthwiseConv2d_local[(5)] + (PaddedInput_shared_local[(16)] * placeholder_shared_local[(1)]));
  DepthwiseConv2d_local[(16)] = (DepthwiseConv2d_local[(16)] + (PaddedInput_shared_local[(55)] * placeholder_shared_local[(10)]));
  DepthwiseConv2d_local[(5)] = (DepthwiseConv2d_local[(5)] + (PaddedInput_shared_local[(17)] * placeholder_shared_local[(2)]));
  DepthwiseConv2d_local[(16)] = (DepthwiseConv2d_local[(16)] + (PaddedInput_shared_local[(56)] * placeholder_shared_local[(11)]));
  DepthwiseConv2d_local[(5)] = (DepthwiseConv2d_local[(5)] + (PaddedInput_shared_local[(18)] * placeholder_shared_local[(3)]));
  DepthwiseConv2d_local[(16)] = (DepthwiseConv2d_local[(16)] + (PaddedInput_shared_local[(57)] * placeholder_shared_local[(12)]));
  DepthwiseConv2d_local[(5)] = (DepthwiseConv2d_local[(5)] + (PaddedInput_shared_local[(19)] * placeholder_shared_local[(4)]));
  DepthwiseConv2d_local[(16)] = (DepthwiseConv2d_local[(16)] + (PaddedInput_shared_local[(58)] * placeholder_shared_local[(13)]));
  DepthwiseConv2d_local[(5)] = (DepthwiseConv2d_local[(5)] + (PaddedInput_shared_local[(20)] * placeholder_shared_local[(5)]));
  DepthwiseConv2d_local[(16)] = (DepthwiseConv2d_local[(16)] + (PaddedInput_shared_local[(59)] * placeholder_shared_local[(14)]));
  DepthwiseConv2d_local[(5)] = (DepthwiseConv2d_local[(5)] + (PaddedInput_shared_local[(21)] * placeholder_shared_local[(6)]));
  DepthwiseConv2d_local[(16)] = (DepthwiseConv2d_local[(16)] + (PaddedInput_shared_local[(60)] * placeholder_shared_local[(15)]));
  DepthwiseConv2d_local[(5)] = (DepthwiseConv2d_local[(5)] + (PaddedInput_shared_local[(22)] * placeholder_shared_local[(7)]));
  DepthwiseConv2d_local[(16)] = (DepthwiseConv2d_local[(16)] + (PaddedInput_shared_local[(61)] * placeholder_shared_local[(16)]));
  DepthwiseConv2d_local[(5)] = (DepthwiseConv2d_local[(5)] + (PaddedInput_shared_local[(23)] * placeholder_shared_local[(8)]));
  DepthwiseConv2d_local[(16)] = (DepthwiseConv2d_local[(16)] + (PaddedInput_shared_local[(62)] * placeholder_shared_local[(17)]));
  DepthwiseConv2d_local[(6)] = 0.000000e+00f;
  DepthwiseConv2d_local[(17)] = 0.000000e+00f;
  DepthwiseConv2d_local[(6)] = (DepthwiseConv2d_local[(6)] + (PaddedInput_shared_local[(18)] * placeholder_shared_local[(0)]));
  DepthwiseConv2d_local[(17)] = (DepthwiseConv2d_local[(17)] + (PaddedInput_shared_local[(57)] * placeholder_shared_local[(9)]));
  DepthwiseConv2d_local[(6)] = (DepthwiseConv2d_local[(6)] + (PaddedInput_shared_local[(19)] * placeholder_shared_local[(1)]));
  DepthwiseConv2d_local[(17)] = (DepthwiseConv2d_local[(17)] + (PaddedInput_shared_local[(58)] * placeholder_shared_local[(10)]));
  DepthwiseConv2d_local[(6)] = (DepthwiseConv2d_local[(6)] + (PaddedInput_shared_local[(20)] * placeholder_shared_local[(2)]));
  DepthwiseConv2d_local[(17)] = (DepthwiseConv2d_local[(17)] + (PaddedInput_shared_local[(59)] * placeholder_shared_local[(11)]));
  DepthwiseConv2d_local[(6)] = (DepthwiseConv2d_local[(6)] + (PaddedInput_shared_local[(21)] * placeholder_shared_local[(3)]));
  DepthwiseConv2d_local[(17)] = (DepthwiseConv2d_local[(17)] + (PaddedInput_shared_local[(60)] * placeholder_shared_local[(12)]));
  DepthwiseConv2d_local[(6)] = (DepthwiseConv2d_local[(6)] + (PaddedInput_shared_local[(22)] * placeholder_shared_local[(4)]));
  DepthwiseConv2d_local[(17)] = (DepthwiseConv2d_local[(17)] + (PaddedInput_shared_local[(61)] * placeholder_shared_local[(13)]));
  DepthwiseConv2d_local[(6)] = (DepthwiseConv2d_local[(6)] + (PaddedInput_shared_local[(23)] * placeholder_shared_local[(5)]));
  DepthwiseConv2d_local[(17)] = (DepthwiseConv2d_local[(17)] + (PaddedInput_shared_local[(62)] * placeholder_shared_local[(14)]));
  DepthwiseConv2d_local[(6)] = (DepthwiseConv2d_local[(6)] + (PaddedInput_shared_local[(24)] * placeholder_shared_local[(6)]));
  DepthwiseConv2d_local[(17)] = (DepthwiseConv2d_local[(17)] + (PaddedInput_shared_local[(63)] * placeholder_shared_local[(15)]));
  DepthwiseConv2d_local[(6)] = (DepthwiseConv2d_local[(6)] + (PaddedInput_shared_local[(25)] * placeholder_shared_local[(7)]));
  DepthwiseConv2d_local[(17)] = (DepthwiseConv2d_local[(17)] + (PaddedInput_shared_local[(64)] * placeholder_shared_local[(16)]));
  DepthwiseConv2d_local[(6)] = (DepthwiseConv2d_local[(6)] + (PaddedInput_shared_local[(26)] * placeholder_shared_local[(8)]));
  DepthwiseConv2d_local[(17)] = (DepthwiseConv2d_local[(17)] + (PaddedInput_shared_local[(65)] * placeholder_shared_local[(17)]));
  DepthwiseConv2d_local[(7)] = 0.000000e+00f;
  DepthwiseConv2d_local[(18)] = 0.000000e+00f;
  DepthwiseConv2d_local[(7)] = (DepthwiseConv2d_local[(7)] + (PaddedInput_shared_local[(21)] * placeholder_shared_local[(0)]));
  DepthwiseConv2d_local[(18)] = (DepthwiseConv2d_local[(18)] + (PaddedInput_shared_local[(60)] * placeholder_shared_local[(9)]));
  DepthwiseConv2d_local[(7)] = (DepthwiseConv2d_local[(7)] + (PaddedInput_shared_local[(22)] * placeholder_shared_local[(1)]));
  DepthwiseConv2d_local[(18)] = (DepthwiseConv2d_local[(18)] + (PaddedInput_shared_local[(61)] * placeholder_shared_local[(10)]));
  DepthwiseConv2d_local[(7)] = (DepthwiseConv2d_local[(7)] + (PaddedInput_shared_local[(23)] * placeholder_shared_local[(2)]));
  DepthwiseConv2d_local[(18)] = (DepthwiseConv2d_local[(18)] + (PaddedInput_shared_local[(62)] * placeholder_shared_local[(11)]));
  DepthwiseConv2d_local[(7)] = (DepthwiseConv2d_local[(7)] + (PaddedInput_shared_local[(24)] * placeholder_shared_local[(3)]));
  DepthwiseConv2d_local[(18)] = (DepthwiseConv2d_local[(18)] + (PaddedInput_shared_local[(63)] * placeholder_shared_local[(12)]));
  DepthwiseConv2d_local[(7)] = (DepthwiseConv2d_local[(7)] + (PaddedInput_shared_local[(25)] * placeholder_shared_local[(4)]));
  DepthwiseConv2d_local[(18)] = (DepthwiseConv2d_local[(18)] + (PaddedInput_shared_local[(64)] * placeholder_shared_local[(13)]));
  DepthwiseConv2d_local[(7)] = (DepthwiseConv2d_local[(7)] + (PaddedInput_shared_local[(26)] * placeholder_shared_local[(5)]));
  DepthwiseConv2d_local[(18)] = (DepthwiseConv2d_local[(18)] + (PaddedInput_shared_local[(65)] * placeholder_shared_local[(14)]));
  DepthwiseConv2d_local[(7)] = (DepthwiseConv2d_local[(7)] + (PaddedInput_shared_local[(27)] * placeholder_shared_local[(6)]));
  DepthwiseConv2d_local[(18)] = (DepthwiseConv2d_local[(18)] + (PaddedInput_shared_local[(66)] * placeholder_shared_local[(15)]));
  DepthwiseConv2d_local[(7)] = (DepthwiseConv2d_local[(7)] + (PaddedInput_shared_local[(28)] * placeholder_shared_local[(7)]));
  DepthwiseConv2d_local[(18)] = (DepthwiseConv2d_local[(18)] + (PaddedInput_shared_local[(67)] * placeholder_shared_local[(16)]));
  DepthwiseConv2d_local[(7)] = (DepthwiseConv2d_local[(7)] + (PaddedInput_shared_local[(29)] * placeholder_shared_local[(8)]));
  DepthwiseConv2d_local[(18)] = (DepthwiseConv2d_local[(18)] + (PaddedInput_shared_local[(68)] * placeholder_shared_local[(17)]));
  DepthwiseConv2d_local[(8)] = 0.000000e+00f;
  DepthwiseConv2d_local[(19)] = 0.000000e+00f;
  DepthwiseConv2d_local[(8)] = (DepthwiseConv2d_local[(8)] + (PaddedInput_shared_local[(24)] * placeholder_shared_local[(0)]));
  DepthwiseConv2d_local[(19)] = (DepthwiseConv2d_local[(19)] + (PaddedInput_shared_local[(63)] * placeholder_shared_local[(9)]));
  DepthwiseConv2d_local[(8)] = (DepthwiseConv2d_local[(8)] + (PaddedInput_shared_local[(25)] * placeholder_shared_local[(1)]));
  DepthwiseConv2d_local[(19)] = (DepthwiseConv2d_local[(19)] + (PaddedInput_shared_local[(64)] * placeholder_shared_local[(10)]));
  DepthwiseConv2d_local[(8)] = (DepthwiseConv2d_local[(8)] + (PaddedInput_shared_local[(26)] * placeholder_shared_local[(2)]));
  DepthwiseConv2d_local[(19)] = (DepthwiseConv2d_local[(19)] + (PaddedInput_shared_local[(65)] * placeholder_shared_local[(11)]));
  DepthwiseConv2d_local[(8)] = (DepthwiseConv2d_local[(8)] + (PaddedInput_shared_local[(27)] * placeholder_shared_local[(3)]));
  DepthwiseConv2d_local[(19)] = (DepthwiseConv2d_local[(19)] + (PaddedInput_shared_local[(66)] * placeholder_shared_local[(12)]));
  DepthwiseConv2d_local[(8)] = (DepthwiseConv2d_local[(8)] + (PaddedInput_shared_local[(28)] * placeholder_shared_local[(4)]));
  DepthwiseConv2d_local[(19)] = (DepthwiseConv2d_local[(19)] + (PaddedInput_shared_local[(67)] * placeholder_shared_local[(13)]));
  DepthwiseConv2d_local[(8)] = (DepthwiseConv2d_local[(8)] + (PaddedInput_shared_local[(29)] * placeholder_shared_local[(5)]));
  DepthwiseConv2d_local[(19)] = (DepthwiseConv2d_local[(19)] + (PaddedInput_shared_local[(68)] * placeholder_shared_local[(14)]));
  DepthwiseConv2d_local[(8)] = (DepthwiseConv2d_local[(8)] + (PaddedInput_shared_local[(30)] * placeholder_shared_local[(6)]));
  DepthwiseConv2d_local[(19)] = (DepthwiseConv2d_local[(19)] + (PaddedInput_shared_local[(69)] * placeholder_shared_local[(15)]));
  DepthwiseConv2d_local[(8)] = (DepthwiseConv2d_local[(8)] + (PaddedInput_shared_local[(31)] * placeholder_shared_local[(7)]));
  DepthwiseConv2d_local[(19)] = (DepthwiseConv2d_local[(19)] + (PaddedInput_shared_local[(70)] * placeholder_shared_local[(16)]));
  DepthwiseConv2d_local[(8)] = (DepthwiseConv2d_local[(8)] + (PaddedInput_shared_local[(32)] * placeholder_shared_local[(8)]));
  DepthwiseConv2d_local[(19)] = (DepthwiseConv2d_local[(19)] + (PaddedInput_shared_local[(71)] * placeholder_shared_local[(17)]));
  DepthwiseConv2d_local[(9)] = 0.000000e+00f;
  DepthwiseConv2d_local[(20)] = 0.000000e+00f;
  DepthwiseConv2d_local[(9)] = (DepthwiseConv2d_local[(9)] + (PaddedInput_shared_local[(27)] * placeholder_shared_local[(0)]));
  DepthwiseConv2d_local[(20)] = (DepthwiseConv2d_local[(20)] + (PaddedInput_shared_local[(66)] * placeholder_shared_local[(9)]));
  DepthwiseConv2d_local[(9)] = (DepthwiseConv2d_local[(9)] + (PaddedInput_shared_local[(28)] * placeholder_shared_local[(1)]));
  DepthwiseConv2d_local[(20)] = (DepthwiseConv2d_local[(20)] + (PaddedInput_shared_local[(67)] * placeholder_shared_local[(10)]));
  DepthwiseConv2d_local[(9)] = (DepthwiseConv2d_local[(9)] + (PaddedInput_shared_local[(29)] * placeholder_shared_local[(2)]));
  DepthwiseConv2d_local[(20)] = (DepthwiseConv2d_local[(20)] + (PaddedInput_shared_local[(68)] * placeholder_shared_local[(11)]));
  DepthwiseConv2d_local[(9)] = (DepthwiseConv2d_local[(9)] + (PaddedInput_shared_local[(30)] * placeholder_shared_local[(3)]));
  DepthwiseConv2d_local[(20)] = (DepthwiseConv2d_local[(20)] + (PaddedInput_shared_local[(69)] * placeholder_shared_local[(12)]));
  DepthwiseConv2d_local[(9)] = (DepthwiseConv2d_local[(9)] + (PaddedInput_shared_local[(31)] * placeholder_shared_local[(4)]));
  DepthwiseConv2d_local[(20)] = (DepthwiseConv2d_local[(20)] + (PaddedInput_shared_local[(70)] * placeholder_shared_local[(13)]));
  DepthwiseConv2d_local[(9)] = (DepthwiseConv2d_local[(9)] + (PaddedInput_shared_local[(32)] * placeholder_shared_local[(5)]));
  DepthwiseConv2d_local[(20)] = (DepthwiseConv2d_local[(20)] + (PaddedInput_shared_local[(71)] * placeholder_shared_local[(14)]));
  DepthwiseConv2d_local[(9)] = (DepthwiseConv2d_local[(9)] + (PaddedInput_shared_local[(33)] * placeholder_shared_local[(6)]));
  DepthwiseConv2d_local[(20)] = (DepthwiseConv2d_local[(20)] + (PaddedInput_shared_local[(72)] * placeholder_shared_local[(15)]));
  DepthwiseConv2d_local[(9)] = (DepthwiseConv2d_local[(9)] + (PaddedInput_shared_local[(34)] * placeholder_shared_local[(7)]));
  DepthwiseConv2d_local[(20)] = (DepthwiseConv2d_local[(20)] + (PaddedInput_shared_local[(73)] * placeholder_shared_local[(16)]));
  DepthwiseConv2d_local[(9)] = (DepthwiseConv2d_local[(9)] + (PaddedInput_shared_local[(35)] * placeholder_shared_local[(8)]));
  DepthwiseConv2d_local[(20)] = (DepthwiseConv2d_local[(20)] + (PaddedInput_shared_local[(74)] * placeholder_shared_local[(17)]));
  DepthwiseConv2d_local[(10)] = 0.000000e+00f;
  DepthwiseConv2d_local[(21)] = 0.000000e+00f;
  DepthwiseConv2d_local[(10)] = (DepthwiseConv2d_local[(10)] + (PaddedInput_shared_local[(30)] * placeholder_shared_local[(0)]));
  DepthwiseConv2d_local[(21)] = (DepthwiseConv2d_local[(21)] + (PaddedInput_shared_local[(69)] * placeholder_shared_local[(9)]));
  DepthwiseConv2d_local[(10)] = (DepthwiseConv2d_local[(10)] + (PaddedInput_shared_local[(31)] * placeholder_shared_local[(1)]));
  DepthwiseConv2d_local[(21)] = (DepthwiseConv2d_local[(21)] + (PaddedInput_shared_local[(70)] * placeholder_shared_local[(10)]));
  DepthwiseConv2d_local[(10)] = (DepthwiseConv2d_local[(10)] + (PaddedInput_shared_local[(32)] * placeholder_shared_local[(2)]));
  DepthwiseConv2d_local[(21)] = (DepthwiseConv2d_local[(21)] + (PaddedInput_shared_local[(71)] * placeholder_shared_local[(11)]));
  DepthwiseConv2d_local[(10)] = (DepthwiseConv2d_local[(10)] + (PaddedInput_shared_local[(33)] * placeholder_shared_local[(3)]));
  DepthwiseConv2d_local[(21)] = (DepthwiseConv2d_local[(21)] + (PaddedInput_shared_local[(72)] * placeholder_shared_local[(12)]));
  DepthwiseConv2d_local[(10)] = (DepthwiseConv2d_local[(10)] + (PaddedInput_shared_local[(34)] * placeholder_shared_local[(4)]));
  DepthwiseConv2d_local[(21)] = (DepthwiseConv2d_local[(21)] + (PaddedInput_shared_local[(73)] * placeholder_shared_local[(13)]));
  DepthwiseConv2d_local[(10)] = (DepthwiseConv2d_local[(10)] + (PaddedInput_shared_local[(35)] * placeholder_shared_local[(5)]));
  DepthwiseConv2d_local[(21)] = (DepthwiseConv2d_local[(21)] + (PaddedInput_shared_local[(74)] * placeholder_shared_local[(14)]));
  DepthwiseConv2d_local[(10)] = (DepthwiseConv2d_local[(10)] + (PaddedInput_shared_local[(36)] * placeholder_shared_local[(6)]));
  DepthwiseConv2d_local[(21)] = (DepthwiseConv2d_local[(21)] + (PaddedInput_shared_local[(75)] * placeholder_shared_local[(15)]));
  DepthwiseConv2d_local[(10)] = (DepthwiseConv2d_local[(10)] + (PaddedInput_shared_local[(37)] * placeholder_shared_local[(7)]));
  DepthwiseConv2d_local[(21)] = (DepthwiseConv2d_local[(21)] + (PaddedInput_shared_local[(76)] * placeholder_shared_local[(16)]));
  DepthwiseConv2d_local[(10)] = (DepthwiseConv2d_local[(10)] + (PaddedInput_shared_local[(38)] * placeholder_shared_local[(8)]));
  DepthwiseConv2d_local[(21)] = (DepthwiseConv2d_local[(21)] + (PaddedInput_shared_local[(77)] * placeholder_shared_local[(17)]));
  DepthwiseConv2d[(((((int)blockIdx.z) * 242) + ((int)threadIdx.x)))] = DepthwiseConv2d_local[(0)];
  DepthwiseConv2d[((((((int)blockIdx.z) * 242) + ((int)threadIdx.x)) + 121))] = DepthwiseConv2d_local[(11)];
  DepthwiseConv2d[((((((int)blockIdx.z) * 242) + ((int)threadIdx.x)) + 11))] = DepthwiseConv2d_local[(1)];
  DepthwiseConv2d[((((((int)blockIdx.z) * 242) + ((int)threadIdx.x)) + 132))] = DepthwiseConv2d_local[(12)];
  DepthwiseConv2d[((((((int)blockIdx.z) * 242) + ((int)threadIdx.x)) + 22))] = DepthwiseConv2d_local[(2)];
  DepthwiseConv2d[((((((int)blockIdx.z) * 242) + ((int)threadIdx.x)) + 143))] = DepthwiseConv2d_local[(13)];
  DepthwiseConv2d[((((((int)blockIdx.z) * 242) + ((int)threadIdx.x)) + 33))] = DepthwiseConv2d_local[(3)];
  DepthwiseConv2d[((((((int)blockIdx.z) * 242) + ((int)threadIdx.x)) + 154))] = DepthwiseConv2d_local[(14)];
  DepthwiseConv2d[((((((int)blockIdx.z) * 242) + ((int)threadIdx.x)) + 44))] = DepthwiseConv2d_local[(4)];
  DepthwiseConv2d[((((((int)blockIdx.z) * 242) + ((int)threadIdx.x)) + 165))] = DepthwiseConv2d_local[(15)];
  DepthwiseConv2d[((((((int)blockIdx.z) * 242) + ((int)threadIdx.x)) + 55))] = DepthwiseConv2d_local[(5)];
  DepthwiseConv2d[((((((int)blockIdx.z) * 242) + ((int)threadIdx.x)) + 176))] = DepthwiseConv2d_local[(16)];
  DepthwiseConv2d[((((((int)blockIdx.z) * 242) + ((int)threadIdx.x)) + 66))] = DepthwiseConv2d_local[(6)];
  DepthwiseConv2d[((((((int)blockIdx.z) * 242) + ((int)threadIdx.x)) + 187))] = DepthwiseConv2d_local[(17)];
  DepthwiseConv2d[((((((int)blockIdx.z) * 242) + ((int)threadIdx.x)) + 77))] = DepthwiseConv2d_local[(7)];
  DepthwiseConv2d[((((((int)blockIdx.z) * 242) + ((int)threadIdx.x)) + 198))] = DepthwiseConv2d_local[(18)];
  DepthwiseConv2d[((((((int)blockIdx.z) * 242) + ((int)threadIdx.x)) + 88))] = DepthwiseConv2d_local[(8)];
  DepthwiseConv2d[((((((int)blockIdx.z) * 242) + ((int)threadIdx.x)) + 209))] = DepthwiseConv2d_local[(19)];
  DepthwiseConv2d[((((((int)blockIdx.z) * 242) + ((int)threadIdx.x)) + 99))] = DepthwiseConv2d_local[(9)];
  DepthwiseConv2d[((((((int)blockIdx.z) * 242) + ((int)threadIdx.x)) + 220))] = DepthwiseConv2d_local[(20)];
  DepthwiseConv2d[((((((int)blockIdx.z) * 242) + ((int)threadIdx.x)) + 110))] = DepthwiseConv2d_local[(10)];
  DepthwiseConv2d[((((((int)blockIdx.z) * 242) + ((int)threadIdx.x)) + 231))] = DepthwiseConv2d_local[(21)];
}

