
#ifdef _WIN32
  using uint = unsigned int;
  using uchar = unsigned char;
  using ushort = unsigned short;
  using int64_t = long long;
  using uint64_t = unsigned long long;
#else
  #define uint unsigned int
  #define uchar unsigned char
  #define ushort unsigned short
  #define int64_t long long
  #define uint64_t unsigned long long
#endif
extern "C" __global__ void __launch_bounds__(256) default_function_kernel0(float* __restrict__ data, float* __restrict__ kernel, float* __restrict__ bias, float* __restrict__ conv_unpad) {
  float conv_local[2];
  __shared__ float data_pad_shared[4096];
  __shared__ float kernel_pad_shared[2048];
  float data_pad_shared_local[2];
  float kernel_pad_shared_local[1];
  conv_local[0] = 0.000000e+00f;
  conv_local[1] = 0.000000e+00f;
  for (int ra_fused0_outer = 0; ra_fused0_outer < 5; ++ra_fused0_outer) {
    bool cse_var_1 = (ra_fused0_outer < 4);
    __syncthreads();
    data_pad_shared[((int)threadIdx.x)] = (((((0 < ((((((int)blockIdx.x) & 1) * 4) + ((((int)threadIdx.x) & 31) >> 3)) + ((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) % 9) / 3))) && (((((((int)blockIdx.x) & 1) * 4) + ((((int)threadIdx.x) & 31) >> 3)) + ((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) % 9) / 3)) < 9)) && (0 < ((((int)threadIdx.x) & 7) + (((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) % 3)))) && (((((int)threadIdx.x) & 7) + (((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) % 3)) < 9)) ? data[(((((((((ra_fused0_outer * 128) + (((int)threadIdx.x) >> 5)) / 9) * 64) + ((((int)blockIdx.x) & 1) * 32)) + (((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) % 9) / 3) * 8)) + (((int)threadIdx.x) & 31)) + (((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) % 3)) - 9)] : 0.000000e+00f);
    data_pad_shared[(((int)threadIdx.x) + 256)] = (((((0 < ((((((int)blockIdx.x) & 1) * 4) + ((((int)threadIdx.x) & 31) >> 3)) + (((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) + 8) % 9) / 3))) && (((((((int)blockIdx.x) & 1) * 4) + ((((int)threadIdx.x) & 31) >> 3)) + (((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) + 8) % 9) / 3)) < 9)) && (0 < ((((int)threadIdx.x) & 7) + ((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) + 2) % 3)))) && (((((int)threadIdx.x) & 7) + ((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) + 2) % 3)) < 9)) ? data[((((((((((ra_fused0_outer * 128) + (((int)threadIdx.x) >> 5)) + 8) / 9) * 64) + ((((int)blockIdx.x) & 1) * 32)) + ((((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) + 8) % 9) / 3) * 8)) + (((int)threadIdx.x) & 31)) + ((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) + 2) % 3)) - 9)] : 0.000000e+00f);
    data_pad_shared[(((int)threadIdx.x) + 512)] = (((((0 < ((((((int)blockIdx.x) & 1) * 4) + ((((int)threadIdx.x) & 31) >> 3)) + (((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) + 7) % 9) / 3))) && (((((((int)blockIdx.x) & 1) * 4) + ((((int)threadIdx.x) & 31) >> 3)) + (((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) + 7) % 9) / 3)) < 9)) && (0 < ((((int)threadIdx.x) & 7) + ((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) + 1) % 3)))) && (((((int)threadIdx.x) & 7) + ((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) + 1) % 3)) < 9)) ? data[((((((((((ra_fused0_outer * 128) + (((int)threadIdx.x) >> 5)) + 16) / 9) * 64) + ((((int)blockIdx.x) & 1) * 32)) + ((((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) + 7) % 9) / 3) * 8)) + (((int)threadIdx.x) & 31)) + ((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) + 1) % 3)) - 9)] : 0.000000e+00f);
    data_pad_shared[(((int)threadIdx.x) + 768)] = (((((0 < ((((((int)blockIdx.x) & 1) * 4) + ((((int)threadIdx.x) & 31) >> 3)) + (((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) / 3) + 2) % 3))) && (((((((int)blockIdx.x) & 1) * 4) + ((((int)threadIdx.x) & 31) >> 3)) + (((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) / 3) + 2) % 3)) < 9)) && (0 < ((((int)threadIdx.x) & 7) + (((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) % 3)))) && (((((int)threadIdx.x) & 7) + (((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) % 3)) < 9)) ? data[((((((((((ra_fused0_outer * 128) + (((int)threadIdx.x) >> 5)) + 24) / 9) * 64) + ((((int)blockIdx.x) & 1) * 32)) + ((((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) / 3) + 2) % 3) * 8)) + (((int)threadIdx.x) & 31)) + (((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) % 3)) - 9)] : 0.000000e+00f);
    data_pad_shared[(((int)threadIdx.x) + 1024)] = (((((0 < ((((((int)blockIdx.x) & 1) * 4) + ((((int)threadIdx.x) & 31) >> 3)) + (((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) + 5) % 9) / 3))) && (((((((int)blockIdx.x) & 1) * 4) + ((((int)threadIdx.x) & 31) >> 3)) + (((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) + 5) % 9) / 3)) < 9)) && (0 < ((((int)threadIdx.x) & 7) + ((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) + 2) % 3)))) && (((((int)threadIdx.x) & 7) + ((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) + 2) % 3)) < 9)) ? data[((((((((((ra_fused0_outer * 128) + (((int)threadIdx.x) >> 5)) + 32) / 9) * 64) + ((((int)blockIdx.x) & 1) * 32)) + ((((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) + 5) % 9) / 3) * 8)) + (((int)threadIdx.x) & 31)) + ((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) + 2) % 3)) - 9)] : 0.000000e+00f);
    data_pad_shared[(((int)threadIdx.x) + 1280)] = (((((0 < ((((((int)blockIdx.x) & 1) * 4) + ((((int)threadIdx.x) & 31) >> 3)) + (((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) + 4) % 9) / 3))) && (((((((int)blockIdx.x) & 1) * 4) + ((((int)threadIdx.x) & 31) >> 3)) + (((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) + 4) % 9) / 3)) < 9)) && (0 < ((((int)threadIdx.x) & 7) + ((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) + 1) % 3)))) && (((((int)threadIdx.x) & 7) + ((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) + 1) % 3)) < 9)) ? data[((((((((((ra_fused0_outer * 128) + (((int)threadIdx.x) >> 5)) + 40) / 9) * 64) + ((((int)blockIdx.x) & 1) * 32)) + ((((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) + 4) % 9) / 3) * 8)) + (((int)threadIdx.x) & 31)) + ((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) + 1) % 3)) - 9)] : 0.000000e+00f);
    data_pad_shared[(((int)threadIdx.x) + 1536)] = (((((0 < ((((((int)blockIdx.x) & 1) * 4) + ((((int)threadIdx.x) & 31) >> 3)) + (((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) / 3) + 1) % 3))) && (((((((int)blockIdx.x) & 1) * 4) + ((((int)threadIdx.x) & 31) >> 3)) + (((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) / 3) + 1) % 3)) < 9)) && (0 < ((((int)threadIdx.x) & 7) + (((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) % 3)))) && (((((int)threadIdx.x) & 7) + (((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) % 3)) < 9)) ? data[((((((((((ra_fused0_outer * 128) + (((int)threadIdx.x) >> 5)) + 48) / 9) * 64) + ((((int)blockIdx.x) & 1) * 32)) + ((((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) / 3) + 1) % 3) * 8)) + (((int)threadIdx.x) & 31)) + (((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) % 3)) - 9)] : 0.000000e+00f);
    data_pad_shared[(((int)threadIdx.x) + 1792)] = (((((0 < ((((((int)blockIdx.x) & 1) * 4) + ((((int)threadIdx.x) & 31) >> 3)) + (((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) + 2) % 9) / 3))) && (((((((int)blockIdx.x) & 1) * 4) + ((((int)threadIdx.x) & 31) >> 3)) + (((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) + 2) % 9) / 3)) < 9)) && (0 < ((((int)threadIdx.x) & 7) + ((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) + 2) % 3)))) && (((((int)threadIdx.x) & 7) + ((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) + 2) % 3)) < 9)) ? data[((((((((((ra_fused0_outer * 128) + (((int)threadIdx.x) >> 5)) + 56) / 9) * 64) + ((((int)blockIdx.x) & 1) * 32)) + ((((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) + 2) % 9) / 3) * 8)) + (((int)threadIdx.x) & 31)) + ((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) + 2) % 3)) - 9)] : 0.000000e+00f);
    data_pad_shared[(((int)threadIdx.x) + 2048)] = (((((cse_var_1 && (0 < ((((((int)blockIdx.x) & 1) * 4) + ((((int)threadIdx.x) & 31) >> 3)) + (((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) + 1) % 9) / 3)))) && (((((((int)blockIdx.x) & 1) * 4) + ((((int)threadIdx.x) & 31) >> 3)) + (((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) + 1) % 9) / 3)) < 9)) && (0 < ((((int)threadIdx.x) & 7) + ((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) + 1) % 3)))) && (((((int)threadIdx.x) & 7) + ((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) + 1) % 3)) < 9)) ? data[((((((((((ra_fused0_outer * 128) + (((int)threadIdx.x) >> 5)) + 64) / 9) * 64) + ((((int)blockIdx.x) & 1) * 32)) + ((((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) + 1) % 9) / 3) * 8)) + (((int)threadIdx.x) & 31)) + ((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) + 1) % 3)) - 9)] : 0.000000e+00f);
    data_pad_shared[(((int)threadIdx.x) + 2304)] = (((((cse_var_1 && (0 < ((((((int)blockIdx.x) & 1) * 4) + ((((int)threadIdx.x) & 31) >> 3)) + ((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) % 9) / 3)))) && (((((((int)blockIdx.x) & 1) * 4) + ((((int)threadIdx.x) & 31) >> 3)) + ((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) % 9) / 3)) < 9)) && (0 < ((((int)threadIdx.x) & 7) + (((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) % 3)))) && (((((int)threadIdx.x) & 7) + (((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) % 3)) < 9)) ? data[(((((((((ra_fused0_outer * 128) + (((int)threadIdx.x) >> 5)) / 9) * 64) + ((((int)blockIdx.x) & 1) * 32)) + (((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) % 9) / 3) * 8)) + (((int)threadIdx.x) & 31)) + (((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) % 3)) + 503)] : 0.000000e+00f);
    data_pad_shared[(((int)threadIdx.x) + 2560)] = (((((cse_var_1 && (0 < ((((((int)blockIdx.x) & 1) * 4) + ((((int)threadIdx.x) & 31) >> 3)) + (((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) + 8) % 9) / 3)))) && (((((((int)blockIdx.x) & 1) * 4) + ((((int)threadIdx.x) & 31) >> 3)) + (((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) + 8) % 9) / 3)) < 9)) && (0 < ((((int)threadIdx.x) & 7) + ((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) + 2) % 3)))) && (((((int)threadIdx.x) & 7) + ((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) + 2) % 3)) < 9)) ? data[((((((((((ra_fused0_outer * 128) + (((int)threadIdx.x) >> 5)) + 80) / 9) * 64) + ((((int)blockIdx.x) & 1) * 32)) + ((((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) + 8) % 9) / 3) * 8)) + (((int)threadIdx.x) & 31)) + ((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) + 2) % 3)) - 9)] : 0.000000e+00f);
    data_pad_shared[(((int)threadIdx.x) + 2816)] = (((((cse_var_1 && (0 < ((((((int)blockIdx.x) & 1) * 4) + ((((int)threadIdx.x) & 31) >> 3)) + (((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) + 7) % 9) / 3)))) && (((((((int)blockIdx.x) & 1) * 4) + ((((int)threadIdx.x) & 31) >> 3)) + (((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) + 7) % 9) / 3)) < 9)) && (0 < ((((int)threadIdx.x) & 7) + ((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) + 1) % 3)))) && (((((int)threadIdx.x) & 7) + ((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) + 1) % 3)) < 9)) ? data[((((((((((ra_fused0_outer * 128) + (((int)threadIdx.x) >> 5)) + 88) / 9) * 64) + ((((int)blockIdx.x) & 1) * 32)) + ((((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) + 7) % 9) / 3) * 8)) + (((int)threadIdx.x) & 31)) + ((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) + 1) % 3)) - 9)] : 0.000000e+00f);
    data_pad_shared[(((int)threadIdx.x) + 3072)] = (((((cse_var_1 && (0 < ((((((int)blockIdx.x) & 1) * 4) + ((((int)threadIdx.x) & 31) >> 3)) + (((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) / 3) + 2) % 3)))) && (((((((int)blockIdx.x) & 1) * 4) + ((((int)threadIdx.x) & 31) >> 3)) + (((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) / 3) + 2) % 3)) < 9)) && (0 < ((((int)threadIdx.x) & 7) + (((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) % 3)))) && (((((int)threadIdx.x) & 7) + (((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) % 3)) < 9)) ? data[((((((((((ra_fused0_outer * 128) + (((int)threadIdx.x) >> 5)) + 96) / 9) * 64) + ((((int)blockIdx.x) & 1) * 32)) + ((((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) / 3) + 2) % 3) * 8)) + (((int)threadIdx.x) & 31)) + (((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) % 3)) - 9)] : 0.000000e+00f);
    data_pad_shared[(((int)threadIdx.x) + 3328)] = (((((cse_var_1 && (0 < ((((((int)blockIdx.x) & 1) * 4) + ((((int)threadIdx.x) & 31) >> 3)) + (((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) + 5) % 9) / 3)))) && (((((((int)blockIdx.x) & 1) * 4) + ((((int)threadIdx.x) & 31) >> 3)) + (((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) + 5) % 9) / 3)) < 9)) && (0 < ((((int)threadIdx.x) & 7) + ((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) + 2) % 3)))) && (((((int)threadIdx.x) & 7) + ((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) + 2) % 3)) < 9)) ? data[((((((((((ra_fused0_outer * 128) + (((int)threadIdx.x) >> 5)) + 104) / 9) * 64) + ((((int)blockIdx.x) & 1) * 32)) + ((((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) + 5) % 9) / 3) * 8)) + (((int)threadIdx.x) & 31)) + ((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) + 2) % 3)) - 9)] : 0.000000e+00f);
    data_pad_shared[(((int)threadIdx.x) + 3584)] = (((((cse_var_1 && (0 < ((((((int)blockIdx.x) & 1) * 4) + ((((int)threadIdx.x) & 31) >> 3)) + (((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) + 4) % 9) / 3)))) && (((((((int)blockIdx.x) & 1) * 4) + ((((int)threadIdx.x) & 31) >> 3)) + (((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) + 4) % 9) / 3)) < 9)) && (0 < ((((int)threadIdx.x) & 7) + ((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) + 1) % 3)))) && (((((int)threadIdx.x) & 7) + ((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) + 1) % 3)) < 9)) ? data[((((((((((ra_fused0_outer * 128) + (((int)threadIdx.x) >> 5)) + 112) / 9) * 64) + ((((int)blockIdx.x) & 1) * 32)) + ((((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) + 4) % 9) / 3) * 8)) + (((int)threadIdx.x) & 31)) + ((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) + 1) % 3)) - 9)] : 0.000000e+00f);
    data_pad_shared[(((int)threadIdx.x) + 3840)] = (((((cse_var_1 && (0 < ((((((int)blockIdx.x) & 1) * 4) + ((((int)threadIdx.x) & 31) >> 3)) + (((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) / 3) + 1) % 3)))) && (((((((int)blockIdx.x) & 1) * 4) + ((((int)threadIdx.x) & 31) >> 3)) + (((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) / 3) + 1) % 3)) < 9)) && (0 < ((((int)threadIdx.x) & 7) + (((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) % 3)))) && (((((int)threadIdx.x) & 7) + (((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) % 3)) < 9)) ? data[((((((((((ra_fused0_outer * 128) + (((int)threadIdx.x) >> 5)) + 120) / 9) * 64) + ((((int)blockIdx.x) & 1) * 32)) + ((((((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) / 3) + 1) % 3) * 8)) + (((int)threadIdx.x) & 31)) + (((ra_fused0_outer * 2) + (((int)threadIdx.x) >> 5)) % 3)) - 9)] : 0.000000e+00f);
    kernel_pad_shared[((int)threadIdx.x)] = ((((ra_fused0_outer * 2) + ((((int)threadIdx.x) & 127) >> 6)) < 9) ? kernel[(((((((int)blockIdx.x) >> 1) * 9216) + ((((int)threadIdx.x) >> 7) * 576)) + ((((ra_fused0_outer * 128) + (((int)threadIdx.x) & 127)) / 9) * 9)) + (((ra_fused0_outer * 2) + (((int)threadIdx.x) & 127)) % 9))] : 0.000000e+00f);
    kernel_pad_shared[(((int)threadIdx.x) + 256)] = ((((ra_fused0_outer * 2) + ((((int)threadIdx.x) & 127) >> 6)) < 9) ? kernel[((((((((int)blockIdx.x) >> 1) * 9216) + ((((int)threadIdx.x) >> 7) * 576)) + ((((ra_fused0_outer * 128) + (((int)threadIdx.x) & 127)) / 9) * 9)) + (((ra_fused0_outer * 2) + (((int)threadIdx.x) & 127)) % 9)) + 1152)] : 0.000000e+00f);
    kernel_pad_shared[(((int)threadIdx.x) + 512)] = ((((ra_fused0_outer * 2) + ((((int)threadIdx.x) & 127) >> 6)) < 9) ? kernel[((((((((int)blockIdx.x) >> 1) * 9216) + ((((int)threadIdx.x) >> 7) * 576)) + ((((ra_fused0_outer * 128) + (((int)threadIdx.x) & 127)) / 9) * 9)) + (((ra_fused0_outer * 2) + (((int)threadIdx.x) & 127)) % 9)) + 2304)] : 0.000000e+00f);
    kernel_pad_shared[(((int)threadIdx.x) + 768)] = ((((ra_fused0_outer * 2) + ((((int)threadIdx.x) & 127) >> 6)) < 9) ? kernel[((((((((int)blockIdx.x) >> 1) * 9216) + ((((int)threadIdx.x) >> 7) * 576)) + ((((ra_fused0_outer * 128) + (((int)threadIdx.x) & 127)) / 9) * 9)) + (((ra_fused0_outer * 2) + (((int)threadIdx.x) & 127)) % 9)) + 3456)] : 0.000000e+00f);
    kernel_pad_shared[(((int)threadIdx.x) + 1024)] = ((((ra_fused0_outer * 2) + ((((int)threadIdx.x) & 127) >> 6)) < 9) ? kernel[((((((((int)blockIdx.x) >> 1) * 9216) + ((((int)threadIdx.x) >> 7) * 576)) + ((((ra_fused0_outer * 128) + (((int)threadIdx.x) & 127)) / 9) * 9)) + (((ra_fused0_outer * 2) + (((int)threadIdx.x) & 127)) % 9)) + 4608)] : 0.000000e+00f);
    kernel_pad_shared[(((int)threadIdx.x) + 1280)] = ((((ra_fused0_outer * 2) + ((((int)threadIdx.x) & 127) >> 6)) < 9) ? kernel[((((((((int)blockIdx.x) >> 1) * 9216) + ((((int)threadIdx.x) >> 7) * 576)) + ((((ra_fused0_outer * 128) + (((int)threadIdx.x) & 127)) / 9) * 9)) + (((ra_fused0_outer * 2) + (((int)threadIdx.x) & 127)) % 9)) + 5760)] : 0.000000e+00f);
    kernel_pad_shared[(((int)threadIdx.x) + 1536)] = ((((ra_fused0_outer * 2) + ((((int)threadIdx.x) & 127) >> 6)) < 9) ? kernel[((((((((int)blockIdx.x) >> 1) * 9216) + ((((int)threadIdx.x) >> 7) * 576)) + ((((ra_fused0_outer * 128) + (((int)threadIdx.x) & 127)) / 9) * 9)) + (((ra_fused0_outer * 2) + (((int)threadIdx.x) & 127)) % 9)) + 6912)] : 0.000000e+00f);
    kernel_pad_shared[(((int)threadIdx.x) + 1792)] = ((((ra_fused0_outer * 2) + ((((int)threadIdx.x) & 127) >> 6)) < 9) ? kernel[((((((((int)blockIdx.x) >> 1) * 9216) + ((((int)threadIdx.x) >> 7) * 576)) + ((((ra_fused0_outer * 128) + (((int)threadIdx.x) & 127)) / 9) * 9)) + (((ra_fused0_outer * 2) + (((int)threadIdx.x) & 127)) % 9)) + 8064)] : 0.000000e+00f);
    __syncthreads();
    for (int ra_fused0_inner_outer = 0; ra_fused0_inner_outer < 128; ++ra_fused0_inner_outer) {
      data_pad_shared_local[0] = data_pad_shared[((ra_fused0_inner_outer * 32) + (((int)threadIdx.x) & 15))];
      data_pad_shared_local[1] = data_pad_shared[(((ra_fused0_inner_outer * 32) + (((int)threadIdx.x) & 15)) + 16)];
      kernel_pad_shared_local[0] = kernel_pad_shared[(((((int)threadIdx.x) >> 4) * 128) + ra_fused0_inner_outer)];
      if (((ra_fused0_outer * 2) + (ra_fused0_inner_outer >> 6)) < 9) {
        conv_local[0] = (conv_local[0] + (data_pad_shared_local[0] * kernel_pad_shared_local[0]));
        conv_local[1] = (conv_local[1] + (data_pad_shared_local[1] * kernel_pad_shared_local[0]));
      }
    }
  }
  conv_unpad[(((((((int)blockIdx.x) >> 1) * 1024) + ((((int)threadIdx.x) >> 4) * 64)) + ((((int)blockIdx.x) & 1) * 32)) + (((int)threadIdx.x) & 15))] = max((conv_local[0] + bias[(((((int)blockIdx.x) >> 1) * 16) + (((int)threadIdx.x) >> 4))]), 0.000000e+00f);
  conv_unpad[((((((((int)blockIdx.x) >> 1) * 1024) + ((((int)threadIdx.x) >> 4) * 64)) + ((((int)blockIdx.x) & 1) * 32)) + (((int)threadIdx.x) & 15)) + 16)] = max((conv_local[1] + bias[(((((int)blockIdx.x) >> 1) * 16) + (((int)threadIdx.x) >> 4))]), 0.000000e+00f);
}

dim3 grid(8, 1, 1);
dim3 block(256, 1, 1);
best_idx 6