// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nnf_pbtypes.proto

#ifndef PROTOBUF_INCLUDED_nnf_5fpbtypes_2eproto
#define PROTOBUF_INCLUDED_nnf_5fpbtypes_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_nnf_5fpbtypes_2eproto 

namespace protobuf_nnf_5fpbtypes_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_nnf_5fpbtypes_2eproto
namespace nnfusion {
namespace serialize {
}  // namespace serialize
}  // namespace nnfusion
namespace nnfusion {
namespace serialize {

enum PBType {
  DT_INVALID = 0,
  DT_BOOL = 1,
  DT_CHAR = 2,
  DT_FLOAT = 3,
  DT_DOUBLE = 4,
  DT_INT8 = 5,
  DT_INT16 = 6,
  DT_INT32 = 7,
  DT_INT64 = 8,
  DT_UINT8 = 9,
  DT_UINT16 = 10,
  DT_UINT32 = 11,
  DT_UINT64 = 12,
  PBType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  PBType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool PBType_IsValid(int value);
const PBType PBType_MIN = DT_INVALID;
const PBType PBType_MAX = DT_UINT64;
const int PBType_ARRAYSIZE = PBType_MAX + 1;

const ::google::protobuf::EnumDescriptor* PBType_descriptor();
inline const ::std::string& PBType_Name(PBType value) {
  return ::google::protobuf::internal::NameOfEnum(
    PBType_descriptor(), value);
}
inline bool PBType_Parse(
    const ::std::string& name, PBType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<PBType>(
    PBType_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace serialize
}  // namespace nnfusion

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::nnfusion::serialize::PBType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::nnfusion::serialize::PBType>() {
  return ::nnfusion::serialize::PBType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_nnf_5fpbtypes_2eproto
