// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

#include "backward_registry.hpp"

REGISTER_EMPTY_BACKWARD_TRANSLATOR(Equal)
REGISTER_EMPTY_BACKWARD_TRANSLATOR(NotEqual)
REGISTER_EMPTY_BACKWARD_TRANSLATOR(Greater)
REGISTER_EMPTY_BACKWARD_TRANSLATOR(GreaterEq)
REGISTER_EMPTY_BACKWARD_TRANSLATOR(Less)
REGISTER_EMPTY_BACKWARD_TRANSLATOR(LessEq)
REGISTER_EMPTY_BACKWARD_TRANSLATOR(Not)
REGISTER_EMPTY_BACKWARD_TRANSLATOR(And)
REGISTER_EMPTY_BACKWARD_TRANSLATOR(Or)