//150528_1_1_21_1_1
//128_336_45_45_5_2_VALID
//dim3 grid(150528, 1, 1);
//dim3 block(21, 1, 1);

#ifdef _WIN32
  using uint = unsigned int;
  using uchar = unsigned char;
  using ushort = unsigned short;
  using int64_t = long long;
  using uint64_t = unsigned long long;
#else
  #define uint unsigned int
  #define uchar unsigned char
  #define ushort unsigned short
  #define int64_t long long
  #define uint64_t unsigned long long
#endif
extern "C" __global__ void __launch_bounds__(21) default_function_kernel0(float* __restrict__ data, float* __restrict__ kernel, float* __restrict__ DepthwiseConv2d) {
  float DepthwiseConv2d_local[6];
  __shared__ float PaddedInput_shared[810];
  __shared__ float kernel_shared[50];
  DepthwiseConv2d_local[(0)] = 0.000000e+00f;
  DepthwiseConv2d_local[(1)] = 0.000000e+00f;
  DepthwiseConv2d_local[(2)] = 0.000000e+00f;
  DepthwiseConv2d_local[(3)] = 0.000000e+00f;
  DepthwiseConv2d_local[(4)] = 0.000000e+00f;
  DepthwiseConv2d_local[(5)] = 0.000000e+00f;
  PaddedInput_shared[(((int)threadIdx.x))] = data[(((((((int)blockIdx.x) / 7) * 4050) + ((((int)blockIdx.x) % 7) * 270)) + ((int)threadIdx.x)))];
  PaddedInput_shared[((((int)threadIdx.x) + 21))] = data[((((((((int)blockIdx.x) / 7) * 4050) + ((((int)blockIdx.x) % 7) * 270)) + ((int)threadIdx.x)) + 21))];
  PaddedInput_shared[((((int)threadIdx.x) + 42))] = data[((((((((int)blockIdx.x) / 7) * 4050) + ((((int)blockIdx.x) % 7) * 270)) + ((int)threadIdx.x)) + 42))];
  PaddedInput_shared[((((int)threadIdx.x) + 63))] = data[((((((((int)blockIdx.x) / 7) * 4050) + ((((int)blockIdx.x) % 7) * 270)) + ((int)threadIdx.x)) + 63))];
  PaddedInput_shared[((((int)threadIdx.x) + 84))] = data[((((((((int)blockIdx.x) / 7) * 4050) + ((((int)blockIdx.x) % 7) * 270)) + ((int)threadIdx.x)) + 84))];
  PaddedInput_shared[((((int)threadIdx.x) + 105))] = data[((((((((int)blockIdx.x) / 7) * 4050) + ((((int)blockIdx.x) % 7) * 270)) + ((int)threadIdx.x)) + 105))];
  PaddedInput_shared[((((int)threadIdx.x) + 126))] = data[((((((((int)blockIdx.x) / 7) * 4050) + ((((int)blockIdx.x) % 7) * 270)) + ((int)threadIdx.x)) + 126))];
  PaddedInput_shared[((((int)threadIdx.x) + 147))] = data[((((((((int)blockIdx.x) / 7) * 4050) + ((((int)blockIdx.x) % 7) * 270)) + ((int)threadIdx.x)) + 147))];
  PaddedInput_shared[((((int)threadIdx.x) + 168))] = data[((((((((int)blockIdx.x) / 7) * 4050) + ((((int)blockIdx.x) % 7) * 270)) + ((int)threadIdx.x)) + 168))];
  PaddedInput_shared[((((int)threadIdx.x) + 189))] = data[((((((((int)blockIdx.x) / 7) * 4050) + ((((int)blockIdx.x) % 7) * 270)) + ((int)threadIdx.x)) + 189))];
  PaddedInput_shared[((((int)threadIdx.x) + 210))] = data[((((((((int)blockIdx.x) / 7) * 4050) + ((((int)blockIdx.x) % 7) * 270)) + ((int)threadIdx.x)) + 210))];
  PaddedInput_shared[((((int)threadIdx.x) + 231))] = data[((((((((int)blockIdx.x) / 7) * 4050) + ((((int)blockIdx.x) % 7) * 270)) + ((int)threadIdx.x)) + 231))];
  PaddedInput_shared[((((int)threadIdx.x) + 252))] = data[((((((((int)blockIdx.x) / 7) * 4050) + ((((int)blockIdx.x) % 7) * 270)) + ((int)threadIdx.x)) + 252))];
  PaddedInput_shared[((((int)threadIdx.x) + 273))] = data[((((((((int)blockIdx.x) / 7) * 4050) + ((((int)blockIdx.x) % 7) * 270)) + ((int)threadIdx.x)) + 273))];
  PaddedInput_shared[((((int)threadIdx.x) + 294))] = data[((((((((int)blockIdx.x) / 7) * 4050) + ((((int)blockIdx.x) % 7) * 270)) + ((int)threadIdx.x)) + 294))];
  PaddedInput_shared[((((int)threadIdx.x) + 315))] = data[((((((((int)blockIdx.x) / 7) * 4050) + ((((int)blockIdx.x) % 7) * 270)) + ((int)threadIdx.x)) + 315))];
  PaddedInput_shared[((((int)threadIdx.x) + 336))] = data[((((((((int)blockIdx.x) / 7) * 4050) + ((((int)blockIdx.x) % 7) * 270)) + ((int)threadIdx.x)) + 336))];
  PaddedInput_shared[((((int)threadIdx.x) + 357))] = data[((((((((int)blockIdx.x) / 7) * 4050) + ((((int)blockIdx.x) % 7) * 270)) + ((int)threadIdx.x)) + 357))];
  PaddedInput_shared[((((int)threadIdx.x) + 378))] = data[((((((((int)blockIdx.x) / 7) * 4050) + ((((int)blockIdx.x) % 7) * 270)) + ((int)threadIdx.x)) + 378))];
  PaddedInput_shared[((((int)threadIdx.x) + 399))] = data[((((((((int)blockIdx.x) / 7) * 4050) + (((((int)threadIdx.x) + 399) / 405) * 2025)) + ((((int)blockIdx.x) % 7) * 270)) + ((((int)threadIdx.x) + 399) % 405)))];
  PaddedInput_shared[((((int)threadIdx.x) + 420))] = data[((((((((int)blockIdx.x) / 7) * 4050) + (((((int)threadIdx.x) + 420) / 405) * 2025)) + ((((int)blockIdx.x) % 7) * 270)) + (((int)threadIdx.x) + 15)))];
  PaddedInput_shared[((((int)threadIdx.x) + 441))] = data[((((((((int)blockIdx.x) / 7) * 4050) + (((((int)threadIdx.x) + 441) / 405) * 2025)) + ((((int)blockIdx.x) % 7) * 270)) + (((int)threadIdx.x) + 36)))];
  PaddedInput_shared[((((int)threadIdx.x) + 462))] = data[((((((((int)blockIdx.x) / 7) * 4050) + (((((int)threadIdx.x) + 462) / 405) * 2025)) + ((((int)blockIdx.x) % 7) * 270)) + (((int)threadIdx.x) + 57)))];
  PaddedInput_shared[((((int)threadIdx.x) + 483))] = data[((((((((int)blockIdx.x) / 7) * 4050) + (((((int)threadIdx.x) + 483) / 405) * 2025)) + ((((int)blockIdx.x) % 7) * 270)) + (((int)threadIdx.x) + 78)))];
  PaddedInput_shared[((((int)threadIdx.x) + 504))] = data[((((((((int)blockIdx.x) / 7) * 4050) + (((((int)threadIdx.x) + 504) / 405) * 2025)) + ((((int)blockIdx.x) % 7) * 270)) + (((int)threadIdx.x) + 99)))];
  PaddedInput_shared[((((int)threadIdx.x) + 525))] = data[((((((((int)blockIdx.x) / 7) * 4050) + (((((int)threadIdx.x) + 525) / 405) * 2025)) + ((((int)blockIdx.x) % 7) * 270)) + (((int)threadIdx.x) + 120)))];
  PaddedInput_shared[((((int)threadIdx.x) + 546))] = data[((((((((int)blockIdx.x) / 7) * 4050) + (((((int)threadIdx.x) + 546) / 405) * 2025)) + ((((int)blockIdx.x) % 7) * 270)) + (((int)threadIdx.x) + 141)))];
  PaddedInput_shared[((((int)threadIdx.x) + 567))] = data[((((((((int)blockIdx.x) / 7) * 4050) + (((((int)threadIdx.x) + 567) / 405) * 2025)) + ((((int)blockIdx.x) % 7) * 270)) + (((int)threadIdx.x) + 162)))];
  PaddedInput_shared[((((int)threadIdx.x) + 588))] = data[((((((((int)blockIdx.x) / 7) * 4050) + (((((int)threadIdx.x) + 588) / 405) * 2025)) + ((((int)blockIdx.x) % 7) * 270)) + (((int)threadIdx.x) + 183)))];
  PaddedInput_shared[((((int)threadIdx.x) + 609))] = data[((((((((int)blockIdx.x) / 7) * 4050) + (((((int)threadIdx.x) + 609) / 405) * 2025)) + ((((int)blockIdx.x) % 7) * 270)) + (((int)threadIdx.x) + 204)))];
  PaddedInput_shared[((((int)threadIdx.x) + 630))] = data[((((((((int)blockIdx.x) / 7) * 4050) + (((((int)threadIdx.x) + 630) / 405) * 2025)) + ((((int)blockIdx.x) % 7) * 270)) + (((int)threadIdx.x) + 225)))];
  PaddedInput_shared[((((int)threadIdx.x) + 651))] = data[((((((((int)blockIdx.x) / 7) * 4050) + (((((int)threadIdx.x) + 651) / 405) * 2025)) + ((((int)blockIdx.x) % 7) * 270)) + (((int)threadIdx.x) + 246)))];
  PaddedInput_shared[((((int)threadIdx.x) + 672))] = data[((((((((int)blockIdx.x) / 7) * 4050) + (((((int)threadIdx.x) + 672) / 405) * 2025)) + ((((int)blockIdx.x) % 7) * 270)) + (((int)threadIdx.x) + 267)))];
  PaddedInput_shared[((((int)threadIdx.x) + 693))] = data[((((((((int)blockIdx.x) / 7) * 4050) + (((((int)threadIdx.x) + 693) / 405) * 2025)) + ((((int)blockIdx.x) % 7) * 270)) + (((int)threadIdx.x) + 288)))];
  PaddedInput_shared[((((int)threadIdx.x) + 714))] = data[((((((((int)blockIdx.x) / 7) * 4050) + (((((int)threadIdx.x) + 714) / 405) * 2025)) + ((((int)blockIdx.x) % 7) * 270)) + (((int)threadIdx.x) + 309)))];
  PaddedInput_shared[((((int)threadIdx.x) + 735))] = data[((((((((int)blockIdx.x) / 7) * 4050) + (((((int)threadIdx.x) + 735) / 405) * 2025)) + ((((int)blockIdx.x) % 7) * 270)) + (((int)threadIdx.x) + 330)))];
  PaddedInput_shared[((((int)threadIdx.x) + 756))] = data[((((((((int)blockIdx.x) / 7) * 4050) + (((((int)threadIdx.x) + 756) / 405) * 2025)) + ((((int)blockIdx.x) % 7) * 270)) + (((int)threadIdx.x) + 351)))];
  PaddedInput_shared[((((int)threadIdx.x) + 777))] = data[((((((((int)blockIdx.x) / 7) * 4050) + (((((int)threadIdx.x) + 777) / 405) * 2025)) + ((((int)blockIdx.x) % 7) * 270)) + (((int)threadIdx.x) + 372)))];
  if (((int)threadIdx.x) < 12) {
    PaddedInput_shared[((((int)threadIdx.x) + 798))] = data[((((((((int)blockIdx.x) / 7) * 4050) + (((((int)threadIdx.x) + 798) / 405) * 2025)) + ((((int)blockIdx.x) % 7) * 270)) + (((int)threadIdx.x) + 393)))];
  }
  kernel_shared[(((int)threadIdx.x))] = kernel[(((((((int)blockIdx.x) % 1176) / 7) * 50) + ((int)threadIdx.x)))];
  kernel_shared[((((int)threadIdx.x) + 21))] = kernel[((((((((int)blockIdx.x) % 1176) / 7) * 50) + ((int)threadIdx.x)) + 21))];
  if (((int)threadIdx.x) < 8) {
    kernel_shared[((((int)threadIdx.x) + 42))] = kernel[((((((((int)blockIdx.x) % 1176) / 7) * 50) + ((int)threadIdx.x)) + 42))];
  }
  __syncthreads();
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared[((((int)threadIdx.x) * 2))] * kernel_shared[(0)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 45))] * kernel_shared[(5)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 90))] * kernel_shared[(10)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 135))] * kernel_shared[(15)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 180))] * kernel_shared[(20)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 90))] * kernel_shared[(0)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 135))] * kernel_shared[(5)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 180))] * kernel_shared[(10)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 225))] * kernel_shared[(15)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 270))] * kernel_shared[(20)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 180))] * kernel_shared[(0)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 225))] * kernel_shared[(5)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 270))] * kernel_shared[(10)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 315))] * kernel_shared[(15)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 360))] * kernel_shared[(20)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 405))] * kernel_shared[(25)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 450))] * kernel_shared[(30)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 495))] * kernel_shared[(35)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 540))] * kernel_shared[(40)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 585))] * kernel_shared[(45)]));
  DepthwiseConv2d_local[(4)] = (DepthwiseConv2d_local[(4)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 495))] * kernel_shared[(25)]));
  DepthwiseConv2d_local[(4)] = (DepthwiseConv2d_local[(4)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 540))] * kernel_shared[(30)]));
  DepthwiseConv2d_local[(4)] = (DepthwiseConv2d_local[(4)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 585))] * kernel_shared[(35)]));
  DepthwiseConv2d_local[(4)] = (DepthwiseConv2d_local[(4)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 630))] * kernel_shared[(40)]));
  DepthwiseConv2d_local[(4)] = (DepthwiseConv2d_local[(4)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 675))] * kernel_shared[(45)]));
  DepthwiseConv2d_local[(5)] = (DepthwiseConv2d_local[(5)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 585))] * kernel_shared[(25)]));
  DepthwiseConv2d_local[(5)] = (DepthwiseConv2d_local[(5)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 630))] * kernel_shared[(30)]));
  DepthwiseConv2d_local[(5)] = (DepthwiseConv2d_local[(5)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 675))] * kernel_shared[(35)]));
  DepthwiseConv2d_local[(5)] = (DepthwiseConv2d_local[(5)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 720))] * kernel_shared[(40)]));
  DepthwiseConv2d_local[(5)] = (DepthwiseConv2d_local[(5)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 765))] * kernel_shared[(45)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 1))] * kernel_shared[(1)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 46))] * kernel_shared[(6)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 91))] * kernel_shared[(11)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 136))] * kernel_shared[(16)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 181))] * kernel_shared[(21)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 91))] * kernel_shared[(1)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 136))] * kernel_shared[(6)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 181))] * kernel_shared[(11)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 226))] * kernel_shared[(16)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 271))] * kernel_shared[(21)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 181))] * kernel_shared[(1)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 226))] * kernel_shared[(6)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 271))] * kernel_shared[(11)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 316))] * kernel_shared[(16)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 361))] * kernel_shared[(21)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 406))] * kernel_shared[(26)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 451))] * kernel_shared[(31)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 496))] * kernel_shared[(36)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 541))] * kernel_shared[(41)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 586))] * kernel_shared[(46)]));
  DepthwiseConv2d_local[(4)] = (DepthwiseConv2d_local[(4)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 496))] * kernel_shared[(26)]));
  DepthwiseConv2d_local[(4)] = (DepthwiseConv2d_local[(4)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 541))] * kernel_shared[(31)]));
  DepthwiseConv2d_local[(4)] = (DepthwiseConv2d_local[(4)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 586))] * kernel_shared[(36)]));
  DepthwiseConv2d_local[(4)] = (DepthwiseConv2d_local[(4)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 631))] * kernel_shared[(41)]));
  DepthwiseConv2d_local[(4)] = (DepthwiseConv2d_local[(4)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 676))] * kernel_shared[(46)]));
  DepthwiseConv2d_local[(5)] = (DepthwiseConv2d_local[(5)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 586))] * kernel_shared[(26)]));
  DepthwiseConv2d_local[(5)] = (DepthwiseConv2d_local[(5)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 631))] * kernel_shared[(31)]));
  DepthwiseConv2d_local[(5)] = (DepthwiseConv2d_local[(5)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 676))] * kernel_shared[(36)]));
  DepthwiseConv2d_local[(5)] = (DepthwiseConv2d_local[(5)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 721))] * kernel_shared[(41)]));
  DepthwiseConv2d_local[(5)] = (DepthwiseConv2d_local[(5)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 766))] * kernel_shared[(46)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 2))] * kernel_shared[(2)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 47))] * kernel_shared[(7)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 92))] * kernel_shared[(12)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 137))] * kernel_shared[(17)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 182))] * kernel_shared[(22)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 92))] * kernel_shared[(2)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 137))] * kernel_shared[(7)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 182))] * kernel_shared[(12)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 227))] * kernel_shared[(17)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 272))] * kernel_shared[(22)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 182))] * kernel_shared[(2)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 227))] * kernel_shared[(7)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 272))] * kernel_shared[(12)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 317))] * kernel_shared[(17)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 362))] * kernel_shared[(22)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 407))] * kernel_shared[(27)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 452))] * kernel_shared[(32)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 497))] * kernel_shared[(37)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 542))] * kernel_shared[(42)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 587))] * kernel_shared[(47)]));
  DepthwiseConv2d_local[(4)] = (DepthwiseConv2d_local[(4)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 497))] * kernel_shared[(27)]));
  DepthwiseConv2d_local[(4)] = (DepthwiseConv2d_local[(4)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 542))] * kernel_shared[(32)]));
  DepthwiseConv2d_local[(4)] = (DepthwiseConv2d_local[(4)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 587))] * kernel_shared[(37)]));
  DepthwiseConv2d_local[(4)] = (DepthwiseConv2d_local[(4)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 632))] * kernel_shared[(42)]));
  DepthwiseConv2d_local[(4)] = (DepthwiseConv2d_local[(4)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 677))] * kernel_shared[(47)]));
  DepthwiseConv2d_local[(5)] = (DepthwiseConv2d_local[(5)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 587))] * kernel_shared[(27)]));
  DepthwiseConv2d_local[(5)] = (DepthwiseConv2d_local[(5)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 632))] * kernel_shared[(32)]));
  DepthwiseConv2d_local[(5)] = (DepthwiseConv2d_local[(5)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 677))] * kernel_shared[(37)]));
  DepthwiseConv2d_local[(5)] = (DepthwiseConv2d_local[(5)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 722))] * kernel_shared[(42)]));
  DepthwiseConv2d_local[(5)] = (DepthwiseConv2d_local[(5)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 767))] * kernel_shared[(47)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 3))] * kernel_shared[(3)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 48))] * kernel_shared[(8)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 93))] * kernel_shared[(13)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 138))] * kernel_shared[(18)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 183))] * kernel_shared[(23)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 93))] * kernel_shared[(3)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 138))] * kernel_shared[(8)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 183))] * kernel_shared[(13)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 228))] * kernel_shared[(18)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 273))] * kernel_shared[(23)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 183))] * kernel_shared[(3)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 228))] * kernel_shared[(8)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 273))] * kernel_shared[(13)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 318))] * kernel_shared[(18)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 363))] * kernel_shared[(23)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 408))] * kernel_shared[(28)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 453))] * kernel_shared[(33)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 498))] * kernel_shared[(38)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 543))] * kernel_shared[(43)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 588))] * kernel_shared[(48)]));
  DepthwiseConv2d_local[(4)] = (DepthwiseConv2d_local[(4)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 498))] * kernel_shared[(28)]));
  DepthwiseConv2d_local[(4)] = (DepthwiseConv2d_local[(4)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 543))] * kernel_shared[(33)]));
  DepthwiseConv2d_local[(4)] = (DepthwiseConv2d_local[(4)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 588))] * kernel_shared[(38)]));
  DepthwiseConv2d_local[(4)] = (DepthwiseConv2d_local[(4)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 633))] * kernel_shared[(43)]));
  DepthwiseConv2d_local[(4)] = (DepthwiseConv2d_local[(4)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 678))] * kernel_shared[(48)]));
  DepthwiseConv2d_local[(5)] = (DepthwiseConv2d_local[(5)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 588))] * kernel_shared[(28)]));
  DepthwiseConv2d_local[(5)] = (DepthwiseConv2d_local[(5)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 633))] * kernel_shared[(33)]));
  DepthwiseConv2d_local[(5)] = (DepthwiseConv2d_local[(5)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 678))] * kernel_shared[(38)]));
  DepthwiseConv2d_local[(5)] = (DepthwiseConv2d_local[(5)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 723))] * kernel_shared[(43)]));
  DepthwiseConv2d_local[(5)] = (DepthwiseConv2d_local[(5)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 768))] * kernel_shared[(48)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 4))] * kernel_shared[(4)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 49))] * kernel_shared[(9)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 94))] * kernel_shared[(14)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 139))] * kernel_shared[(19)]));
  DepthwiseConv2d_local[(0)] = (DepthwiseConv2d_local[(0)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 184))] * kernel_shared[(24)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 94))] * kernel_shared[(4)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 139))] * kernel_shared[(9)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 184))] * kernel_shared[(14)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 229))] * kernel_shared[(19)]));
  DepthwiseConv2d_local[(1)] = (DepthwiseConv2d_local[(1)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 274))] * kernel_shared[(24)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 184))] * kernel_shared[(4)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 229))] * kernel_shared[(9)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 274))] * kernel_shared[(14)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 319))] * kernel_shared[(19)]));
  DepthwiseConv2d_local[(2)] = (DepthwiseConv2d_local[(2)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 364))] * kernel_shared[(24)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 409))] * kernel_shared[(29)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 454))] * kernel_shared[(34)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 499))] * kernel_shared[(39)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 544))] * kernel_shared[(44)]));
  DepthwiseConv2d_local[(3)] = (DepthwiseConv2d_local[(3)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 589))] * kernel_shared[(49)]));
  DepthwiseConv2d_local[(4)] = (DepthwiseConv2d_local[(4)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 499))] * kernel_shared[(29)]));
  DepthwiseConv2d_local[(4)] = (DepthwiseConv2d_local[(4)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 544))] * kernel_shared[(34)]));
  DepthwiseConv2d_local[(4)] = (DepthwiseConv2d_local[(4)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 589))] * kernel_shared[(39)]));
  DepthwiseConv2d_local[(4)] = (DepthwiseConv2d_local[(4)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 634))] * kernel_shared[(44)]));
  DepthwiseConv2d_local[(4)] = (DepthwiseConv2d_local[(4)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 679))] * kernel_shared[(49)]));
  DepthwiseConv2d_local[(5)] = (DepthwiseConv2d_local[(5)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 589))] * kernel_shared[(29)]));
  DepthwiseConv2d_local[(5)] = (DepthwiseConv2d_local[(5)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 634))] * kernel_shared[(34)]));
  DepthwiseConv2d_local[(5)] = (DepthwiseConv2d_local[(5)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 679))] * kernel_shared[(39)]));
  DepthwiseConv2d_local[(5)] = (DepthwiseConv2d_local[(5)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 724))] * kernel_shared[(44)]));
  DepthwiseConv2d_local[(5)] = (DepthwiseConv2d_local[(5)] + (PaddedInput_shared[(((((int)threadIdx.x) * 2) + 769))] * kernel_shared[(49)]));
  for (int c_inner = 0; c_inner < 2; ++c_inner) {
    for (int i_inner = 0; i_inner < 3; ++i_inner) {
      DepthwiseConv2d[(((((((((int)blockIdx.x) / 7) * 882) + (c_inner * 441)) + ((((int)blockIdx.x) % 7) * 63)) + (i_inner * 21)) + ((int)threadIdx.x)))] = DepthwiseConv2d_local[(((c_inner * 3) + i_inner))];
    }
  }
}

