# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

pr:
  - opensource
  - releases/*
  - master

pool:
  name : NNFusion Build Agents
  demands : gpu

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - script: ./maint/script/test.sh