// Microsoft (c) 2019
/**
 * \brief Unit tests for ir::Ceiling
 * \author generated by script
 */

#include "nnfusion/core/operators/ceiling.hpp"
#include "../test_util/common.hpp"
#include "nnfusion/core/operators/parameter.hpp"

using namespace ngraph;

namespace nnfusion
{
    namespace test
    {
        template <typename T, size_t N>
        using NDArray = nnfusion::test::NDArrayay<T, N>;
    }

    namespace inventory
    {
        template <>
        shared_ptr<op::Ceiling> create_object<op::Ceiling, float>(int option)
        {
            switch (option)
            {
            case 0:
            {
                Shape shape{2, 2};
                auto A = make_shared<op::Parameter>(element::f32, shape);
                return make_shared<op::Ceiling>(A);
            }
            default: return nullptr;
            }
        }

        template <>
        vector<float> generate_input<op::Ceiling, float>(int option)
        {
            switch (option)
            {
            case 0:
            {
                vector<float> a = vector<float>{-2.5f, -2.0f, 0.3f, 4.8f};
                auto return_vector = vector<float>();
                return_vector.insert(return_vector.end(), a.begin(), a.end());
                return return_vector;
            }
            default: return vector<float>();
            }
        }

        template <>
        vector<float> generate_output<op::Ceiling, float>(int option)
        {
            switch (option)
            {
            case 0:
            {
                vector<float> result = vector<float>{-2.0f, -2.0f, 1.0f, 5.0f};
                auto return_vector = vector<float>();
                return_vector.insert(return_vector.end(), result.begin(), result.end());
                return return_vector;
            }
            default: return vector<float>();
            }
        }
    }
}