// Microsoft (c) 2019
/**
 * \brief Unit tests for ir::Multiply
 * \author generated by script
 */

#include "nnfusion/core/operators/multiply.hpp"
#include "../test_util/common.hpp"
#include "nnfusion/core/operators/parameter.hpp"

using namespace ngraph;

namespace nnfusion
{
    namespace test
    {
        template <typename T, size_t N>
        using NDArray = nnfusion::test::NDArray<T, N>;
    }

    namespace inventory
    {
        template <>
        shared_ptr<op::Multiply> create_object<op::Multiply, float>(int option)
        {
            switch (option)
            {
            case 0:
            {
                Shape shape{2, 2};
                auto A = make_shared<op::Parameter>(element::f32, shape);
                auto B = make_shared<op::Parameter>(element::f32, shape);
                return make_shared<op::Multiply>(A, B);
            }
            default: return nullptr;
            }
        }

        template <>
        vector<float> generate_input<op::Multiply, float>(int option)
        {
            switch (option)
            {
            case 0:
            {
                vector<float> a = test::NDArray<float, 2>({{1, 2}, {3, 4}}).get_vector();
                vector<float> b = test::NDArray<float, 2>({{5, 6}, {7, 8}}).get_vector();
                auto return_vector = vector<float>();
                return_vector.insert(return_vector.end(), a.begin(), a.end());
                return_vector.insert(return_vector.end(), b.begin(), b.end());
                return return_vector;
            }
            default: return vector<float>();
            }
        }

        template <>
        vector<float> generate_output<op::Multiply, float>(int option)
        {
            switch (option)
            {
            case 0:
            {
                vector<float> result = (test::NDArray<float, 2>({{5, 12}, {21, 32}})).get_vector();
                auto return_vector = vector<float>();
                return_vector.insert(return_vector.end(), result.begin(), result.end());
                return return_vector;
            }
            default: return vector<float>();
            }
        }
    }
}