// Microsoft (c) 2019
/**
 * \brief Unit tests for ir::ReplaceSlice
 * \author generated by script
 */

#include "nnfusion/core/operators/replace_slice.hpp"
#include "../test_util/common.hpp"
#include "nnfusion/core/operators/parameter.hpp"

using namespace ngraph;

namespace nnfusion
{
    namespace test
    {
        template <typename T, size_t N>
        using NDArray = nnfusion::test::NDArray<T, N>;
    }

    namespace inventory
    {
        template <>
        shared_ptr<op::ReplaceSlice> create_object<op::ReplaceSlice, float>(int option)
        {
            switch (option)
            {
            case 0:
            {
                Shape shape_a{};
                auto A = make_shared<op::Parameter>(element::f32, shape_a);
                Shape shape_b{};
                auto B = make_shared<op::Parameter>(element::f32, shape_b);
                auto r = make_shared<op::ReplaceSlice>(A, B, Coordinate{}, Coordinate{});
                return r;
            }
            case 1:
            {
                Shape shape_a{4, 4};
                auto A = make_shared<op::Parameter>(element::f32, shape_a);
                Shape shape_b{3, 2};
                auto B = make_shared<op::Parameter>(element::f32, shape_b);
                auto r = make_shared<op::ReplaceSlice>(A, B, Coordinate{0, 1}, Coordinate{3, 3});
                return r;
            }
            case 2:
            {
                Shape shape_a{16};
                auto A = make_shared<op::Parameter>(element::f32, shape_a);
                Shape shape_b{12};
                auto B = make_shared<op::Parameter>(element::f32, shape_b);
                auto r = make_shared<op::ReplaceSlice>(A, B, Coordinate{2}, Coordinate{14});
                return r;
            }
            case 3:
            {
                Shape shape_a{4, 4, 4};
                auto A = make_shared<op::Parameter>(element::f32, shape_a);
                Shape shape_b{2, 2, 2};
                auto B = make_shared<op::Parameter>(element::f32, shape_b);
                auto r =
                    make_shared<op::ReplaceSlice>(A, B, Coordinate{1, 1, 1}, Coordinate{3, 3, 3});
                return r;
            }
            case 4:
            {
                Shape shape_a{4, 4, 4};
                auto A = make_shared<op::Parameter>(element::f32, shape_a);
                Shape shape_b{2, 2, 2};
                auto B = make_shared<op::Parameter>(element::f32, shape_b);
                auto r = make_shared<op::ReplaceSlice>(
                    A, B, Coordinate{0, 0, 0}, Coordinate{4, 4, 4}, Strides{2, 2, 2});
                return r;
            }
            case 5:
            {
                Shape shape_a{4, 4, 4};
                auto A = make_shared<op::Parameter>(element::f32, shape_a);
                Shape shape_b{2, 2, 2};
                auto B = make_shared<op::Parameter>(element::f32, shape_b);
                auto r = make_shared<op::ReplaceSlice>(
                    A, B, Coordinate{0, 0, 0}, Coordinate{4, 4, 4}, Strides{2, 2, 3});
                return r;
            }
            default: return nullptr;
            }
        }

        template <>
        vector<float> generate_input<op::ReplaceSlice, float>(int option)
        {
            switch (option)
            {
            case 0:
            {
                vector<float> a = vector<float>{312};
                vector<float> b = vector<float>{808};
                auto return_vector = vector<float>();
                return_vector.insert(return_vector.end(), a.begin(), a.end());
                return_vector.insert(return_vector.end(), b.begin(), b.end());
                return return_vector;
            }
            case 1:
            {
                vector<float> a =
                    vector<float>{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};
                vector<float> b = vector<float>{102, 103, 106, 107, 110, 111};
                auto return_vector = vector<float>();
                return_vector.insert(return_vector.end(), a.begin(), a.end());
                return_vector.insert(return_vector.end(), b.begin(), b.end());
                return return_vector;
            }
            case 2:
            {
                vector<float> a =
                    vector<float>{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};
                vector<float> b =
                    vector<float>{102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113};
                auto return_vector = vector<float>();
                return_vector.insert(return_vector.end(), a.begin(), a.end());
                return_vector.insert(return_vector.end(), b.begin(), b.end());
                return return_vector;
            }
            case 3:
            {
                vector<float> a =
                    vector<float>{0,  1,  2,  3,  4,  5,  6,  7,  8,  9,  10, 11, 12, 13, 14, 15,
                                  16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
                                  32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
                                  48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63};
                vector<float> b = vector<float>{921, 922, 925, 926, 937, 938, 941, 942};
                auto return_vector = vector<float>();
                return_vector.insert(return_vector.end(), a.begin(), a.end());
                return_vector.insert(return_vector.end(), b.begin(), b.end());
                return return_vector;
            }
            case 4:
            {
                vector<float> a =
                    vector<float>{0,  1,  2,  3,  4,  5,  6,  7,  8,  9,  10, 11, 12, 13, 14, 15,
                                  16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
                                  32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
                                  48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63};
                vector<float> b = vector<float>{900, 902, 908, 910, 932, 934, 940, 942};
                auto return_vector = vector<float>();
                return_vector.insert(return_vector.end(), a.begin(), a.end());
                return_vector.insert(return_vector.end(), b.begin(), b.end());
                return return_vector;
            }
            case 5:
            {
                vector<float> a =
                    vector<float>{0,  1,  2,  3,  4,  5,  6,  7,  8,  9,  10, 11, 12, 13, 14, 15,
                                  16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
                                  32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
                                  48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63};
                vector<float> b = vector<float>{900, 903, 908, 911, 932, 935, 940, 943};
                auto return_vector = vector<float>();
                return_vector.insert(return_vector.end(), a.begin(), a.end());
                return_vector.insert(return_vector.end(), b.begin(), b.end());
                return return_vector;
            }
            default: return vector<float>();
            }
        }

        template <>
        vector<float> generate_output<op::ReplaceSlice, float>(int option)
        {
            switch (option)
            {
            case 0:
            {
                vector<float> result = vector<float>{808};
                auto return_vector = vector<float>();
                return_vector.insert(return_vector.end(), result.begin(), result.end());
                return return_vector;
            }
            case 1:
            {
                vector<float> result =
                    vector<float>{1, 102, 103, 4, 5, 106, 107, 8, 9, 110, 111, 12, 13, 14, 15, 16};
                auto return_vector = vector<float>();
                return_vector.insert(return_vector.end(), result.begin(), result.end());
                return return_vector;
            }
            case 2:
            {
                vector<float> result = vector<float>{
                    0, 1, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 14, 15};
                auto return_vector = vector<float>();
                return_vector.insert(return_vector.end(), result.begin(), result.end());
                return return_vector;
            }
            case 3:
            {
                vector<float> result = vector<float>{
                    0,  1,  2,  3,  4,  5,   6,   7,  8,  9,   10,  11, 12, 13, 14, 15,
                    16, 17, 18, 19, 20, 921, 922, 23, 24, 925, 926, 27, 28, 29, 30, 31,
                    32, 33, 34, 35, 36, 937, 938, 39, 40, 941, 942, 43, 44, 45, 46, 47,
                    48, 49, 50, 51, 52, 53,  54,  55, 56, 57,  58,  59, 60, 61, 62, 63};
                auto return_vector = vector<float>();
                return_vector.insert(return_vector.end(), result.begin(), result.end());
                return return_vector;
            }
            case 4:
            {
                vector<float> result = vector<float>{
                    900, 1,  902, 3,  4,  5,  6,  7,  908, 9,  910, 11, 12, 13, 14, 15,
                    16,  17, 18,  19, 20, 21, 22, 23, 24,  25, 26,  27, 28, 29, 30, 31,
                    932, 33, 934, 35, 36, 37, 38, 39, 940, 41, 942, 43, 44, 45, 46, 47,
                    48,  49, 50,  51, 52, 53, 54, 55, 56,  57, 58,  59, 60, 61, 62, 63};
                auto return_vector = vector<float>();
                return_vector.insert(return_vector.end(), result.begin(), result.end());
                return return_vector;
            }
            case 5:
            {
                vector<float> result = vector<float>{
                    900, 1,  2,  903, 4,  5,  6,  7,  908, 9,  10, 911, 12, 13, 14, 15,
                    16,  17, 18, 19,  20, 21, 22, 23, 24,  25, 26, 27,  28, 29, 30, 31,
                    932, 33, 34, 935, 36, 37, 38, 39, 940, 41, 42, 943, 44, 45, 46, 47,
                    48,  49, 50, 51,  52, 53, 54, 55, 56,  57, 58, 59,  60, 61, 62, 63};
                auto return_vector = vector<float>();
                return_vector.insert(return_vector.end(), result.begin(), result.end());
                return return_vector;
            }
            default: return vector<float>();
            }
        }
    }
}