// Microsoft (c) 2019
/**
 * \brief Unit tests for ir::Reverse
 * \author generated by script
 */

#include "nnfusion/core/operators/reverse.hpp"
#include "../test_util/common.hpp"
#include "nnfusion/core/operators/parameter.hpp"

using namespace ngraph;

namespace nnfusion
{
    namespace test
    {
        template <typename T, size_t N>
        using NDArray = nnfusion::test::NDArrayay<T, N>;
    }

    namespace inventory
    {
        template <>
        shared_ptr<op::Reverse> create_object<op::Reverse, float>(int option)
        {
            switch (option)
            {
            case 0:
            {
                Shape shape{};
                auto A = make_shared<op::Parameter>(element::f32, shape);
                return make_shared<op::Reverse>(A, AxisSet{});
            }
            case 1:
            {
                Shape shape{8};
                auto A = make_shared<op::Parameter>(element::f32, shape);
                return make_shared<op::Reverse>(A, AxisSet{});
            }
            case 2:
            {
                Shape shape{8};
                auto A = make_shared<op::Parameter>(element::f32, shape);
                return make_shared<op::Reverse>(A, AxisSet{0});
            }
            case 3:
            {
                Shape shape{4, 3};
                auto A = make_shared<op::Parameter>(element::f32, shape);
                return make_shared<op::Reverse>(A, AxisSet{});
            }
            case 4:
            {
                Shape shape{4, 3};
                auto A = make_shared<op::Parameter>(element::f32, shape);
                return make_shared<op::Reverse>(A, AxisSet{0});
            }
            case 5:
            {
                Shape shape{4, 3};
                auto A = make_shared<op::Parameter>(element::f32, shape);
                return make_shared<op::Reverse>(A, AxisSet{1});
            }
            case 6:
            {
                Shape shape{4, 3};
                auto A = make_shared<op::Parameter>(element::f32, shape);
                return make_shared<op::Reverse>(A, AxisSet{0, 1});
            }
            case 7:
            {
                Shape shape{2, 4, 3};
                auto A = make_shared<op::Parameter>(element::f32, shape);
                return make_shared<op::Reverse>(A, AxisSet{});
            }
            case 8:
            {
                Shape shape{2, 4, 3};
                auto A = make_shared<op::Parameter>(element::f32, shape);
                return make_shared<op::Reverse>(A, AxisSet{0});
            }
            case 9:
            {
                Shape shape{2, 4, 3};
                auto A = make_shared<op::Parameter>(element::f32, shape);
                return make_shared<op::Reverse>(A, AxisSet{1});
            }
            case 10:
            {
                Shape shape{2, 4, 3};
                auto A = make_shared<op::Parameter>(element::f32, shape);
                return make_shared<op::Reverse>(A, AxisSet{2});
            }
            case 11:
            {
                Shape shape{2, 4, 3};
                auto A = make_shared<op::Parameter>(element::f32, shape);
                return make_shared<op::Reverse>(A, AxisSet{0, 1});
            }
            case 12:
            {
                Shape shape{2, 4, 3};
                auto A = make_shared<op::Parameter>(element::f32, shape);
                return make_shared<op::Reverse>(A, AxisSet{0, 2});
            }
            case 13:
            {
                Shape shape{2, 4, 3};
                auto A = make_shared<op::Parameter>(element::f32, shape);
                return make_shared<op::Reverse>(A, AxisSet{1, 2});
            }
            case 14:
            {
                Shape shape{2, 4, 3};
                auto A = make_shared<op::Parameter>(element::f32, shape);
                return make_shared<op::Reverse>(A, AxisSet{0, 1, 2});
            }
            default: return nullptr;
            }
        }

        template <>
        vector<float> generate_input<op::Reverse, float>(int option)
        {
            switch (option)
            {
            case 0:
            {
                vector<float> a = vector<float>{6};
                auto return_vector = vector<float>();
                return_vector.insert(return_vector.end(), a.begin(), a.end());
                return return_vector;
            }
            case 1:
            {
                vector<float> a = vector<float>{0, 1, 2, 3, 4, 5, 6, 7};
                auto return_vector = vector<float>();
                return_vector.insert(return_vector.end(), a.begin(), a.end());
                return return_vector;
            }
            case 2:
            {
                vector<float> a = vector<float>{0, 1, 2, 3, 4, 5, 6, 7};
                auto return_vector = vector<float>();
                return_vector.insert(return_vector.end(), a.begin(), a.end());
                return return_vector;
            }
            case 3:
            {
                vector<float> a =
                    test::NDArray<float, 2>({{0, 1, 2}, {3, 4, 5}, {6, 7, 8}, {9, 10, 11}})
                        .get_vector();
                auto return_vector = vector<float>();
                return_vector.insert(return_vector.end(), a.begin(), a.end());
                return return_vector;
            }
            case 4:
            {
                vector<float> a =
                    test::NDArray<float, 2>({{0, 1, 2}, {3, 4, 5}, {6, 7, 8}, {9, 10, 11}})
                        .get_vector();
                auto return_vector = vector<float>();
                return_vector.insert(return_vector.end(), a.begin(), a.end());
                return return_vector;
            }
            case 5:
            {
                vector<float> a =
                    test::NDArray<float, 2>({{0, 1, 2}, {3, 4, 5}, {6, 7, 8}, {9, 10, 11}})
                        .get_vector();
                auto return_vector = vector<float>();
                return_vector.insert(return_vector.end(), a.begin(), a.end());
                return return_vector;
            }
            case 6:
            {
                vector<float> a =
                    test::NDArray<float, 2>({{0, 1, 2}, {3, 4, 5}, {6, 7, 8}, {9, 10, 11}})
                        .get_vector();
                auto return_vector = vector<float>();
                return_vector.insert(return_vector.end(), a.begin(), a.end());
                return return_vector;
            }
            case 7:
            {
                vector<float> a = test::NDArray<float, 3>(
                                      {{{0, 1, 2}, {3, 4, 5}, {6, 7, 8}, {9, 10, 11}},
                                       {{12, 13, 14}, {15, 16, 17}, {18, 19, 20}, {21, 22, 23}}})
                                      .get_vector();
                auto return_vector = vector<float>();
                return_vector.insert(return_vector.end(), a.begin(), a.end());
                return return_vector;
            }
            case 8:
            {
                vector<float> a = test::NDArray<float, 3>(
                                      {{{0, 1, 2}, {3, 4, 5}, {6, 7, 8}, {9, 10, 11}},
                                       {{12, 13, 14}, {15, 16, 17}, {18, 19, 20}, {21, 22, 23}}})
                                      .get_vector();
                auto return_vector = vector<float>();
                return_vector.insert(return_vector.end(), a.begin(), a.end());
                return return_vector;
            }
            case 9:
            {
                vector<float> a = test::NDArray<float, 3>(
                                      {{{0, 1, 2}, {3, 4, 5}, {6, 7, 8}, {9, 10, 11}},
                                       {{12, 13, 14}, {15, 16, 17}, {18, 19, 20}, {21, 22, 23}}})
                                      .get_vector();
                auto return_vector = vector<float>();
                return_vector.insert(return_vector.end(), a.begin(), a.end());
                return return_vector;
            }
            case 10:
            {
                vector<float> a = test::NDArray<float, 3>(
                                      {{{0, 1, 2}, {3, 4, 5}, {6, 7, 8}, {9, 10, 11}},
                                       {{12, 13, 14}, {15, 16, 17}, {18, 19, 20}, {21, 22, 23}}})
                                      .get_vector();
                auto return_vector = vector<float>();
                return_vector.insert(return_vector.end(), a.begin(), a.end());
                return return_vector;
            }
            case 11:
            {
                vector<float> a = test::NDArray<float, 3>(
                                      {{{0, 1, 2}, {3, 4, 5}, {6, 7, 8}, {9, 10, 11}},
                                       {{12, 13, 14}, {15, 16, 17}, {18, 19, 20}, {21, 22, 23}}})
                                      .get_vector();
                auto return_vector = vector<float>();
                return_vector.insert(return_vector.end(), a.begin(), a.end());
                return return_vector;
            }
            case 12:
            {
                vector<float> a = test::NDArray<float, 3>(
                                      {{{0, 1, 2}, {3, 4, 5}, {6, 7, 8}, {9, 10, 11}},
                                       {{12, 13, 14}, {15, 16, 17}, {18, 19, 20}, {21, 22, 23}}})
                                      .get_vector();
                auto return_vector = vector<float>();
                return_vector.insert(return_vector.end(), a.begin(), a.end());
                return return_vector;
            }
            case 13:
            {
                vector<float> a = test::NDArray<float, 3>(
                                      {{{0, 1, 2}, {3, 4, 5}, {6, 7, 8}, {9, 10, 11}},
                                       {{12, 13, 14}, {15, 16, 17}, {18, 19, 20}, {21, 22, 23}}})
                                      .get_vector();
                auto return_vector = vector<float>();
                return_vector.insert(return_vector.end(), a.begin(), a.end());
                return return_vector;
            }
            case 14:
            {
                vector<float> a = test::NDArray<float, 3>(
                                      {{{0, 1, 2}, {3, 4, 5}, {6, 7, 8}, {9, 10, 11}},
                                       {{12, 13, 14}, {15, 16, 17}, {18, 19, 20}, {21, 22, 23}}})
                                      .get_vector();
                auto return_vector = vector<float>();
                return_vector.insert(return_vector.end(), a.begin(), a.end());
                return return_vector;
            }
            default: return vector<float>();
            }
        }

        template <>
        vector<float> generate_output<op::Reverse, float>(int option)
        {
            switch (option)
            {
            case 0:
            {
                vector<float> result = vector<float>{6};
                auto return_vector = vector<float>();
                return_vector.insert(return_vector.end(), result.begin(), result.end());
                return return_vector;
            }
            case 1:
            {
                vector<float> result = vector<float>{0, 1, 2, 3, 4, 5, 6, 7};
                auto return_vector = vector<float>();
                return_vector.insert(return_vector.end(), result.begin(), result.end());
                return return_vector;
            }
            case 2:
            {
                vector<float> result = vector<float>{7, 6, 5, 4, 3, 2, 1, 0};
                auto return_vector = vector<float>();
                return_vector.insert(return_vector.end(), result.begin(), result.end());
                return return_vector;
            }
            case 3:
            {
                vector<float> result =
                    test::NDArray<float, 2>({{0, 1, 2}, {3, 4, 5}, {6, 7, 8}, {9, 10, 11}})
                        .get_vector();
                auto return_vector = vector<float>();
                return_vector.insert(return_vector.end(), result.begin(), result.end());
                return return_vector;
            }
            case 4:
            {
                vector<float> result =
                    test::NDArray<float, 2>({{9, 10, 11}, {6, 7, 8}, {3, 4, 5}, {0, 1, 2}})
                        .get_vector();
                auto return_vector = vector<float>();
                return_vector.insert(return_vector.end(), result.begin(), result.end());
                return return_vector;
            }
            case 5:
            {
                vector<float> result =
                    test::NDArray<float, 2>({{2, 1, 0}, {5, 4, 3}, {8, 7, 6}, {11, 10, 9}})
                        .get_vector();
                auto return_vector = vector<float>();
                return_vector.insert(return_vector.end(), result.begin(), result.end());
                return return_vector;
            }
            case 6:
            {
                vector<float> result =
                    test::NDArray<float, 2>({{11, 10, 9}, {8, 7, 6}, {5, 4, 3}, {2, 1, 0}})
                        .get_vector();
                auto return_vector = vector<float>();
                return_vector.insert(return_vector.end(), result.begin(), result.end());
                return return_vector;
            }
            case 7:
            {
                vector<float> result =
                    test::NDArray<float, 3>(
                        {{{0, 1, 2}, {3, 4, 5}, {6, 7, 8}, {9, 10, 11}},
                         {{12, 13, 14}, {15, 16, 17}, {18, 19, 20}, {21, 22, 23}}})
                        .get_vector();
                auto return_vector = vector<float>();
                return_vector.insert(return_vector.end(), result.begin(), result.end());
                return return_vector;
            }
            case 8:
            {
                vector<float> result =
                    test::NDArray<float, 3>(
                        {{{12, 13, 14}, {15, 16, 17}, {18, 19, 20}, {21, 22, 23}},
                         {{0, 1, 2}, {3, 4, 5}, {6, 7, 8}, {9, 10, 11}}})
                        .get_vector();
                auto return_vector = vector<float>();
                return_vector.insert(return_vector.end(), result.begin(), result.end());
                return return_vector;
            }
            case 9:
            {
                vector<float> result =
                    test::NDArray<float, 3>(
                        {{{9, 10, 11}, {6, 7, 8}, {3, 4, 5}, {0, 1, 2}},
                         {{21, 22, 23}, {18, 19, 20}, {15, 16, 17}, {12, 13, 14}}})
                        .get_vector();
                auto return_vector = vector<float>();
                return_vector.insert(return_vector.end(), result.begin(), result.end());
                return return_vector;
            }
            case 10:
            {
                vector<float> result =
                    test::NDArray<float, 3>(
                        {{{2, 1, 0}, {5, 4, 3}, {8, 7, 6}, {11, 10, 9}},
                         {{14, 13, 12}, {17, 16, 15}, {20, 19, 18}, {23, 22, 21}}})
                        .get_vector();
                auto return_vector = vector<float>();
                return_vector.insert(return_vector.end(), result.begin(), result.end());
                return return_vector;
            }
            case 11:
            {
                vector<float> result =
                    test::NDArray<float, 3>(
                        {{{21, 22, 23}, {18, 19, 20}, {15, 16, 17}, {12, 13, 14}},
                         {{9, 10, 11}, {6, 7, 8}, {3, 4, 5}, {0, 1, 2}}})
                        .get_vector();
                auto return_vector = vector<float>();
                return_vector.insert(return_vector.end(), result.begin(), result.end());
                return return_vector;
            }
            case 12:
            {
                vector<float> result =
                    test::NDArray<float, 3>(
                        {{{14, 13, 12}, {17, 16, 15}, {20, 19, 18}, {23, 22, 21}},
                         {{2, 1, 0}, {5, 4, 3}, {8, 7, 6}, {11, 10, 9}}})
                        .get_vector();
                auto return_vector = vector<float>();
                return_vector.insert(return_vector.end(), result.begin(), result.end());
                return return_vector;
            }
            case 13:
            {
                vector<float> result =
                    test::NDArray<float, 3>(
                        {{{11, 10, 9}, {8, 7, 6}, {5, 4, 3}, {2, 1, 0}},
                         {{23, 22, 21}, {20, 19, 18}, {17, 16, 15}, {14, 13, 12}}})
                        .get_vector();
                auto return_vector = vector<float>();
                return_vector.insert(return_vector.end(), result.begin(), result.end());
                return return_vector;
            }
            case 14:
            {
                vector<float> result =
                    test::NDArray<float, 3>(
                        {{{23, 22, 21}, {20, 19, 18}, {17, 16, 15}, {14, 13, 12}},
                         {{11, 10, 9}, {8, 7, 6}, {5, 4, 3}, {2, 1, 0}}})
                        .get_vector();
                auto return_vector = vector<float>();
                return_vector.insert(return_vector.end(), result.begin(), result.end());
                return return_vector;
            }
            default: return vector<float>();
            }
        }
    }
}