// Microsoft (c) 2019
/**
 * \brief Unit tests for ir::Sqrt
 * \author generated by script
 */

#include "nnfusion/core/operators/sqrt.hpp"
#include "../test_util/common.hpp"
#include "nnfusion/core/operators/parameter.hpp"

using namespace ngraph;

namespace nnfusion
{
    namespace test
    {
        template <typename T, size_t N>
        using NDArray = nnfusion::test::NDArray<T, N>;
    }

    namespace inventory
    {
        template <>
        shared_ptr<op::Sqrt> create_object<op::Sqrt, float>(int option)
        {
            switch (option)
            {
            case 0:
            {
                Shape shape{2, 3};
                auto A = make_shared<op::Parameter>(element::f32, shape);
                return make_shared<op::Sqrt>(A);
            }
            default: return nullptr;
            }
        }

        template <>
        vector<float> generate_input<op::Sqrt, float>(int option)
        {
            switch (option)
            {
            case 0:
            {
                vector<float> a = vector<float>{16, 4, 81, 100, 10000, 0};
                auto return_vector = vector<float>();
                return_vector.insert(return_vector.end(), a.begin(), a.end());
                return return_vector;
            }
            default: return vector<float>();
            }
        }

        template <>
        vector<float> generate_output<op::Sqrt, float>(int option)
        {
            switch (option)
            {
            case 0:
            {
                vector<float> result = vector<float>{4, 2, 9, 10, 100, 0};
                auto return_vector = vector<float>();
                return_vector.insert(return_vector.end(), result.begin(), result.end());
                return return_vector;
            }
            default: return vector<float>();
            }
        }
    }
}